<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_cogeneration01_qjlct.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_cogeneration01_qjlct" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc_cogeneration01";
        publicData.sceneName = "1号余热发电";
    </script>
</head>
<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style="width: 1535px; height:745px; margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_cogeneration01_qjlct.png'); width: 1535px; height: 745px; overflow: hidden;">
    <div id="ConnectionGround" style="width: 1535px; height: 745px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6"></div>
    <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1535px;height: 745px;"></div>   
    <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div>
    <%--贴标签处--%>
        <%--<button onclick="CheckTags()">检查标签</button>--%>
    <%--模拟量--%>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 68px; left: 389px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE04_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 621px; left: 729px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 73px; left: 905px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TFT01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 70px; left: 504px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE07B_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 348px; left: 1110px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 530px; left: 670px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE06B_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 348px; left: 1002px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE21_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 396px; left: 1184px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE06A_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 574px; left: 999px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE07A_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 574px; left: 1121px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT12_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 425px; left: 1061px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLT01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 494px; left: 1072px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT01A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 69px; left: 789px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TFT02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 622px; left: 633px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT04_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 657px; left: 732px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT02A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 130px; left: 1187px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 131px; left: 1268px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT03A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 131px; left: 1349px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLZ02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 346px; left: 155px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLZ01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 432px; left: 610px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT11_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 432px; left: 787px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT05_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 308px; left: 366px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLT02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 373px; left: 132px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLZ01_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 448px; left: 610px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_DEH_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 161px; left: 885px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W1M_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 589px; left: 1244px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W2M_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 589px; left: 1353px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W3M_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 589px; left: 1449px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_WLT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 453px; left: 1360px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_WTI01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 349px; left: 1301px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_WTI02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 349px; left: 1411px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W4M_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 333px; left: 1301px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W5M_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 332px; left: 1411px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W4M_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 319px; left: 1301px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLT04_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 358px; left: 410px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W1M_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 622px; left: 1244px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W2M_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 622px; left: 1354px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W3M_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 622px; left: 1450px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_VVF_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 432px; left: 52px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_VVF_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 450px; left: 51px; position:absolute;color:#4cff00;text-align:right; right: 1434px;"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_CLT01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 464px; left: 257px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT06A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 559px; left: 47px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT07A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 584px; left: 47px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT08A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 606px; left: 47px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT10A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 631px; left: 47px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09A1_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 560px; left: 140px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09A1_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 560px; left: 211px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09A2_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 574px; left: 140px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09A2_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 574px; left: 211px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09B2_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 613px; left: 140px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09B2_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 613px; left: 212px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09B1_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 597px; left: 212px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE09B1_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 597px; left: 140px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE10_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 638px; left: 143px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE10_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 653px; left: 143px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE11A_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 638px; left: 212px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE11B_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 653px; left: 212px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TXIA03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 228px; left: 1284px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TXIA04_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 228px; left: 1352px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TZIA01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 200px; left: 1320px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE12_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 680px; left: 142px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE13_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 680px; left: 220px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TZDIA01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 687px; left: 38px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18A_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 600px; left: 291px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18B_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 600px; left: 363px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18C_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 600px; left: 430px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18D_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 600px; left: 494px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18A_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 626px; left: 291px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18B_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 626px; left: 363px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18C_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 626px; left: 430px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE18D_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 626px; left: 490px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE16A_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 561px; left: 316px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE20A_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 561px; left: 401px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE17A_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 561px; left: 477px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE20B_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 576px; left: 401px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE16B_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 576px; left: 316px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE17B_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 576px; left: 477px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1ATT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 28px; left: 173px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1AFT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 28px; left: 257px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1SPT02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 57px; left: 32px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1STT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 59px; left: 169px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1SFT02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 59px; left: 257px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2ATT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 90px; left: 170px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2SPT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 120px; left: 32px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2AFT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 90px; left: 256px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2SFT02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 120px; left: 256px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TPT09A_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 661px; left: 44px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLZ02_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 360px; left: 155px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19A_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 660px; left: 291px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19B_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 660px; left: 362px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19D_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 660px; left: 497px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19C_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 660px; left: 428px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19A_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 690px; left: 294px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19B_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 690px; left: 362px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19D_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 690px; left: 496px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE19C_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 690px; left: 428px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TSIA03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 177px; left: 885px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TXIA01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 258px; left: 1285px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TXIA02_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 258px; left: 1353px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TTE08B_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 685px; left: 602px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2ATT04_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 688px; left: 1270px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2STT04_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 688px; left: 1414px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1APT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 29px; left: 32px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2APT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 91px; left: 32px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_A1M_AO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 587px; left: 848px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_A1M_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 601px; left: 848px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_CFT01_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:99px; display:block; top: 77px; left: 1302px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2APT06_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:70px; display:block; top: 656px; left: 1229px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2SPT04_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:70px; display:block; top: 656px; left: 1383px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLIS04_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 372px; left: 746px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2STT03_AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 118px; left: 171px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W1M_AI1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 604px; left: 1244px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W2M_AI1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 604px; left: 1354px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W3M_AI1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 604px; left: 1450px; position:absolute;color:#4cff00;text-align:right"></div>
    <%--开关量--%>  
    <%--圆形--%>  
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T9M_DI1>BoolSignal" style="position: absolute; top:515px; left: 893px; height: 32px; width: 32px;" data-option="RelatedTags='Cogeneration01_T9M_DO,Cogeneration01_T9M_DI2,Cogeneration01_T9M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T10M_DI1>BoolSignal" style="position: absolute; top:515px; left: 852px; height: 32px; width: 32px;" data-option="RelatedTags='Cogeneration01_T10M_DO,Cogeneration01_T10M_DI2,Cogeneration01_T10M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T11M_DI1>BoolSignal" style="position: absolute; top:383px; left: 473px; height: 32px; width: 32px;" data-option="RelatedTags='Cogeneration01_T11M_DO,Cogeneration01_T11M_DI2,Cogeneration01_T11M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_A1M_DI1>BoolSignal" style="position: absolute; top:605px; left: 938px; height: 30px; width: 30px;" data-option="RelatedTags='Cogeneration01_A1M_DO,Cogeneration01_A1M_DI2,Cogeneration01_A1M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T8M_DI1>BoolSignal" style="position: absolute; top:652px; left: 938px; height: 30px; width: 30px;" data-option="RelatedTags='Cogeneration01_T8M_DO,Cogeneration01_T8M_DI2,Cogeneration01_T8M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W1M_DI1>BoolSignal" style="position: absolute; top:510px; left: 1283px; height: 30px; width: 30px;" data-option="RelatedTags='Cogeneration01_W1M_DO1,Cogeneration01_W1M_DI2,Cogeneration01_W1M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W2M_DI1>BoolSignal" style="position: absolute; top:510px; left: 1389px; height: 30px; width: 30px;" data-option="RelatedTags='Cogeneration01_W2M_DO1,Cogeneration01_W2M_DI2,Cogeneration01_W2M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W3M_DI1>BoolSignal" style="position: absolute; top:510px; left: 1493px; height: 30px; width: 30px;" data-option="RelatedTags='Cogeneration01_W3M_DO1,Cogeneration01_W3M_DI2,Cogeneration01_W3M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_C2M_DI4>BoolSignal" style="position: absolute; top:509px; left: 170px; height: 30px; width: 30px;" data-option="RelatedTags='Cogeneration01_C2M_DO,Cogeneration01_C2M_DI1,Cogeneration01_C2M_DI4',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_C1M_DI4>BoolSignal" style="position: absolute; top:457px; left: 170px; height: 30px; width: 30px;" data-option="RelatedTags='Cogeneration01_C1M_DO,Cogeneration01_C1M_DI1,Cogeneration01_C1M_DI4',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2A7M_DI1>BoolSignal" style="position: absolute; top:300px; left: 817px; height: 21px; width: 21px;" data-option="RelatedTags='Cogeneration01_F_2A7M_DO,Cogeneration01_F_2A7M_DI2,Cogeneration01_F_2A7M_DI1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <%--方形--%>  
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T17YM_DI4>BoolSignal" style="position: absolute; top:84px; left: 669px; height: 13px; width: 35px;" data-option="RelatedTags='Cogeneration01_T17YM_DO1,Cogeneration01_T17YM_DI5,Cogeneration01_T17YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T18YM_DI4>BoolSignal" style="position: absolute; top:508px; left: 1156px; height: 23px; width: 15px;" data-option="RelatedTags='Cogeneration01_T18YM_DO1,Cogeneration01_T18YM_DI5,Cogeneration01_T18YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T19YM_DI4>BoolSignal" style="position: absolute; top:508px; left: 1027px; height: 23px; width: 15px;" data-option="RelatedTags='Cogeneration01_T19YM_DO1,Cogeneration01_T19YM_DI5,Cogeneration01_T19YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T20YM_DI4>BoolSignal" style="position: absolute; top:400px; left: 1137px; height: 23px; width: 15px;" data-option="RelatedTags='Cogeneration01_T20YM_DO1,Cogeneration01_T20YM_DI5,Cogeneration01_T20YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_T21YM_DI4>BoolSignal" style="position: absolute; top:400px; left: 1047px; height: 23px; width: 15px;" data-option="RelatedTags='Cogeneration01_T21YM_DO1,Cogeneration01_T21YM_DI5,Cogeneration01_T21YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W4M_DI1>BoolSignal" style="position: absolute; top:386px; left: 1332px; height: 12px; width: 22px;" data-option="RelatedTags='Cogeneration01_W4M_DO1,Cogeneration01_W4M_DI2,Cogeneration01_W4M_DI1',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W5M_DI1>BoolSignal" style="position: absolute; top:386px; left: 1441px; height: 12px; width: 22px;" data-option="RelatedTags='Cogeneration01_W5M_DO1,Cogeneration01_W5M_DI2,Cogeneration01_W5M_DI1',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W6YM_DI4>BoolSignal" style="position: absolute; top:548px; left: 1290px; height: 20px; width: 15px;" data-option="RelatedTags='Cogeneration01_W6YM_DO1,Cogeneration01_W6YM_DI5,Cogeneration01_W6YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W7YM_DI4>BoolSignal" style="position: absolute; top:548px; left: 1396px; height: 20px; width: 15px;" data-option="RelatedTags='Cogeneration01_W7YM_DO1,Cogeneration01_W7YM_DI5,Cogeneration01_W7YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_W8YM_DI4>BoolSignal" style="position: absolute; top:548px; left: 1501px; height: 20px; width: 15px;" data-option="RelatedTags='Cogeneration01_W8YM_DO1,Cogeneration01_W8YM_DI5,Cogeneration01_W8YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1A3YM_DI4>BoolSignal" style="position: absolute; top:39px; left: 139px; height: 13px; width: 30px;" data-option="RelatedTags='Cogeneration01_F_1A3YM_DO1,Cogeneration01_F_1A3YM_DI5,Cogeneration01_F_1A3YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_1S3YM_DI4>BoolSignal" style="position: absolute; top:70px; left: 139px; height: 13px; width: 30px;" data-option="RelatedTags='Cogeneration01_F_1S3YM_DO1,Cogeneration01_F_1S3YM_DI5,Cogeneration01_F_1S3YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2A3YM_DI4>BoolSignal" style="position: absolute; top:101px; left: 139px; height: 13px; width: 30px;" data-option="RelatedTags='Cogeneration01_F_2A3YM_DO1,Cogeneration01_F_2A3YM_DI5,Cogeneration01_F_2A3YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration01_F_2S3YM_DI4>BoolSignal" style="position: absolute; top:132px; left: 139px; height: 13px; width: 30px;" data-option="RelatedTags='Cogeneration01_F_2S3YM_DO1,Cogeneration01_F_2S3YM_DI5,Cogeneration01_F_2S3YM_DI4',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'"></div>
    <%--汉字隐藏--%>
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK13_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 282px; left: 550px; color:yellow;font-size:12px;">超速试验投入</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK11_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 286px; left: 34px; color:yellow;font-size:12px;">远程转速给定已投</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TPS09C_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 282px; left: 321px; color:yellow;font-size:12px;">高压油压力小于0.65MPa启电动油泵</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK6_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 127px; left: 990px; color:red;font-size:12px;">主汽门全开</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK5_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 169px; left: 990px; color:red;font-size:12px;">主汽门关闭</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK4_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 266px; left: 656px; color:#4cff00;font-size:12px;">盘车装置投入</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK9_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 154px; left: 525px; color:red;font-size:12px;">505报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK8_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 211px; left: 34px; color:#4cff00;font-size:12px;">505跳闸</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK12_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 271px; left: 34px; color:yellow;font-size:12px;">505控制ok</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K10_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 152px; left: 306px; color:red;font-size:12px;">汽机转速大于3180r/min报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TLIS04_H>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 154px; left: 34px; color:red;font-size:12px;">油箱油位高报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TLIS04_L>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 154px; left: 134px; color:red;font-size:12px;">油箱油位低报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K3_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 211px; left: 92px; color:#4cff00;font-size:12px;">润滑油压低于0.08MPa停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK10_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 267px; left: 321px; color:yellow;font-size:12px;">转速低于500rpm阀位高于30%</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_TK14_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 266px; left: 550px; color:yellow;font-size:12px;">进汽压力控制已投</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K2_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 208px; left: 321px; color:#4cff00;font-size:12px;">汽机排汽压力大于0.07MPa停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K4_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 226px; left: 34px; color:#4cff00;font-size:12px;">汽机胀差大于3.3mm小于-2.2mm停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K8_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 241px; left: 34px; color:#4cff00;font-size:12px;">汽机转子负向轴位移小于-0.6mm停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K6_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 223px; left: 321px; color:#4cff00;font-size:12px;">汽机前后轴承震动大于90um停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K7_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 238px; left: 321px; color:#4cff00;font-size:12px;">汽机转子正向轴位移大于+0.6mm停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K9_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 238px; left: 550px; color:#4cff00;font-size:12px;">发电机前后轴瓦振动大于30um停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K11_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 168px; left: 525px; color:red;font-size:12px;">润滑油压低于0.13MPa报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K16_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 182px; left: 525px; color:red;font-size:12px;">汽机胀差大于3mm小于-2mm报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K13_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 169px; left: 34px; color:red;font-size:12px;">汽机前后轴瓦振动大于25um报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K15_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 208px; left: 550px; color:#4cff00;font-size:12px;">汽机转子负向轴位移小于-0.4mm停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K14_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 222px; left: 550px; color:#4cff00;font-size:12px;">汽机转子正向轴位移大于+0.4mm停机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K17_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 167px; left: 306px; color:red;font-size:12px;">发电机前后轴瓦振动大于25um报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_K18_DI>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 196px; left: 525px; color:red;font-size:12px;">汽机排汽压力大于0.04MPa报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_WLS01_H>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 183px; left: 34px; color:red;font-size:12px;">1#冷却塔风机减速箱内油位高报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_WLS01_L>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 256px; left: 34px; color:#4cff00;font-size:12px;">1#冷却塔风机减速箱内油位低停风机</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_WVS01_H>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 181px; left: 306px; color:red;font-size:12px;">1#冷却塔风机振动高报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_WVS02_H>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 198px; left: 34px; color:red;font-size:12px;">2#冷却塔风机振动高报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_WLS02_H>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 195px; left: 306px; color:red;font-size:12px;">2#冷却塔风机减速箱内油位高报警</div> 
      <div id="zc_nxjc_qtx_efc>Cogeneration01_WLS02_L>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 252px; left: 321px; color:#4cff00;font-size:12px;">2#冷却塔风机减速箱内油位低停风机</div> 
    <%--棒图--%>
      <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLT02_AI>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:11px; height:48px; position:absolute; top: 359px; left: 257px;"></div> 
      <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration01_TLT04_AI>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:11px; height:48px; position:absolute; top: 359px; left: 372px;"></div> 
      <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration01_WLT03_AI>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:240px; height:27px; position:absolute; top: 475px; left: 1282px;"></div> 
    </div>
</body>
</html>


