<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_clinker02_ytblj.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_clinker02_ytblj" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc";
        publicData.sceneName = "4#水泥包装";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <%--<div id="ForeGround" style=" width: 1480px; height: 760px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>--%>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_clinker02_ytblj.png'); width: 1480px; height: 783px; overflow: hidden;">
  <%-- <div id="ConnectionGround" style="width: 1480px; height: 760px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
   <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1480px;height: 760px;"></div>   
    <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div>--%>
    <%--标签粘贴处--%>
<%--     <button onclick="CheckTags()">检查标签</button>--%>
 <%--贴标签处--%>
        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT13_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:68px; display:block; top: 98px; left: 164px; position:absolute;color:#4cff00;text-align:right; bottom: 665px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:68px; display:block; top: 78px; left: 164px; position:absolute;color:#4cff00;text-align:right; bottom: 687px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 103px; left: 536px; position:absolute;color:#4cff00;text-align:right; bottom: 662px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 197px; left: 536px; position:absolute;color:#4cff00;text-align:right; bottom: 567px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 297px; left: 536px; position:absolute;color:#4cff00;text-align:right; bottom: 469px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE04_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:51px; display:block; top: 376px; left: 195px; position:absolute;color:blue;text-align:right; bottom: 388px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:51px; display:block; top: 396px; left: 195px; position:absolute;color:blue;text-align:right; bottom: 367px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G27ARC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:62px; display:block; top: 396px; left: 274px; position:absolute;color:blue;text-align:right; bottom: 344px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE06_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 386px; left: 486px; position:absolute;color:blue;text-align:right; bottom: 356px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 404px; left: 486px; position:absolute;color:blue;text-align:right; bottom: 336px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G28ARC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:68px; display:block; top: 404px; left: 561px; position:absolute;color:blue;text-align:right; "></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT17_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 69px; left: 604px; position:absolute;color:#4cff00;text-align:right; "></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 97px; left: 603px; position:absolute;color:#4cff00;text-align:right; bottom: 668px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT12_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 158px; left: 603px; position:absolute;color:#4cff00;text-align:right; bottom: 606px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 189px; left: 603px; position:absolute;color:#4cff00;text-align:right; "></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT16_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 255px; left: 603px; position:absolute;color:#4cff00;text-align:right; bottom: 509px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 603px; position:absolute;color:#4cff00;text-align:right; bottom: 483px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G5ASR_VOT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; left: 1023px; position:absolute;color:#4cff00;text-align:right; bottom: 726px; height: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G5ASR_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; left: 1023px; position:absolute;color:#4cff00;text-align:right; bottom: 699px; height: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G6ASR_VOT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; left: 1142px; position:absolute;color:#4cff00;text-align:right; bottom: 726px; height: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G6ASR_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; left: 1142px; position:absolute;color:#4cff00;text-align:right; bottom: 699px; height: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G7ASR_VOT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; left: 1259px; position:absolute;color:#4cff00;text-align:right; bottom: 726px; height: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G7ASR_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; left: 1259px; position:absolute;color:#4cff00;text-align:right; bottom: 699px; height: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G27ARC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:62px; display:block; left: 274px; position:absolute;color:blue;text-align:right; bottom: 364px; height: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G28ARC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:68px; display:block; left: 561px; position:absolute;color:blue;text-align:right; bottom: 356px; height: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; left: 222px; position:absolute;color:blue;text-align:right; bottom: 296px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; left: 312px; position:absolute;color:blue;text-align:right; bottom: 296px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT03_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; left: 401px; position:absolute;color:blue;text-align:right; bottom: 296px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; left: 486px; position:absolute;color:blue;text-align:right; bottom: 296px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT06_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; left: 570px; position:absolute;color:blue;text-align:right; bottom: 296px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT05_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; left: 653px; position:absolute;color:blue;text-align:right; bottom: 296px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ12_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 827px; position:absolute;color:#4cff00;text-align:right; bottom: 590px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ17_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:32px; display:block; left: 802px; position:absolute;color:#4cff00;text-align:right; bottom: 522px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ18_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 818px; position:absolute;color:#4cff00;text-align:right; bottom: 461px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 982px; position:absolute;color:#4cff00;text-align:right; bottom: 656px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 1295px; position:absolute;color:#4cff00;text-align:right; bottom: 650px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT14_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 1295px; position:absolute;color:#4cff00;text-align:right; bottom: 619px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ13_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 1303px; position:absolute;color:#4cff00;text-align:right; bottom: 557px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G26AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 832px; position:absolute;color:#4cff00;text-align:right; bottom: 303px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; left: 1298px; position:absolute;color:#4cff00;text-align:right; bottom: 463px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G16M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 128px; position:absolute;color:#4cff00;text-align:right; height: 18px; top: 685px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G17M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 200px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G18M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 273px; position:absolute;color:#4cff00;text-align:right; bottom: 55px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G19M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 344px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G20M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 415px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 488px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 558px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G23M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 629px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G24M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 700px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G25M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 771px; position:absolute;color:#4cff00;text-align:right; bottom: 56px; height: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT11_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 57px; position:absolute;color:#4cff00;text-align:right; bottom: 31px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT07_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 128px; position:absolute;color:#4cff00;text-align:right; bottom: 31px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT08_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 200px; position:absolute;color:#4cff00;text-align:right; bottom: 31px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT15_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 273px; position:absolute;color:#4cff00;text-align:right; bottom: 31px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT09_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 344px; position:absolute;color:#4cff00;text-align:right; bottom: 31px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT10_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 415px; position:absolute;color:#4cff00;text-align:right; height: 18px; top: 712px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ05_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 57px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 128px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ02_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 200px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ11_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 273px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 344px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ04_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 415px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ06_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 488px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px; top: 736px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ07_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 558px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ08_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 629px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ09_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 700px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ10_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:67px; display:block; left: 771px; position:absolute;color:#4cff00;text-align:right; bottom: 6px; height: 18px; top: 736px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GLT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:48px; display:block; left: 1349px; position:absolute;color:blue;text-align:right; bottom: 103px; height: 18px;"></div>
        <%--<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1LP_T1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1323px; position:absolute;color:#4cff00;text-align:right; bottom: 405px; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1LP_T2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1323px; position:absolute;color:#4cff00;text-align:right; bottom: 377px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1LP_T3_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1323px; position:absolute;color:#4cff00;text-align:right; bottom: 351px; height: 21px;"></div>--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE13_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1392px; position:absolute;color:#4cff00;text-align:right; bottom: 355px; height: 21px;"></div>
       <%-- <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1LP_T4_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1396px; position:absolute;color:#4cff00;text-align:right; bottom: 404px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1LP_T5_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1396px; position:absolute;color:#4cff00;text-align:right; bottom: 379px; height: 21px;"></div>--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1LP_T6_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1392px; position:absolute;color:#4cff00;text-align:right; bottom: 410px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE14_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; left: 1392px; position:absolute;color:#4cff00;text-align:right; bottom: 381px; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G3M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; left: 1255px; position:absolute;color:#4cff00;text-align:right; bottom: 280px; height: 23px;"></div>
        <%--开关量--%>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F8M_AM>BoolSignal" style="position: absolute; top: 472px; left: 19px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_F8M_RD,Clinker02_F8M_RN,Clinker02_F8M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G15M_AM>BoolSignal" style="position: absolute; top: 595px; left: 14px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G15M_RD,Clinker02_G15M_RN,Clinker02_G15M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G16M_AM>BoolSignal" style="position: absolute; top: 594px; left: 94px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G16M_RD,Clinker02_G16M_RN,Clinker02_G16M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G17M_AM>BoolSignal" style="position: absolute; top: 595px; left: 169px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G17M_RD,Clinker02_G17M_RN,Clinker02_G17M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G18M_AM>BoolSignal" style="position: absolute; top: 595px; left: 250px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G18M_RD,Clinker02_G18M_RN,Clinker02_G18M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G19M_AM>BoolSignal" style="position: absolute; top: 594px; left: 323px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G19M_RD,Clinker02_G19M_RN,Clinker02_G19M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G20M_AM>BoolSignal" style="position: absolute; top: 594px; left: 399px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G20M_RD,Clinker02_G20M_RN,Clinker02_G20M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_AM>BoolSignal" style="position: absolute; top: 593px; left: 483px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G21AC_RD,Clinker02_G21AC_RN,Clinker02_G21AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_AM>BoolSignal" style="position: absolute; top: 593px; left: 560px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G22AC_RD,Clinker02_G22AC_RN,Clinker02_G22AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G23M_AM>BoolSignal" style="position: absolute; top: 594px; left: 634px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G23M_RD,Clinker02_G23M_RN,Clinker02_G23M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G24M_AM>BoolSignal" style="position: absolute; top: 595px; left: 712px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G24M_RD,Clinker02_G24M_RN,Clinker02_G24M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G25M_AM>BoolSignal" style="position: absolute; top: 595px; left: 785px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G25M_RD,Clinker02_G25M_RN,Clinker02_G25M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G26AC_AM>BoolSignal" style="position: absolute; top: 448px; left: 769px; height: 30px; width: 30px;" data-option="RelatedTags='Clinker02_G26AC_RD,Clinker02_G26AC_RN,Clinker02_G26AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC1_AM>BoolSignal" style="position: absolute; top: 349px; left: 144px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G36ALC_RD,Clinker02_G36ALC1_RN,Clinker02_G36ALC1_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC2_AM>BoolSignal" style="position: absolute; top: 370px; left: 143px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G36ALC_RD,Clinker02_G36ALC2_RN,Clinker02_G36ALC2_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC3_AM>BoolSignal" style="position: absolute; top: 393px; left: 147px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G36ALC_RD,Clinker02_G36ALC3_RN,Clinker02_G36ALC3_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC4_AM>BoolSignal" style="position: absolute; top: 413px; left: 157px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G36ALC_RD,Clinker02_G36ALC4_RN,Clinker02_G36ALC4_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC5_AM>BoolSignal" style="position: absolute; top: 433px; left: 175px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G36ALC_RD,Clinker02_G36ALC5_RN,Clinker02_G36ALC5_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN>BoolSignal" style="position: absolute; top: 406px; left: 1086px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RN,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:green'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC2_RN>BoolSignal" style="position: absolute; top: 406px; left: 1026px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RN,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:green'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC3_RN>BoolSignal" style="position: absolute; top: 326px; left: 1092px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RN ,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:green'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC4_RN>BoolSignal" style="position: absolute; top: 251px; left: 1035px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RN ,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:green'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4ALP_AM>BoolSignal" style="position: absolute; top: 225px; left: 1289px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G4ALP_RD,Clinker02_G4ALP_RN,Clinker02_G4ALP_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G10M_AM>BoolSignal" style="position: absolute; top: 476px; left: 969px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G10M_RD,Clinker02_G10M_RN,Clinker02_G10M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G3M_AM>BoolSignal" style="position: absolute; top: 492px; left: 1292px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G3M_RD,Clinker02_G3M_RN,Clinker02_G3M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1M_AM>BoolSignal" style="position: absolute; top: 514px; left: 1435px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G1M_RD,Clinker02_G1M_RN,Clinker02_G1M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN1>BoolSignal" style="position: absolute; top: 161px; left: 1127px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RD,Clinker02_G8AC_RN1',Display='00:lightBlueC,01:redCB,10:yellowC,11:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN2>BoolSignal" style="position: absolute; top: 160px; left: 1165px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RD,Clinker02_G8AC_RN2',Display='00:lightBlueC,01:redCB,10:yellowC,11:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RD>BoolSignal" style="position: absolute; top: 162px; left: 1205px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RD,Clinker02_G8AC_RN3',Display='00:lightBlueC,01:redCB,10:yellowC,11:greenC'"></div>
        
        <%--红色边框--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G5ASR_FT>BoolSignal" style="position: absolute; top: 79px; left: 1130px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_G5ASR_FT',Display='0:NULL,1:redS'"></div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G6ASR_FT>BoolSignal" style="position: absolute; top: 79px; left: 1164px; height: 18px; width: 19px;" data-option="RelatedTags='Clinker02_G6ASR_FT',Display='0:NULL,1:redS'"></div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G7ASR_FT>BoolSignal" style="position: absolute; top: 79px; left: 1209px; height: 16px; width: 19px;" data-option="RelatedTags='Clinker02_G7ASR_FT',Display='0:NULL,1:redS'"></div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_FT>BoolSignal" style="position: absolute; top: 136px; left: 1163px; height: 21px; width: 22px;" data-option="RelatedTags='Clinker02_G8AC_FT',Display='0:NULL,1:redS'"></div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4ALP_FT>BoolSignal" style="position: absolute; top: 214px; left: 1313px; height: 34px; width: 46px;" data-option="RelatedTags='Clinker02_G4ALP_FT',Display='0:NULL,1:redS'"></div>  --%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G2ALC_FT>BoolSignal" style="position: absolute; top: 505px; left: 1386px; height: 20px; width: 26px;" data-option="RelatedTags='Clinker02_G2ALC_FT',Display='1:redS'"></div>--%>
        <%--红色边框--%>

        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G6ASR_AM>BoolSignal" style="position: absolute; top: 79px; left: 1171px; height: 15px; width: 17px; right: 292px;" data-option="RelatedTags='Clinker02_G6ASR_RD,Clinker02_G6ASR_RN,Clinker02_G6ASR_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G5ASR_AM>BoolSignal" style="position: absolute; top: 78px; left: 1131px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G5ASR_RD,Clinker02_G5ASR_RN,Clinker02_G5ASR_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G7ASR_AM>BoolSignal" style="position: absolute; top: 79px; left: 1209px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G7ASR_RD,Clinker02_G7ASR_RN,Clinker02_G7ASR_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_AM>BoolSignal" style="position: absolute; top: 136px; left: 1165px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_G8AC_RD,Clinker02_G8AC_RN,Clinker02_G8AC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_RD>BoolSignal" style="position: absolute; top: 67px; left: 565px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G33AC_RD,Clinker02_G33AC_RN,Clinker02_G33AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_RD>BoolSignal" style="position: absolute; top: 162px; left: 565px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G31AC_RD,Clinker02_G31AC_RN,Clinker02_G31AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_RD>BoolSignal" style="position: absolute; top: 264px; left: 571px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G32AC_RD,Clinker02_G32AC_RN,Clinker02_G32AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_FT>BoolSignal" style="position: absolute; top: 91px; left: 569px; height: 11px; width: 17px;" data-option="RelatedTags='Clinker02_G33AC_FT',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_FT>BoolSignal" style="position: absolute; top: 186px; left: 569px; height: 10px; width: 17px;" data-option="RelatedTags='Clinker02_G31AC_FT',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_FT>BoolSignal" style="position: absolute; top: 290px; left: 575px; height: 9px; width: 17px;" data-option="RelatedTags='Clinker02_G32AC_FT',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC_RD>BoolSignal" style="position: absolute; top: 373px; left: 85px; height: 15px; width: 24px;" data-option="RelatedTags='Clinker02_G36ALC_RD,Clinker02_G36ALC_RN,Clinker02_G36ALC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G15M_RD>BoolSignal" style="position: absolute; top: 662px; left: 60px; height: 16px; width: 67px;" data-option="RelatedTags='Clinker02_G15M_RD,Clinker02_G15M_RN,Clinker02_G15M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G16M_RD>BoolSignal" style="position: absolute; top: 662px; left: 130px; height: 16px; width: 67px;" data-option="RelatedTags='Clinker02_G16M_RD,Clinker02_G16M_RN,Clinker02_G16M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G17M_RD>BoolSignal" style="position: absolute; top: 662px; left: 202px; height: 16px; width: 67px;" data-option="RelatedTags='Clinker02_G17M_RD,Clinker02_G17M_RN,Clinker02_G17M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G18M_RD>BoolSignal" style="position: absolute; top: 662px; left: 275px; height: 16px; width: 67px;" data-option="RelatedTags='Clinker02_G18M_RD,Clinker02_G18M_RN,Clinker02_G18M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G19M_RD>BoolSignal" style="position: absolute; top: 662px; left: 346px; height: 16px; width: 67px;" data-option="RelatedTags='Clinker02_G19M_RD,Clinker02_G19M_RN,Clinker02_G19M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G20M_RD>BoolSignal" style="position: absolute; top: 662px; left: 417px; height: 16px; width: 67px; bottom: 82px;" data-option="RelatedTags='Clinker02_G20M_RD,Clinker02_G20M_RN,Clinker02_G20M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_RD>BoolSignal" style="position: absolute; top: 662px; left: 489px; height: 16px; width: 67px;" data-option="RelatedTags='Clinker02_G21AC_RD,Clinker02_G21AC_RN,Clinker02_G21AC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_RD>BoolSignal" style="position: absolute; top: 662px; left: 563px; height: 16px; width: 29px;" data-option="RelatedTags='Clinker02_G22AC_RD,Clinker02_G22AC_RN,Clinker02_G22AC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G23M_RD>BoolSignal" style="position: absolute; top: 662px; left: 633px; height: 16px; width: 29px;" data-option="RelatedTags='Clinker02_G23M_RD,Clinker02_G23M_RN,Clinker02_G23M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G24M_RD>BoolSignal" style="position: absolute; top: 662px; left: 704px; height: 16px; width: 67px;" data-option="RelatedTags='Clinker02_G24M_RD,Clinker02_G24M_RN,Clinker02_G24M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G25M_RD>BoolSignal" style="position: absolute; top: 662px; left: 774px; height: 17px; width: 67px;" data-option="RelatedTags='Clinker02_G25M_RD,Clinker02_G25M_RN,Clinker02_G25M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_FT>BoolSignal" style="position: absolute; top: 662px; left: 596px; height: 16px; width: 29px;" data-option="RelatedTags='Clinker02_G32AC_FT',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_FT>BoolSignal" style="position: absolute; top: 662px; left: 666px; height: 16px; width: 29px;" data-option="RelatedTags='Clinker02_G32AC_FT',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_1G22AC_FT>BoolSignal" style="position: absolute; top: 618px; left: 565px; height: 9px; width: 17px;" data-option="RelatedTags='Clinker02_G22AC_FT',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_OK>BoolSignal" style="position: absolute; top: 619px; left: 488px; height: 9px; width: 17px;" data-option="RelatedTags='Clinker02_G21AC_OK',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G29AC_RD>BoolSignal" style="position: absolute; top: 639px; left: 895px; height: 16px; width: 32px;" data-option="RelatedTags='Clinker02_G29AC_RD,Clinker02_G29AC_RN,Clinker02_G29AC_AM',Display='000:lightBlueS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G2ALC_AM>BoolSignal" style="position: absolute; top: 509px; left: 1393px; height: 15px; width: 13px;" data-option="RelatedTags='Clinker02_G2ALC_RD,Clinker02_G2ALC_RN,Clinker02_G2ALC_AM',Display='000:lightBlueS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G27ARC_FT1>BoolSignal" style="position: absolute; top: 334px; left: 235px; height: 20px; width: 265px;" data-option="RelatedTags='Clinker02_G27ARC_FT1',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G28ARC_FT1>BoolSignal" style="position: absolute; top: 351px; left: 506px; height: 20px; width: 306px;" data-option="RelatedTags='Clinker02_G28ARC_FT1',Display='1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4ALP_OK>BoolSignal" style="position: absolute; top: 227px; left: 1317px; height: 11px; width: 36px;" data-option="RelatedTags='Clinker02_G4ALP_OK',Display='0:whiteS,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4ALP_RD>BoolSignal" style="position: absolute; top: 212px; left: 1317px; height: 11px; width: 36px;" data-option="RelatedTags='Clinker02_G4ALP_RD',Display='0:whiteS,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ13_LM>BoolSignal" style="position: absolute; top: 214px; left: 1383px; height: 15px; width: 17px;" data-option="RelatedTags='Clinker02_GZZ13_LM',Display='0:NULL,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4M_AM>BoolSignal" style="position: absolute; top: 271px; left: 1386px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_G4M_RD,Clinker02_G4M_RN,Clinker02_G4M_AM',Display='000:lightBlueC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>

        
         <%--汉字隐藏--%>
        <%-- 2个颜色均为透明色--%>
        <%--<div id="zc_nxjc_qtx_efc>Clinker02_G26AC_OK>DCS" class="TextDisplay"data-option="Display='1'"style="position:absolute; top: 482px; left: 838px; font-size:12px; color:yellow;text-align:center; height: 14px; width: 54px;">起动完毕</div>  --%>
        <%-- 2个颜色均为透明色--%>
        <div id="zc_nxjc_qtx_efc>Clinker02_G4ALP_LK>DCS" class="TextDisplay"data-option="Display='1'"style="position:absolute; top: 256px; left: 1311px; font-size:12px; color:yellow;text-align:center; height: 14px; width: 54px;">允许启动</div>  
        <div id="zc_nxjc_qtx_efc>Clinker02_G3M_SS1>DCS" class="TextDisplay"data-option="Display='0'"style="position:absolute; top: 546px; left: 842px; font-size:12px; color:red;text-align:center; height: 14px; width: 54px;">速度报警</div>  
        <%--棒图--%>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_GLT01_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:5px; height:142px; position:absolute; top: 599px; left: 1305px; bottom: 17px;"></div>
    </div>
</body>
</html>
