<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_clinker02_scyt.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_clinker02_scyt" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc_clinker02";
        publicData.sceneName = "2号窑";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style=" width: 1684px; height: 1017px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_clinker02_scyt.png'); width: 1684px; height: 1017px; overflow: hidden; top: 2px; left: 0px;">
   <div id="ConnectionGround" style="width: 1684px; height: 1017px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
    <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1684px;height: 1017px;"></div>   
    <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div> 
     <%--标签粘贴处--%>
        <%--<button onclick="CheckTags()">检查标签</button>--%>
 <%--模拟量--%>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT17_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 86px; left: 550px; position:absolute;color:#4cff00;text-align:right; bottom: 908px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 118px; left: 550px; position:absolute;color:#4cff00;text-align:right; bottom: 876px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 147px; left: 550px; position:absolute;color:#4cff00;text-align:right; bottom: 847px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT12_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 185px; left: 550px; position:absolute;color:#4cff00;text-align:right; bottom: 809px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 214px; left: 550px; position:absolute;color:#4cff00;text-align:right; bottom: 780px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 245px; left: 550px; position:absolute;color:#4cff00;text-align:right; bottom: 749px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT16_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 292px; left: 567px; position:absolute;color:#4cff00;text-align:right; bottom: 702px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 327px; left: 562px; position:absolute;color:#4cff00;text-align:right; bottom: 667px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT13_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 229px; left: 340px; position:absolute;color:#4cff00;text-align:right; bottom: 765px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 349px; left: 661px; position:absolute;color:#4cff00;text-align:right; bottom: 645px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 157px; left: 920px; position:absolute;color:#4cff00;text-align:right; bottom: 837px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ12_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 211px; left: 808px; position:absolute;color:#4cff00;text-align:right; bottom: 783px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ17_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 316px; left: 818px; position:absolute;color:#4cff00;text-align:right; bottom: 678px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ18_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 409px; left: 862px; position:absolute;color:#4cff00;text-align:right; bottom: 585px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 334px; left: 343px; position:absolute;color:blue;text-align:right; bottom: 660px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 160px; left: 1315px; position:absolute;color:#4cff00;text-align:right; bottom: 834px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT14_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 194px; left: 1317px; position:absolute;color:#4cff00;text-align:right; bottom: 800px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ13_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 259px; left: 1398px; position:absolute;color:#4cff00;text-align:right; bottom: 735px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G27ARC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 453px; left: 430px; position:absolute;color:blue;text-align:right; bottom: 541px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G27ARC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 454px; left: 551px; position:absolute;color:blue;text-align:right; bottom: 540px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE04_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 509px; left: 326px; position:absolute;color:blue;text-align:right; bottom: 485px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 531px; left: 326px; position:absolute;color:blue;text-align:right; bottom: 463px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE06_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 509px; left: 415px; position:absolute;color:blue;text-align:right; bottom: 485px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 531px; left: 415px; position:absolute;color:blue;text-align:right; bottom: 461px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G28ARC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 477px; left: 655px; position:absolute;color:blue;text-align:right; bottom: 517px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G28ARC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 477px; left: 772px; position:absolute;color:blue;text-align:right; bottom: 517px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 560px; left: 353px; position:absolute;color:blue;text-align:right; bottom: 434px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 559px; left: 466px; position:absolute;color:blue;text-align:right; bottom: 435px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT03_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 559px; left: 559px; position:absolute;color:blue;text-align:right; bottom: 435px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 559px; left: 641px; position:absolute;color:blue;text-align:right; bottom: 435px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT06_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 559px; left: 725px; position:absolute;color:blue;text-align:right; bottom: 436px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT05_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 559px; left: 807px; position:absolute;color:blue;text-align:right; bottom: 435px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YQFX2_YHL1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 511px; left: 944px; position:absolute;color:#4cff00;text-align:right; bottom: 483px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G26AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 539px; left: 944px; position:absolute;color:#4cff00;text-align:right; bottom: 455px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K77M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 584px; left: 1204px; position:absolute;color:#4cff00;text-align:right; bottom: 410px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K77M_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 615px; left: 1204px; position:absolute;color:#4cff00;text-align:right; bottom: 379px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 641px; left: 1204px; position:absolute;color:#4cff00;text-align:right; bottom: 353px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G3M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 547px; left: 1391px; position:absolute;color:#4cff00;text-align:right; bottom: 447px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 360px; left: 1497px; position:absolute;color:#4cff00;text-align:right; bottom: 634px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1LP_T6_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 430px; left: 1525px; position:absolute;color:#4cff00;text-align:right; bottom: 564px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE13_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 458px; left: 1525px; position:absolute;color:#4cff00;text-align:right; bottom: 536px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GTE14_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 488px; left: 1525px; position:absolute;color:#4cff00;text-align:right; bottom: 506px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GLT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 724px; left: 1537px; position:absolute;color:blue;text-align:right; bottom: 270px;"></div>

    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G16M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:82px; display:block; top: 846px; left: 175px; position:absolute;color:#4cff00;text-align:right; bottom: 148px; right: 1427px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G17M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:77px; display:block; top: 846px; left: 264px; position:absolute;color:#4cff00;text-align:right; bottom: 147px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G18M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 846px; left: 348px; position:absolute;color:#4cff00;text-align:right; bottom: 147px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G19M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 846px; left: 429px; position:absolute;color:#4cff00;text-align:right; bottom: 147px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G20M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:74px; display:block; top: 846px; left: 514px; position:absolute;color:#4cff00;text-align:right; bottom: 148px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 846px; left: 597px; position:absolute;color:#4cff00;text-align:right; bottom: 147px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 846px; left: 685px; position:absolute;color:#4cff00;text-align:right; bottom: 147px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G23M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 846px; left: 769px; position:absolute;color:#4cff00;text-align:right; bottom: 147px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G24M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 847px; left: 857px; position:absolute;color:#4cff00;text-align:right; bottom: 147px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G25M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:80px; display:block; top: 846px; left: 944px; position:absolute;color:#4cff00;text-align:right; bottom: 148px;"></div>
 
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ05_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:80px; display:block; top: 880px; left: 89px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:82px; display:block; top: 880px; left: 175px; position:absolute;color:#4cff00;text-align:right;right: 1427px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ02_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:77px; display:block; top: 880px; left: 264px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ11_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 880px; left: 348px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 880px; left: 429px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ04_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:74px; display:block; top: 880px; left: 514px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ06_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 880px; left: 597px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ07_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 880px; left: 685px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ08_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 880px; left: 769px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ09_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 880px; left: 857px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ10_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:80px; display:block; top: 880px; left: 944px; position:absolute;color:#4cff00;text-align:right;"></div>

    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G15M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:80px; display:block; top: 946px; left: 89px; position:absolute;color:#4cff00;text-align:right; bottom: 48px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G16M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:82px; display:block; top: 946px; left: 175px; position:absolute;color:#4cff00;text-align:right;right: 1427px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G17M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:77px; display:block; top: 946px; left: 264px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G18M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 946px; left: 348px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G19M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 946px; left: 429px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G20M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:74px; display:block; top: 946px; left: 514px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 946px; left: 597px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 946px; left: 685px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G23M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 946px; left: 769px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G24M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 946px; left: 857px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G25M_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:80px; display:block; top: 946px; left: 944px; position:absolute;color:#4cff00;text-align:right;"></div>

    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT11_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:80px; display:block; top: 980px; left: 89px; position:absolute;color:#4cff00;text-align:right; bottom: 14px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT07_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:82px; display:block; top: 980px; left: 175px; position:absolute;color:#4cff00;text-align:right;right: 1427px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT08_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:77px; display:block; top: 980px; left: 264px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT15_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 980px; left: 348px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT09_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:79px; display:block; top: 980px; left: 429px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GPT10_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:74px; display:block; top: 980px; left: 514px; position:absolute;color:#4cff00;text-align:right;"></div>

          
<%--开关量--%>
<%--圆形--%>        
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_AM>BoolSignal" style="position: absolute; top: 122px; left: 672px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G33AC_AM,Clinker02_G33AC_RN,Clinker02_G33AC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_AM>BoolSignal" style="position: absolute; top: 216px; left: 671px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G31AC_AM,Clinker02_G31AC_RN,Clinker02_G31AC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_AM>BoolSignal" style="position: absolute; top: 305px; left: 668px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G32AC_AM,Clinker02_G32AC_RN,Clinker02_G32AC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G15M_AM>BoolSignal" style="position: absolute; top: 505px; left: 84px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G15M_AM,Clinker02_G15M_RN,Clinker02_G15M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G16M_AM>BoolSignal" style="position: absolute; top: 593px; left: 85px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G16M_AM,Clinker02_G16M_RN,Clinker02_G16M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G17M_AM>BoolSignal" style="position: absolute; top: 681px; left: 84px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G17M_AM,Clinker02_G17M_RN,Clinker02_G17M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G18M_AM>BoolSignal" style="position: absolute; top: 766px; left: 84px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G18M_AM,Clinker02_G18M_RN,Clinker02_G18M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G19M_AM>BoolSignal" style="position: absolute; top: 767px; left: 454px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G19M_AM,Clinker02_G19M_RN,Clinker02_G19M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G20M_AM>BoolSignal" style="position: absolute; top: 767px; left: 538px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G20M_AM,Clinker02_G20M_RN,Clinker02_G20M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_AM>BoolSignal" style="position: absolute; top: 767px; left: 624px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G21AC_AM,Clinker02_G21AC_RN,Clinker02_G21AC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_AM>BoolSignal" style="position: absolute; top: 767px; left: 710px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G22AC_AM,Clinker02_G22AC_RN,Clinker02_G22AC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G23M_AM>BoolSignal" style="position: absolute; top: 767px; left: 791px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G23M_AM,Clinker02_G23M_RN,Clinker02_G23M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G24M_AM>BoolSignal" style="position: absolute; top: 767px; left: 880px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G24M_AM,Clinker02_G24M_RN,Clinker02_G24M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G25M_AM>BoolSignal" style="position: absolute; top: 767px; left: 968px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G25M_AM,Clinker02_G25M_RN,Clinker02_G25M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC2_AM>BoolSignal" style="position: absolute; top: 435px; left: 297px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_G36ALC2_AM,Clinker02_G36ALC2_RN,Clinker02_G36ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC1_AM>BoolSignal" style="position: absolute; top: 422px; left: 321px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_G36ALC1_AM,Clinker02_G36ALC1_RN,Clinker02_G36ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC3_AM>BoolSignal" style="position: absolute; top: 458px; left: 291px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_G36ALC3_AM,Clinker02_G36ALC3_RN,Clinker02_G36ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC4_AM>BoolSignal" style="position: absolute; top: 482px; left: 298px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_G36ALC4_AM,Clinker02_G36ALC4_RN,Clinker02_G36ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC5_AM>BoolSignal" style="position: absolute; top: 496px; left: 320px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_G36ALC5_AM,Clinker02_G36ALC5_RN,Clinker02_G36ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F8M_AM>BoolSignal" style="position: absolute; top: 430px; left: 260px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_F8M_AM,Clinker02_F8M_RN,Clinker02_F8M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G26AC_AM>BoolSignal" style="position: absolute; top: 541px; left: 901px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_G26AC_AM,Clinker02_G26AC_RN,Clinker02_G26AC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G10M_AM>BoolSignal" style="position: absolute; top: 561px; left: 1074px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G10M_AM,Clinker02_G10M_RN,Clinker02_G10M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4M_AM>BoolSignal" style="position: absolute; top: 308px; left: 1526px; height: 28px; width: 28px;" data-option="RelatedTags='Clinker02_G4M_AM,Clinker02_G4M_RN,Clinker02_G4M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G1M_AM>BoolSignal" style="position: absolute; top: 543px; left: 1541px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G1M_AM,Clinker02_G1M_RN,Clinker02_G1M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G3M_AM>BoolSignal" style="position: absolute; top: 573px; left: 1427px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G3M_AM,Clinker02_G3M_RN,Clinker02_G3M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4ALP_AM>BoolSignal" style="position: absolute; top: 201px; left: 1501px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G4ALP_AM,Clinker02_G4ALP_RN,Clinker02_G4ALP_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GHSB_RN>BoolSignal" style="position: absolute; top: 48px; left: 69px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_GHSB_RN,Clinker02_GHSB_RD',Display='00:lightBlueC,01:yellowC,10:redCB,11:greenCB'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN1>BoolSignal" style="position: absolute; top: 260px; left: 1110px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G8AC_RD,Clinker02_G8AC_RN1',Display='00:lightBlueC,01:redCB,10:yellowC,11:greenC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN2>BoolSignal" style="position: absolute; top: 260px; left: 1184px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G8AC_RD,Clinker02_G8AC_RN2',Display='00:lightBlueC,01:redCB,10:yellowC,11:greenC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN3>BoolSignal" style="position: absolute; top: 260px; left: 1252px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G8AC_RD,Clinker02_G8AC_RN3',Display='00:lightBlueC,01:redCB,10:yellowC,11:greenC'"></div>  

    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN>BoolSignal" style="position: absolute; top: 352px; left: 1039px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G8AC_RN,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:greenC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RD>BoolSignal" style="position: absolute; top: 409px; left: 1086px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G8AC_RN,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:greenC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN4>BoolSignal" style="position: absolute; top: 459px; left: 1027px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G8AC_RN,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:greenC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_RN5>BoolSignal" style="position: absolute; top: 474px; left: 1075px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_G8AC_RN,Clinker02_G8AC_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:greenC'"></div>  
<%--方形--%>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G27ARC_AM>BoolSignal" style="position: absolute; top:485px; left: 352px; height: 18px; width: 293px; bottom: 514px;" data-option="RelatedTags='Clinker02_G27ARC_AM,Clinker02_G27ARC_RN,Clinker02_G27ARC_RD1',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G28ARC_AM>BoolSignal" style="position: absolute; top:506px; left: 654px; height: 18px; width: 220px; bottom: 493px;" data-option="RelatedTags='Clinker02_G28ARC_AM,Clinker02_G28ARC_RN,Clinker02_G28ARC_RD1',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G36ALC_AM>BoolSignal" style="position: absolute; top:564px; left: 267px; height: 16px; width: 40px; bottom: 437px;" data-option="RelatedTags='Clinker02_G36ALC_AM,Clinker02_G36ALC_RN,Clinker02_G36ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G29AC_AM>BoolSignal" style="position: absolute; top:646px; left: 551px; height: 16px; width: 40px; bottom: 355px;" data-option="RelatedTags='Clinker02_G29AC_AM,Clinker02_G29AC_RN,Clinker02_G29AC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
 

    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G5ASR_AM>BoolSignal" style="position: absolute; top:134px; left: 1111px; height: 16px; width: 31px; bottom: 867px;" data-option="RelatedTags='Clinker02_G5ASR_AM,Clinker02_G5ASR_RN,Clinker02_G5ASR_RD2',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G6ASR_AM>BoolSignal" style="position: absolute; top:135px; left: 1185px; height: 16px; width: 31px; bottom: 866px;" data-option="RelatedTags='Clinker02_G6ASR_AM,Clinker02_G6ASR_RN,Clinker02_G6ASR_RD2',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G7ASR_AM>BoolSignal" style="position: absolute; top:136px; left: 1252px; height: 16px; width: 31px; bottom: 865px;" data-option="RelatedTags='Clinker02_G7ASR_AM,Clinker02_G7ASR_RN,Clinker02_G7ASR_RD2',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G8AC_AM>BoolSignal" style="position: absolute; top:203px; left: 1189px; height: 16px; width: 31px; bottom: 798px;" data-option="RelatedTags='Clinker02_G8AC_AM,Clinker02_G8AC_RN,Clinker02_G8AC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G2ALC_AM>BoolSignal" style="position: absolute; top:597px; left: 1542px; height: 16px; width: 31px; bottom: 404px;" data-option="RelatedTags='Clinker02_G2ALC_AM,Clinker02_G2ALC_RN,Clinker02_G2ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>

    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G33AC_FT>BoolSignal" style="position: absolute; top:147px; left: 669px; height: 16px; width: 31px; bottom: 854px;" data-option="RelatedTags='Clinker02_G33AC_FT',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G31AC_FT>BoolSignal" style="position: absolute; top:240px; left: 668px; height: 16px; width: 31px; bottom: 761px;" data-option="RelatedTags='Clinker02_G31AC_FT',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G32AC_FT>BoolSignal" style="position: absolute; top:330px; left: 666px; height: 16px; width: 31px; bottom: 671px;" data-option="RelatedTags='Clinker02_G32AC_FT',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G21AC_FT>BoolSignal" style="position: absolute; top:810px; left: 662px; height: 31px; width: 16px; bottom: 176px;" data-option="RelatedTags='Clinker02_G21AC_FT',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G22AC_FTZ>BoolSignal" style="position: absolute; top:810px; left: 747px; height: 31px; width: 16px; bottom: 177px;" data-option="RelatedTags='Clinker02_G22AC_FTZ',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G23M_FTZ>BoolSignal" style="position: absolute; top:810px; left: 837px; height: 31px; width: 16px; bottom: 176px;" data-option="RelatedTags='Clinker02_G23M_FTZ',Display='0:NULL,1:redS'"></div>   
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G24M_FTZ>BoolSignal" style="position: absolute; top:810px; left: 923px; height: 31px; width: 16px; bottom: 176px;" data-option="RelatedTags='Clinker02_G24M_FTZ',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G25M_FTZ>BoolSignal" style="position: absolute; top:810px; left: 1010px; height: 31px; width: 16px; bottom: 177px;" data-option="RelatedTags='Clinker02_G25M_FTZ',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4ALP_RD>BoolSignal" style="position: absolute; top:190px; left: 1548px; height: 16px; width: 31px; bottom: 811px;" data-option="RelatedTags='Clinker02_G4ALP_RD',Display='0:whiteS,1:yellowS'"></div>     
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_G4ALP_OK>BoolSignal" style="position: absolute; top:205px; left: 1548px; height: 16px; width: 31px; bottom: 796px;" data-option="RelatedTags='Clinker02_G4ALP_OK',Display='0:whiteS,1:greenS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ13_LM>BoolSignal" style="position: absolute; top:313px; left: 1435px; height: 16px; width: 31px; bottom: 688px;" data-option="RelatedTags='Clinker02_GZZ13_LM',Display='0:yellowS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ05_LM>BoolSignal" style="position: absolute; top:914px; left: 116px; height: 16px; width: 31px; bottom: 87px;" data-option="RelatedTags='Clinker02_GZZ05_LM',Display='0:yellowS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ01_LM>BoolSignal" style="position: absolute; top:914px; left: 204px; height: 16px; width: 31px; bottom: 87px;" data-option="RelatedTags='Clinker02_GZZ01_LM',Display='0:yellowS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ02_LM>BoolSignal" style="position: absolute; top:914px; left: 290px; height: 16px; width: 31px; bottom: 87px;" data-option="RelatedTags='Clinker02_GZZ02_LM',Display='0:yellowS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ11_LM>BoolSignal" style="position: absolute; top:915px; left: 372px; height: 16px; width: 31px; bottom: 86px;" data-option="RelatedTags='Clinker02_GZZ11_LM',Display='0:yellowS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ03_LM>BoolSignal" style="position: absolute; top:915px; left: 455px; height: 16px; width: 31px; bottom: 86px;" data-option="RelatedTags='Clinker02_GZZ03_LM',Display='0:yellowS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ04_LM>BoolSignal" style="position: absolute; top:915px; left: 538px; height: 16px; width: 31px; bottom: 86px;" data-option="RelatedTags='Clinker02_GZZ04_LM',Display='0:yellowS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_GZZ06_LM>BoolSignal" style="position: absolute; top:915px; left: 624px; height: 16px; width: 31px; bottom: 86px;" data-option="RelatedTags='Clinker02_GZZ06_LM',Display='0:yellowS,1:yellowS'"></div>


<%--汉字隐藏--%>
    <div id="zc_nxjc_qtx_efc>Clinker02_G26AC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 591px; left: 896px; color:yellow; text-align: center;right: 742px;">起动完毕</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_G21AC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 984px; left: 610px; color:yellow; text-align: center; height: 12px; right: 1023px; bottom: 20px;">起动完毕</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_G3M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 727px; left: 1078px; color:red; text-align: center; height: 12px; right: 557px; bottom: 278px;">速度报警</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_G4ALP_LK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 234px; left: 1537px; color:yellow; text-align: center; height: 12px; right: 94px; bottom: 771px;">允许启动</div>
   <%--棒图--%>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_GLT01_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:12px; height:97px; position:absolute; top: 724px; left: 1520px;"></div>
             </div>
</body>
</html>
