<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_clinker02_ylfm.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_clinker02_ylfm" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc_clinker02";
        publicData.sceneName = "2号窑";
    </script>
</head>
<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style=" width: 1684px; height: 994px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_clinker02_ylfm.png'); width: 1684px; height: 994px; overflow: hidden; top: 0px; left: -1px;">
   <div id="ConnectionGround" style="width: 1684px; height: 994px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
   <div id="TextGround"style="font-size:large;padding-left:140px;padding-bottom:200px;padding-right:500px;padding-top:38px;width:1684px;height: 994px;"></div>   
    <div id="Picture"style="position: absolute; top: 40px; left: 115px; height: 20px; width: 20px; background-size:100% auto"></div> 
     <%--标签粘贴处--%>
        <%--<button onclick="CheckTags()">检查标签</button>--%>
 <%--模拟量--%>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 150px; left: 29px; position:absolute;color:blue;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT02_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 160px; left: 133px; position:absolute;color:blue;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT04_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 156px; left: 244px; position:absolute;color:blue;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT03_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 158px; left: 359px; position:absolute;color:blue;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE29_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 41px; left: 467px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE31_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 68px; left: 467px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE33_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 96px; left: 467px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE27_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 122px; left: 467px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE30_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 41px; left: 544px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE32_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 71px; left: 544px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE34_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 96px; left: 544px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE28_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 122px; left: 544px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ02_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 33px; left: 699px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 44px; left: 809px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 22px; left: 932px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ05_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 22px; left: 1121px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ06_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 34px; left: 1233px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 91px; left: 789px; position:absolute;color:#4cff00;text-align:right;"></div>
<%--    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 90px; left: 880px; position:absolute;color:#4cff00;text-align:right;"></div>--%>
    <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_BTT03_T_M>DCS'" style="width:66px;display:block; top: 91px; left: 881px; position:absolute;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ04_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 109px; left: 971px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 92px; left: 1062px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE35_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 202px; left: 996px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE36_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 203px; left: 1085px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_CUN_A_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 111px; left: 1272px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 142px; left: 1272px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B4M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 122px; left: 1420px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B10M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 296px; left: 979px; position:absolute;color:#4cff00;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BLT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 310px; left: 1574px; position:absolute;color:blue;text-align:right;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 465px; left: 18px; position:absolute;color:#4cff00;text-align:right;"></div>
<%--    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 464px; left: 137px; position:absolute;color:#4cff00;text-align:right;"></div>--%>
    <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_A7M_ZF_M>DCS'" style="width:66px;display:block; top: 464px; left: 137px; position:absolute;"></div>
    <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_BTT03_T_M>DCS'" style="width:66px;display:block; top: 462px; left: 258px; position:absolute;"></div>
    <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_BTT03_T_M>DCS'" style="width:66px;display:block; top: 462px; left: 381px; position:absolute;"></div>

  <%--  <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 462px; left: 258px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 462px; left: 381px; position:absolute;color:#4cff00;text-align:right;"></div>--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B29AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 445px; left: 532px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 491px; left: 18px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 490px; left: 137px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 491px; left: 258px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 492px; left: 381px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_TOTAL_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 563px; left: 150px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AFEED_TOTF>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 566px; left: 385px; position:absolute;color:#4cff00;text-align:right;"></div>


        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_RAT888>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 609px; left: 138px; position:absolute;color:blue;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AFEED_TOLLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 609px; left: 372px; position:absolute;color:blue;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 580px; left: 827px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 614px; left: 808px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 506px; left: 1083px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 713px; left: 477px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_ZFLJL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 738px; left: 477px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 686px; left: 166px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 686px; left: 246px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 686px; left: 322px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 686px; left: 401px; position:absolute;color:#4cff00;text-align:right;"></div>

<%--        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 723px; left: 166px; position:absolute;color:#4cff00;text-align:right;"></div>--%>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_A4M_ZF_M>DCS'" style="width:66px;display:block; top: 723px; left: 166px; position:absolute;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 723px; left: 246px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 723px; left: 322px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 723px; left: 401px; position:absolute;color:#4cff00;text-align:right;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 759px; left: 166px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 759px; left: 246px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 759px; left: 322px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 759px; left: 401px; position:absolute;color:#4cff00;text-align:right;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 799px; left: 166px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 799px; left: 246px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 799px; left: 322px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 799px; left: 401px; position:absolute;color:#4cff00;text-align:right;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 737px; left: 666px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 764px; left: 666px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 794px; left: 666px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 664px; left: 875px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT03_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 716px; left: 950px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 729px; left: 828px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_SZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 803px; left: 932px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_CZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 831px; left: 932px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BFT01_LW_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 862px; left: 932px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 911px; left: 960px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 943px; left: 681px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 952px; left: 940px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 878px; left: 168px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 907px; left: 168px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP03_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 933px; left: 168px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 959px; left: 168px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE15_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 598px; left: 1197px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE16_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 634px; left: 1197px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE18_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 669px; left: 1197px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE19_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 599px; left: 1349px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE17_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 634px; left: 1349px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE20_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 669px; left: 1349px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 632px; left: 1574px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 667px; left: 1574px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_VOT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 702px; left: 1574px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE09_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 710px; left: 1192px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE11_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 736px; left: 1192px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE13_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 763px; left: 1192px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 790px; left: 1192px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE10_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 709px; left: 1267px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE12_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 739px; left: 1267px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE14_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 764px; left: 1267px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE08_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 790px; left: 1267px; position:absolute;color:#4cff00;text-align:right;"></div>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_SZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 879px; left: 1419px; position:absolute;color:#4cff00;text-align:right;"></div>--%>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_CZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 906px; left: 1419px; position:absolute;color:#4cff00;text-align:right;"></div>--%>
       <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_B49M_CZD_M>DCS'" style="width:66px;display:block; top: 906px; left: 1419px; position:absolute;"></div>
       <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_B49M_CZD_M>DCS'" style="width:66px;display:block; top: 879px; left: 1419px; position:absolute;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BFT03_LW_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 937px; left: 1195px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT09_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 936px; left: 1321px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B21M_TIME>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:66px; display:block; top: 970px; left: 1221px; position:absolute;color:#4cff00;text-align:right;"></div>

      <%--开关量--%>
<%--圆形--%>        
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_AM>BoolSignal" style="position: absolute; top: 432px; left: 98px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A4M_AM,Clinker02_A4M_RN,Clinker02_A4M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div> 
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_AM>BoolSignal" style="position: absolute; top: 432px; left: 216px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A7M_AM,Clinker02_A7M_RN,Clinker02_A7M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_AM>BoolSignal" style="position: absolute; top: 432px; left: 458px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A6M_AM,Clinker02_A6M_RN,Clinker02_A6M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A2M_AM>BoolSignal" style="position: absolute; top: 316px; left: 557px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A2M_AM,Clinker02_A2M_RN,Clinker02_A2M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_AM>BoolSignal" style="position: absolute; top: 432px; left: 339px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A5M_AM,Clinker02_A5M_RN,Clinker02_A5M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A3M_AM>BoolSignal" style="position: absolute; top: 524px; left: 511px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A3M_AM,Clinker02_A3M_RN,Clinker02_A3M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B46M_AM>BoolSignal" style="position: absolute; top: 476px; left: 581px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B46M_AM,Clinker02_B46M_RN,Clinker02_B46M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B11M_AM>BoolSignal" style="position: absolute; top: 490px; left: 642px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B11M_AM,Clinker02_B11M_RN,Clinker02_B11M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B55M_AM>BoolSignal" style="position: absolute; top: 525px; left: 742px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B55M_AM,Clinker02_B55M_RN,Clinker02_B55M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_AM>BoolSignal" style="position: absolute; top: 673px; left: 524px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A8M_AM,Clinker02_A8M_RN,Clinker02_A8M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_AM>BoolSignal" style="position: absolute; top: 904px; left: 414px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B49ALC1_AM,Clinker02_B49ALC1_RN1,Clinker02_B49ALC1_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_RN2>BoolSignal" style="position: absolute; top: 903px; left: 447px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B49ALC1_AM,Clinker02_B49ALC1_RN2,Clinker02_B49ALC1_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_RN3>BoolSignal" style="position: absolute; top: 928px; left: 414px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B49ALC1_AM,Clinker02_B49ALC1_RN3,Clinker02_B49ALC1_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_RN4>BoolSignal" style="position: absolute; top: 928px; left: 447px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B49ALC1_AM,Clinker02_B49ALC1_RN4,Clinker02_B49ALC1_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC2_AM>BoolSignal" style="position: absolute; top: 922px; left: 501px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B49ALC2_AM,Clinker02_B49ALC2_RN1,Clinker02_B49ALC2_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC2_RN2>BoolSignal" style="position: absolute; top: 922px; left: 526px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B49ALC2_AM,Clinker02_B49ALC2_RN2,Clinker02_B49ALC2_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B47M_AM>BoolSignal" style="position: absolute; top: 818px; left: 628px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B47M_AM,Clinker02_B47M_RN,Clinker02_B47M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALP_AM>BoolSignal" style="position: absolute; top: 941px; left: 650px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B49ALP_AM,Clinker02_B49ALP_RN1,Clinker02_B49ALP_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B54M_AM>BoolSignal" style="position: absolute; top: 580px; left: 736px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B54M_AM,Clinker02_B54M_RN,Clinker02_B54M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B11M_RN>BoolSignal" style="position: absolute; top: 491px; left: 874px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B11M_AM,Clinker02_B11M_RN,Clinker02_B11M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B42M_AM>BoolSignal" style="position: absolute; top: 297px; left: 685px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B42M_AM,Clinker02_B42M_RN,Clinker02_B42M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B43M_AM>BoolSignal" style="position: absolute; top: 299px; left: 753px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B43M_AM,Clinker02_B43M_RN,Clinker02_B43M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B43M_RD>BoolSignal" style="position: absolute; top: 297px; left: 826px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B44M_AM,Clinker02_B44M_RN,Clinker02_B44M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B45M_AM>BoolSignal" style="position: absolute; top: 299px; left: 896px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B45M_AM,Clinker02_B45M_RN,Clinker02_B45M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B12ALC_AM>BoolSignal" style="position: absolute; top: 323px; left: 922px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B12ALC_AM,Clinker02_B12ALC_RN,Clinker02_B12ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B10M_AM>BoolSignal" style="position: absolute; top: 324px; left: 996px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B10M_AM,Clinker02_B10M_RN,Clinker02_B10M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B7ALC_AM>BoolSignal" style="position: absolute; top: 272px; left: 1123px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B7ALC_AM,Clinker02_B7ALC_RN,Clinker02_B7ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ALP_AM>BoolSignal" style="position: absolute; top: 119px; left: 1165px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B52ALP_AM,Clinker02_B52ALP_RN1,Clinker02_B52ALP_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B51ALC_AM>BoolSignal" style="position: absolute; top: 209px; left: 1193px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B51ALC_AM,Clinker02_B51ALC_RN1,Clinker02_B51ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B51ALC_RN2>BoolSignal" style="position: absolute; top: 209px; left: 1221px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B51ALC_AM,Clinker02_B51ALC_RN2,Clinker02_B51ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B6ALC_AM>BoolSignal" style="position: absolute; top: 269px; left: 1317px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B6ALC_AM,Clinker02_B6ALC_RN,Clinker02_B6ALC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B4M_AM>BoolSignal" style="position: absolute; top: 123px; left: 1386px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B4M_AM,Clinker02_B4M_RN,Clinker02_B4M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B2M_AM>BoolSignal" style="position: absolute; top: 113px; left: 1577px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B2M_AM,Clinker02_B2M_RN,Clinker02_B2M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B3M_AM>BoolSignal" style="position: absolute; top: 233px; left: 1431px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B3M_AM,Clinker02_B3M_AM,Clinker02_B3M_RN,Clinker02_B3M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B9M_AM>BoolSignal" style="position: absolute; top: 451px; left: 1040px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B9M_AM,Clinker02_B9M_RN,Clinker02_B9M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B8M_AM>BoolSignal" style="position: absolute; top: 459px; left: 1169px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B8M_AM,Clinker02_B8M_RN,Clinker02_B8M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B65M_AM>BoolSignal" style="position: absolute; top: 455px; left: 1339px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B65M_AM,Clinker02_B65M_RN,Clinker02_B65M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_RN>BoolSignal" style="position: absolute; top: 678px; left: 833px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B50M_RN,Clinker02_B50M_RD',Display='00:lightBlueC,01:yellowC,10:greenCB,11:greenC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B61M_AM>BoolSignal" style="position: absolute; top: 892px; left: 1303px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B61M_AM,Clinker02_B61M_RN,Clinker02_B61M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B60M_DR1>BoolSignal" style="position: absolute; top: 911px; left: 310px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B60M_DR1',Display='0:yellowC,1:greenC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BG4_RN1>BoolSignal" style="position: absolute; top: 639px; left: 724px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_BG4_RN1',Display='0:lightBlueC,1:greenC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B5M_RN>BoolSignal" style="position: absolute; top: 157px; left: 1387px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B5M_RN',Display='0:yellowC,1:greenC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48M_AM>BoolSignal" style="position: absolute; top: 897px; left: 650px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B48M_AM,Clinker02_B48M_RN,Clinker02_B48M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>                                
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BHSB_RN>BoolSignal" style="position: absolute; top: 52px; left: 50px; height: 28px; width: 28px;" data-option="RelatedTags='Clinker02_BHSB_RN,Clinker02_BHSB_RD',Display='00:lightBlueC,01:yellowC,10:redCB,11:greenCB'"></div>                                
                         
<%--方形--%>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A1ALC_AM>BoolSignal" style="position: absolute; top:365px; left: 546px; height: 14px; width: 34px; bottom: 615px;" data-option="RelatedTags='Clinker02_A1ALC_AM,Clinker02_A1ALC_RN,Clinker02_A1ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B55ALC_AM>BoolSignal" style="position: absolute; top:495px; left: 684px; height: 19px; width: 34px; bottom: 480px;" data-option="RelatedTags='Clinker02_B55ALC_AM,Clinker02_B55ALC_RN,Clinker02_B55ALC_RD2',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B55ALC_FT>BoolSignal" style="position: absolute; top:513px; left: 682px; height: 13px; width: 39px; bottom: 468px;" data-option="RelatedTags='Clinker02_B55ALC_FT',Display='0:NULL,1:redS''"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B56M_FT>BoolSignal" style="position: absolute; top:493px; left: 741px; height: 19px; width: 34px; bottom: 482px;" data-option="RelatedTags='Clinker02_B56M_FT',Display='0:redS,1:lightBlueS''"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B12ALC_RN>BoolSignal" style="position: absolute; top:357px; left: 916px; height: 19px; width: 34px; bottom: 618px;" data-option="RelatedTags='Clinker02_B12ALC_AM,Clinker02_B12ALC_RN,Clinker02_B12ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B7ALC_RN>BoolSignal" style="position: absolute; top:311px; left: 1113px; height: 19px; width: 34px; bottom: 664px;" data-option="RelatedTags='Clinker02_B7ALC_AM,Clinker02_B7ALC_RN,Clinker02_B7ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B1ALC_RN>BoolSignal" style="position: absolute; top:310px; left: 1307px; height: 19px; width: 34px; bottom: 665px;" data-option="RelatedTags='Clinker02_B6ALC_AM,Clinker02_B6ALC_RN,Clinker02_B6ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>       
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B1ALC_AM>BoolSignal" style="position: absolute; top:166px; left: 1568px; height: 19px; width: 34px; bottom: 809px;" data-option="RelatedTags='Clinker02_B1ALC_AM,Clinker02_B1ALC_RN,Clinker02_B1ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_AM>BoolSignal" style="position: absolute; top:172px; left: 1291px; height: 19px; width: 34px; bottom: 803px;" data-option="RelatedTags='Clinker02_B52ACP_AM,Clinker02_B52ACP_OK,Clinker02_B52ACP_RD1',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ALP_RD>BoolSignal" style="position: absolute; top:123px; left: 1207px; height: 19px; width: 34px; bottom: 852px;" data-option="RelatedTags='Clinker02_B52ALP_RD',Display='0:whiteS,1:yellowS''"></div>
 <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ALP_OK>BoolSignal" style="position: absolute; top:146px; left: 1207px; height: 19px; width: 34px; bottom: 829px;" data-option="RelatedTags='Clinker02_B52ALP_OK',Display='0:whiteS,1:yellowS'"></div>
 <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ02_LM>BoolSignal" style="position: absolute; top:9px; left: 687px; height: 19px; width: 34px; bottom: 966px;" data-option="RelatedTags='Clinker02_BZZ02_LM',Display='0:lightBlueS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ01_LM>BoolSignal" style="position: absolute; top:63px; left: 923px; height: 19px; width: 34px; bottom: 912px;" data-option="RelatedTags='Clinker02_BZZ01_LM',Display='0:lightBlueS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ05_LM>BoolSignal" style="position: absolute; top:62px; left: 1140px; height: 19px; width: 34px; bottom: 913px;" data-option="RelatedTags='Clinker02_BZZ05_LM',Display='0:lightBlueS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ04_LM>BoolSignal" style="position: absolute; top:153px; left: 993px; height: 19px; width: 34px; bottom: 822px;" data-option="RelatedTags='Clinker02_BZZ04_LM',Display='0:lightBlueS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ03_LM>BoolSignal" style="position: absolute; top:551px; left: 1108px; height: 19px; width: 34px; bottom: 424px;" data-option="RelatedTags='Clinker02_B50M_AM',Display='0:lightBlueS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_AM>BoolSignal" style="position: absolute; top:793px; left: 855px; height: 19px; width: 34px; bottom: 182px;" data-option="RelatedTags='Clinker02_B50M_AM,Clinker02_B50M_RN,Clinker02_B50M_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ACP_AM>BoolSignal" style="position: absolute; top:813px; left: 515px; height: 19px; width: 34px; bottom: 162px;" data-option="RelatedTags='Clinker02_B49ACP_AM,Clinker02_B49ACP_OK,Clinker02_B49ACP_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_AM>BoolSignal" style="position: absolute; top:894px; left: 705px; height: 30px; width: 37px; bottom: 70px;" data-option="RelatedTags='Clinker02_B49M_AM,Clinker02_B49M_RN,Clinker02_B49M_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48M2_AM>BoolSignal" style="position: absolute; top:871px; left: 641px; height: 14px; width: 34px; bottom: 109px;" data-option="RelatedTags='Clinker02_B48M2_AM,Clinker02_B48M2_RN,Clinker02_B48M1_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48M1_AM>BoolSignal" style="position: absolute; top:871px; left: 691px; height: 14px; width: 34px; bottom: 109px;" data-option="RelatedTags='Clinker02_B48M1_AM,Clinker02_B48M1_RN,Clinker02_B48M1_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48RE_AM>BoolSignal" style="position: absolute; top:874px; left: 743px; height: 16px; width: 34px; bottom: 104px;" data-option="RelatedTags='Clinker02_B48RE_AM,Clinker02_B48RE_RN,Clinker02_B48RE_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BG42_AM>BoolSignal" style="position: absolute; top:938px; left: 852px; height: 19px; width: 34px; bottom: 37px;" data-option="RelatedTags='Clinker02_BG42_AM,Clinker02_BG4_RN,Clinker02_BG4_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALP_RD>BoolSignal" style="position: absolute; top:919px; left: 598px; height: 19px; width: 34px; bottom: 56px;" data-option="RelatedTags='Clinker02_B49ALP_RD',Display='0:whiteS,1:yellowS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALP_OK>BoolSignal" style="position: absolute; top:940px; left: 598px; height: 19px; width: 34px; bottom: 35px;" data-option="RelatedTags='Clinker02_B49ALP_OK',Display='0:whiteS,1:greenS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_LALM>BoolSignal" style="position: absolute; top:830px; left: 182px; height: 19px; width: 34px; bottom: 145px;" data-option="RelatedTags='Clinker02_A4M_LALM',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_LALM>BoolSignal" style="position: absolute; top:830px; left: 259px; height: 19px; width: 34px; bottom: 144px;" data-option="RelatedTags='Clinker02_A7M_LALM',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_LALM>BoolSignal" style="position: absolute; top:830px; left: 339px; height: 19px; width: 34px; bottom: 147px;" data-option="RelatedTags='Clinker02_A5M_LALM',Display='0:NULL,1:redS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_LALM>BoolSignal" style="position: absolute; top:830px; left: 417px; height: 19px; width: 34px; bottom: 146px;" data-option="RelatedTags='Clinker02_A6M_LALM',Display='0:NULL,1:redS'"></div>
        
<%--汉字隐藏--%>
    <div id="zc_nxjc_qtx_efc>Clinker02_B22M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 165px; left: 508px; color:red; text-align: center; height: 15px;">袋收尘1#星型下料器故障</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B24M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 183px; left: 508px; color:red; text-align: center; height: 15px;">袋收尘1#拉链机器故障</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B23M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 201px; left: 508px; color:red; text-align: center; height: 15px;">袋收尘2#星型下料器故障</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B25M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 217px; left: 508px; color:red; text-align: center; height: 15px; bottom: 762px;">袋收尘2#拉链机器故障</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 531px; left: 95px; color:red; text-align: center; height: 15px;">速度报警</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 531px; left: 249px; color:red; text-align: center; height: 15px;">二度跑偏</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 531px; left: 345px; color:red; text-align: center; height: 15px;">一度跑偏</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B55M_ES1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 553px; left: 663px; color:red; text-align: center; height: 15px;">三度跑偏</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B55M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 649px; left: 585px; color:red; text-align: center; height: 56px; width: 15px;">速度报警</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_QCX_RN2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 653px; left: 20px; color:#4cff00; text-align: center; height: 74px; width: 11px;">Q C X运行</div>
<%--    <div id="zc_nxjc_qtx_efc>Clinker02_QCX_SEL>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 653px; left: 33px; color:yellow; text-align: center; height: 74px;width: 11px;">人工配料</div>--%>
    <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_QCX_SEL>DCS'" style="display:block; top: 654px; left: 48px; position:absolute;color:yellow; text-align: center; height: 68px; width: 11px;font-size:12px;">Q C X配料</div>

    <div id="zc_nxjc_qtx_efc>Clinker02_B49ACP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 838px; left: 512px; color:yellow; text-align: center; height: 15px;">允许进相</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_LK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 952px; left: 423px; color:yellow; text-align: center; height: 15px;">允许启动</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B49ALC2_LK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 959px; left: 504px; color:yellow; text-align: center; height: 15px;">允许启动</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B49ALP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 964px; left: 592px; color:yellow; text-align: center; height: 15px;">允许启动</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_YB1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 975px; left: 410px; color:red; text-align: center; height: 15px;">减速机油站预报警</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B48M1_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 855px; left: 658px; color:yellow; text-align: center; height: 15px;">分</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B48M1_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 855px; left: 694px; color:yellow; text-align: center; height: 15px;">合</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 82px; left: 1368px; color:#4cff00; text-align: center; height: 15px;">变频器允许运行</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 82px; left: 1368px; color:red; text-align: center; height: 15px;">变频器轻故障</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_RN1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 175px; left: 1342px; color:#4cff00; text-align: center; height: 15px;">启动中</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B52ALP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 175px; left: 1200px; color:yellow; text-align: center; height: 15px;">允许启动</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B51ALC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 254px; left: 1194px; color:yellow; text-align: center; height: 15px;">允许启动</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B4M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 12px; top: 214px; left: 1387px; color:red; text-align: center; height: 52px; width: 17px;">速度报警</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B10M_LVS>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 528px; left: 981px; color:red; text-align: center; height: 15px;">料位报警</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_B4M_LVS>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 530px; left: 1379px; color:red; text-align: center; height: 15px;">料位报警</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_BG4_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 842px; left: 1088px; color:red; text-align: center; height: 15px;">立磨故障跳停</div>
    <div id="zc_nxjc_qtx_efc>Clinker02_BG4_FT2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 860px; left: 1089px; color:red; text-align: center; height: 15px;">立磨综合报警</div>
   <%--棒图--%>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT01_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:10px;height:117px; position:absolute; top: 194px; left: 54px;"></div>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT02_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:10px;height:117px; position:absolute; top: 196px; left: 173px;"></div>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT04_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:10px;height:117px; position:absolute; top: 196px; left: 289px;"></div>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT03_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:10px;height:117px; position:absolute; top: 197px; left: 406px;"></div>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_BLT01_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:13px; height:250px; position:absolute; top: 299px; left: 1559px;"></div>
<%--箭头--%>
         <div class="BoolSignal mchart"id="zc_nxjc_qtx_efc>Clinker02_B54M_RN>BoolSigna" style="position: absolute; top:610px; left: 766px; height: 32px; width: 12px;" data-option="RelatedTags='Clinker02_B54M_RN',Display='1:NULL,0:arrowYellowDown'"></div>
         <div class="BoolSignal mchart"id="zc_nxjc_qtx_efc>Clinker02_B54M_RN1>BoolSigna" style="position: absolute; top:606px; left: 799px; height: 48px; width: 12px;" data-option="RelatedTags='Clinker02_B54M_RN',Display='1:NULL,0:arrowYellowDown'"></div>
             </div>
</body>
</html>
