<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_clinker02_mfzbxt.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_clinker02_mfzbxt" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>

    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc_clinker02";
        publicData.sceneName = "煤粉制备系统";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
 <div id="ForeGround" style=" width: 1682px; height: 1012px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>

   <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_clinker02_mfzbxt.png'); width: 1682px; height: 1012px; overflow: hidden; top: 0px; left: 0px;">
    <div id="ConnectionGround" style="width: 1682px; height: 1012px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
  <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1682px;height: 1012px;"></div>   
    <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div> 
        <%--标签粘贴处--%>
        <%--<button onclick="CheckTags()">检查标签</button>--%>

               <%--开关量--%>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KHSB_RN>BoolSignal" style="position: absolute; top: 22px; left: 33px; height: 47px; width: 47px;" data-option="RelatedTags='Clinker02_KHSB_RN,Clinker02_KHSB_RD',Display='00:lightblueC,01:yellowC,10:redCB,11:greenCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2M_AM>BoolSignal" style="position: absolute; top: 119px; left: 169px; height: 35px; width: 35px;" data-option="RelatedTags='Clinker02_K2M_AM,Clinker02_K2M_RN,Clinker02_K2M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2ALP_AM>BoolSignal" style="position: absolute; top: 202px; left: 224px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_K2ALP_AM,Clinker02_K2ALP_RN,Clinker02_K2ALP_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K4M_AM>BoolSignal" style="position: absolute; top: 265px; left: 248px; height: 30px; width: 30px;" data-option="RelatedTags='Clinker02_K4M_AM,Clinker02_K4M_RN,Clinker02_K4M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K9M_AM>BoolSignal" style="position: absolute; top: 306px; left: 685px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K9M_AM,Clinker02_K9M_RN,Clinker02_K9M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K10M_AM>BoolSignal" style="position: absolute; top: 360px; left: 741px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K10M_AM,Clinker02_K10M_RN,Clinker02_K10M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K23M_AM>BoolSignal" style="position: absolute; top: 94px; left: 1012px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K23M_AM,Clinker02_K23M_RN,Clinker02_K23M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K26M_AM>BoolSignal" style="position: absolute; top: 157px; left: 983px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_K26M_AM,Clinker02_K26M_RN,Clinker02_K26M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_S3M_AM>BoolSignal" style="position: absolute; top: 73px; left: 1340px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_S3M_AM,Clinker02_S3M_RN,Clinker02_S3M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K29M_AM>BoolSignal" style="position: absolute; top: 262px; left: 1414px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K29M_AM,Clinker02_K29M_RN,Clinker02_K29M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K21AC_AM>BoolSignal" style="position: absolute; top: 507px; left: 1082px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K21AC_AM,Clinker02_K21AC_RN,Clinker02_K21AC_RD1',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K50M_RN>BoolSignal" style="position: absolute; top: 613px; left: 1095px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_K50M_RN,Clinker02_K50M_RD',Display='00:lightblueC,01:yellowC,10:greenCB,11:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_AM>BoolSignal" style="position: absolute; top: 776px; left: 938px; height: 30px; width: 30px;" data-option="RelatedTags='Clinker02_K18M_AM,Clinker02_K18M_RN,Clinker02_K18M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KG2_RN3>BoolSignal" style="position: absolute; top: 789px; left: 1153px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_KG2_RN3,Clinker02_KG2_RD',Display='00:lightblueC,01:yellowC,10:greenCB,11:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K17AC_AM>BoolSignal" style="position: absolute; top: 739px; left: 1316px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K17AC_AM,Clinker02_K17AC_RN,Clinker02_K17AC_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B18M_AM>BoolSignal" style="position: absolute; top: 867px; left: 1574px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_B18M_AM,Clinker02_B18M_RN,Clinker02_B18M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K14M_AM>BoolSignal" style="position: absolute; top: 891px; left: 246px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K14M_AM,Clinker02_K14M_RN,Clinker02_K14M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K15M_AM>BoolSignal" style="position: absolute; top: 891px; left: 366px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K15M_AM,Clinker02_K15M_RN,Clinker02_K15M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K16M_AM>BoolSignal" style="position: absolute; top: 891px; left: 491px; height: 22px; width: 22px;" data-option="RelatedTags='Clinker02_K16M_AM,Clinker02_K16M_RN,Clinker02_K16M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K28M_AM>BoolSignal" style="position: absolute; top: 149px; left: 1229px; height: 27px; width: 27px;" data-option="RelatedTags='Clinker02_K28M_AM,Clinker02_K28M_RN,Clinker02_K28M_RD',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>

        <%--方形--%>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2RE_AM>BoolSignal" style="position: absolute; top: 119px; left: 130px; height: 12px; width: 29px;" data-option="RelatedTags='Clinker02_K2RE_AM,Clinker02_K2RE_RN,Clinker02_K2RE_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K7M_AM>BoolSignal" style="position: absolute; top: 390px; left: 413px; height: 13px; width: 27px;" data-option="RelatedTags='Clinker02_K7M_AM,Clinker02_K7M_RN,Clinker02_K7M_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KZZ02_LM>BoolSignal" style="position: absolute; top: 134px; left: 249px; height: 15px; width: 33px;" data-option="RelatedTags='Clinker02_KZZ02_LM',Display='0:yellowS,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2ALP_RD>BoolSignal" style="position: absolute; top: 186px; left: 177px; height: 12px; width: 29px;" data-option="RelatedTags='Clinker02_K2ALP_RD',Display='0:NULL,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2ALP_OK>BoolSignal" style="position: absolute; top: 211px; left: 177px; height: 12px; width: 29px;" data-option="RelatedTags='Clinker02_K2ALP_OK',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2ALP_FT>BoolSignal" style="position: absolute; top: 178px; left: 162px; height: 53px; width: 60px;" data-option="RelatedTags='Clinker02_K2ALP_FT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K1ALC_AM>BoolSignal" style="position: absolute; top: 98px; left: 552px; height: 19px; width: 41px;" data-option="RelatedTags='Clinker02_K1ALC_AM,Clinker02_K1ALC_RN,Clinker02_K1ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K1ALC_FT>BoolSignal" style="position: absolute; top: 96px; left: 550px; height: 24px; width: 46px;" data-option="RelatedTags='Clinker02_K1ALC_FT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K52YV_AM>BoolSignal" style="position: absolute; top: 152px; left: 827px; height: 35px; width: 15px;" data-option="RelatedTags='Clinker02_K52YV_AM,Clinker02_K52YV_RN,Clinker02_K52YV_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K25ALC_FT>BoolSignal" style="position: absolute; top: 82px; left: 1059px; height: 13px; width: 27px;" data-option="RelatedTags='Clinker02_K25ALC_FT',Display='0:redS,1:lightblueS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K24ALC_AM>BoolSignal" style="position: absolute; top: 78px; left: 1110px; height: 25px; width: 41px;" data-option="RelatedTags='Clinker02_K24ALC_AM,Clinker02_K24ALC_RN,Clinker02_K24ALC_RD2',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K24ALC_FT>BoolSignal" style="position: absolute; top: 88px; left: 1117px; height: 13px; width: 27px;" data-option="RelatedTags='Clinker02_K24ALC_FT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K39ALC2_AM>BoolSignal" style="position: absolute; top: 83px; left: 1607px; height: 16px; width: 27px;" data-option="RelatedTags='Clinker02_K39ALC2_AM,Clinker02_K39ALC2_RN,Clinker02_K39ALC2_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K39ALC2_FT>BoolSignal" style="position: absolute; top: 80px; left: 1605px; height: 23px; width: 33px;" data-option="RelatedTags='Clinker02_K39ALC2_FT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K3ALC_AM>BoolSignal" style="position: absolute; top: 330px; left: 256px; height: 14px; width: 25px;" data-option="RelatedTags='Clinker02_K3ALC_AM,Clinker02_K3ALC_RN,Clinker02_K3ALC_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K3ALC_FT>BoolSignal" style="position: absolute; top: 328px; left: 253px; height: 18px; width: 32px;" data-option="RelatedTags='Clinker02_K3ALC_FT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K5M_AM>BoolSignal" style="position: absolute; top: 339px; left: 358px; height: 13px; width: 27px;" data-option="RelatedTags='Clinker02_K5M_AM,Clinker02_K5M_RN,Clinker02_K5M_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K6M_AM>BoolSignal" style="position: absolute; top: 393px; left: 668px; height: 13px; width: 27px;" data-option="RelatedTags='Clinker02_K6M_AM,Clinker02_K6M_RN,Clinker02_K6M_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K8M_AM>BoolSignal" style="position: absolute; top: 418px; left: 704px; height: 13px; width: 27px;" data-option="RelatedTags='Clinker02_K8M_AM,Clinker02_K8M_RN,Clinker02_K8M_RD',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K12AC_AM1>BoolSignal" style="position: absolute; top: 745px; left: 248px; height: 17px; width: 32px;" data-option="RelatedTags='Clinker02_K12AC_AM1,Clinker02_K12AC_RN,Clinker02_K12AC_LK',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K11AC_AM1>BoolSignal" style="position: absolute; top: 748px; left: 478px; height: 17px; width: 32px;" data-option="RelatedTags='Clinker02_K11AC_AM1,Clinker02_K11AC_RN,Clinker02_K11AC_LK',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K14M_ZFT>BoolSignal" style="position: absolute; top: 913px; left: 245px; height: 13px; width: 25px;" data-option="RelatedTags='Clinker02_K14M_ZFT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K16M_ZFT>BoolSignal" style="position: absolute; top: 913px; left: 490px; height: 13px; width: 25px;" data-option="RelatedTags='Clinker02_K16M_ZFT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K50M_AM>BoolSignal" style="position: absolute; top: 708px; left: 1089px; height: 16px; width: 25px;" data-option="RelatedTags='Clinker02_K50M_AM,Clinker02_K50M_RN1,Clinker02_K50M_RD',Display=''000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K50M_FT>BoolSignal" style="position: absolute; top: 708px; left: 1088px; height: 17px; width: 27px;" data-option="RelatedTags='Clinker02_K50M_FT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K17AC_FT>BoolSignal" style="position: absolute; top: 763px; left: 1317px; height: 11px; width: 22px;" data-option="RelatedTags='Clinker02_K17AC_FT',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K9M_SEL>BoolSignal" style="position: absolute; top: 309px; left: 400px; height: 15px; width: 43px;" data-option="RelatedTags='Clinker02_K9M_SEL',Display='0:NULL,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K9M_SEL1>BoolSignal" style="position: absolute; top: 309px; left: 608px; height: 15px; width: 43px;" data-option="RelatedTags='Clinker02_K9M_SEL',Display='0:yellowS,1:NULL'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K9M_SEL2>BoolSignal" style="position: absolute; top: 363px; left: 456px; height: 15px; width: 43px;" data-option="RelatedTags='Clinker02_K9M_SEL',Display='0:NULL,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K9M_SEL3>BoolSignal" style="position: absolute; top: 361px; left: 657px; height: 15px; width: 43px;" data-option="RelatedTags='Clinker02_K9M_SEL',Display='0:yellowS,1:NULL'"></div>
<div class="BoolSignal mchart"id="zc_nxjc_qtx_efc>Clinker02_K26M_LMF>BoolSignal" style="position: absolute; top:169px; left: 1042px; height: 44px; width: 12px;" data-option="RelatedTags='Clinker02_K26M_LMF',Display='0:NULL,1:arrowyellowDownS'"></div>
<div class="BoolSignal mchart"id="zc_nxjc_qtx_efc>Clinker02_K26M_LMR>BoolSignal" style="position: absolute; top:185px; left: 1006px; height: 44px; width: 12px;" data-option="RelatedTags='Clinker02_K26M_LMR',Display='0:NULL,1:arrowyellowDownS'"></div>

        <%--模拟量--%>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KHSB_TIME>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 77px; left: 33px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 93px; left: 243px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 178px; left: 54px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K2M_V_01M_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 227px; left: 34px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTT10_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 115px; left: 334px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 74px; display: block; top: 150px; left: 304px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KA01_A_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 182px; left: 334px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE04_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 203px; left: 422px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE06_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 203px; left: 499px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE08_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 203px; left: 578px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 229px; left: 476px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 229px; left: 555px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE09_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 229px; left: 635px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KWT01_W_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 259px; left: 870px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 99px; left: 687px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K23M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 66px; left: 982px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE25_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 324px; left: 88px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE26_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 324px; left: 158px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE27_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 351px; left: 88px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE28_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 351px; left: 158px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE29_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 379px; left: 88px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE30_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 379px; left: 158px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE31_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 405px; left: 88px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE32_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 405px; left: 158px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE71_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 433px; left: 98px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE72_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 433px; left: 160px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KA02_A_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 482px; left: 173px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE11_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 555px; left: 196px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KWT02_W_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 476px; left: 476px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE12_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 559px; left: 470px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE13_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 465px; left: 282px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE14_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 493px; left: 282px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K12AC_LOAD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 703px; left: 121px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K12AC_ZS_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 734px; left: 121px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K12AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 766px; left: 93px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K12AC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 73px; display: block; top: 804px; left: 93px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KPT05_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 855px; left: 257px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K14M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 942px; left: 231px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K14M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 969px; left: 231px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KPT06_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 852px; left: 370px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K15M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 935px; left: 348px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KPT07_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 853px; left: 506px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K16M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 934px; left: 480px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_FZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 970px; left: 478px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K11AC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 73px; display: block; top: 802px; left: 591px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K11AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 769px; left: 604px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K11AC_ZS_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 738px; left: 605px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K11AC_LOAD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 705px; left: 606px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KPT02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 68px; display: block; top: 550px; left: 767px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 550px; left: 884px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K21AC_FF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 494px; left: 1122px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K21AC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 74px; display: block; top: 521px; left: 1129px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE50M_T_M1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 51px; display: block; top: 558px; left: 1158px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE50M_T_M2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 51px; display: block; top: 580px; left: 1158px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KPT12_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 51px; display: block; top: 609px; left: 1159px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K50M_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 51px; display: block; top: 660px; left: 1055px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KZZ02_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 651px; left: 1393px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 783px; left: 843px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_TIME>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 83px; display: block; top: 828px; left: 842px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 699px; left: 1364px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K17M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 710px; left: 1293px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 723px; left: 1198px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KPT01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 52px; display: block; top: 760px; left: 1197px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ09_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 716px; left: 1585px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 762px; left: 1477px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE17_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 628px; left: 800px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE20_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 628px; left: 871px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE18_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 655px; left: 800px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE21_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 655px; left: 871px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE19_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 684px; left: 800px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE22_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 684px; left: 871px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE23_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 711px; left: 835px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_KTE24_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 737px; left: 835px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE_YWZX_SO2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 891px; left: 834px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE_YWZX_NOX>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 935px; left: 834px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_SSL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 975px; left: 834px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE_YWZX_O2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 891px; left: 1100px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE_YWZX_KLW>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 935px; left: 1100px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE_YWZX_NOXZS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 975px; left: 1100px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWZX_ABGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 891px; left: 1388px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWZX_NOXFK>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 935px; left: 1388px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWZX_NOXGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 57px; display: block; top: 975px; left: 1388px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>

      <%--汉字隐藏--%>
        <div id="zc_nxjc_qtx_efc>Clinker02_K2ALP_LK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 156px; left: 151px; color: yellow; text-align: center; height: 18px; bottom: 838px; width: 72px;; font-size: 15px">允许起动</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K5M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 339px; left: 312px; color: yellow; text-align: center; height: 16px; bottom: 657px; width: 21px;; font-size: 15px">开</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K5M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 339px; left: 312px; color: yellow; text-align: center; height: 16px; bottom: 657px; width: 21px;; font-size: 15px">关</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K7M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 392px; left: 458px; color: yellow; text-align: center; height: 16px; bottom: 604px; width: 21px;; font-size: 15px">开</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K7M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 392px; left: 458px; color: yellow; text-align: center; height: 16px; bottom: 604px; width: 21px;; font-size: 15px">关</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K6M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 398px; left: 625px; color: yellow; text-align: center; height: 16px; bottom: 598px; width: 21px;; font-size: 15px">开</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K6M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 398px; left: 625px; color: yellow; text-align: center; height: 16px; bottom: 598px; width: 21px;; font-size: 15px">关</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K8M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 422px; left: 749px; color: yellow; text-align: center; height: 16px; bottom: 574px; width: 21px;; font-size: 15px">开</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K8M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 422px; left: 749px; color: yellow; text-align: center; height: 16px; bottom: 574px; width: 21px;; font-size: 15px">关</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K12AC_LM1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 718px; left: 240px; color: yellow; text-align: center; height: 18px; bottom: 276px; width: 49px;; font-size: 15px">滑阀开</div>
        <div class="Conflict" data-option="id='zc_nxjc_qtx_efc>Clinker02_K12AC_LM1>DCS'" style="width: 53px; display: block; top: 718px; left: 240px; position: absolute; color: yellow;text-align: right;right: 1391px; height: 18px; bottom: 276px">滑阀关</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K11AC_LM1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 722px; left: 468px; color: yellow; text-align: center; height: 18px; bottom: 272px; width: 49px;; font-size: 15px">滑阀开</div>
        <div class="Conflict" data-option="id='zc_nxjc_qtx_efc>Clinker02_K11AC_LM1>DCS'" style="width: 53px; display: block; top: 722px; left: 468px; position: absolute; color: yellow;text-align: right;right: 1164px; height: 18px; bottom: 273px">滑阀关</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_KG2_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 745px; left: 1065px; color: yellow; text-align: center; height: 18px; bottom: 249px; width: 72px;; font-size: 15px">允许起动</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K12AC_DR2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 781px; left: 231px; color: yellow; text-align: center; height: 18px; bottom: 213px; width: 43px;; font-size: 15px">中控</div>
        <div class="Conflict" data-option="id='zc_nxjc_qtx_efc>Clinker02_K12AC_DR2>DCS'" style="width: 35px; display: block; top: 781px; left: 231px; position: absolute; color: yellow;text-align: right;right: 1412px; height: 18px; bottom: 213px">机旁</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K11AC_DR2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 781px; left: 482px; color: yellow; text-align: center; height: 18px; bottom: 209px; width: 43px;; font-size: 15px">中控</div>
        <div class="Conflict" data-option="id='zc_nxjc_qtx_efc>Clinker02_K11AC_DR2>DCS'" style="width: 35px; display: block; top: 781px; left: 482px; position: absolute; color: yellow;text-align: right;right: 1162px; height: 18px; bottom: 214px">机旁</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K12AC_AM2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 844px; left: 101px; color: red; text-align: center; height: 18px; bottom: 150px; width: 64px;; font-size: 15px">综合报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K12AC_FT22>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 866px; left: 101px; color: red; text-align: center; height: 18px; bottom: 128px; width: 64px;; font-size: 15px">转子故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K12AC_FT33>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 886px; left: 101px; color: red; text-align: center; height: 18px; bottom: 108px; width: 64px;; font-size: 15px">助流故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K12AC_STP2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 908px; left: 101px; color: red; text-align: center; height: 18px; bottom: 86px; width: 64px;; font-size: 15px">紧急闭锁</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K11AC_AM2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 858px; left: 614px; color: red; text-align: center; height: 18px; bottom: 136px; width: 64px;; font-size: 15px">综合报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K11AC_FT22>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 880px; left: 614px; color: red; text-align: center; height: 18px; bottom: 114px; width: 64px;; font-size: 15px">转子故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K11AC_FT33>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 902px; left: 614px; color: red; text-align: center; height: 18px; bottom: 92px; width: 64px;; font-size: 15px">助流故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K11AC_STP2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 924px; left: 614px; color: red; text-align: center; height: 18px; bottom: 70px; width: 64px;; font-size: 15px">紧急闭锁</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K23M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 118px; left: 1093px; color: red; text-align: center; height: 18px; bottom: 876px; width: 72px;; font-size: 15px">二度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K23M_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 118px; left: 1093px; color: red; text-align: center; height: 18px; bottom: 876px; width: 72px;; font-size: 15px">一度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_S3M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 68px; left: 1397px; color: red; text-align: center; height: 18px; bottom: 926px; width: 72px;; font-size: 15px">二度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_S3M_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 68px; left: 1397px; color: red; text-align: center; height: 18px; bottom: 926px; width: 72px;; font-size: 15px">一度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K29M_ES2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 291px; left: 1326px; color: red; text-align: center; height: 18px; bottom: 703px; width: 72px;; font-size: 15px">二度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K29M_ES1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 291px; left: 1326px; color: red; text-align: center; height: 18px; bottom: 703px; width: 72px;; font-size: 15px">一度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K23M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 109px; left: 1261px; color: red; text-align: center; height: 18px; bottom: 885px; width: 72px;; font-size: 15px">速度报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_S3M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 128px; left: 1499px; color: red; text-align: center; height: 18px; bottom: 866px; width: 72px;; font-size: 15px">速度报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K29M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 317px; left: 1175px; color: red; text-align: center; height: 18px; bottom: 677px; width: 72px;; font-size: 15px">速度报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K39ALC2_AUTO>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 75px; left: 1647px; color: yellow; text-align: center; height: 31px; bottom: 906px; width: 24px;; font-size: 15px">中控</div>
        <div class="Conflict" data-option="id='zc_nxjc_qtx_efc>Clinker02_K39ALC2_AUTO>DCS'" style="width: 17px; display: block; top: 75px; left: 1649px; position: absolute; color: yellow;text-align: right;right: 16px; height: 34px; bottom: 905px">现场</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_K17AC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 688px; left: 1279px; color: yellow; text-align: center; height: 18px; bottom: 306px; width: 72px;; font-size: 15px">起动完毕</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_KG2_FT4>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 787px; left: 1192px; color: red; text-align: center; height: 18px; bottom: 207px; width: 72px;; font-size: 15px">密封故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_KG2_FT3>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 807px; left: 1192px; color: red; text-align: center; height: 18px; bottom: 187px; width: 100px;; font-size: 15px">润滑系统故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_KG2_FT6>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 787px; left: 1312px; color: red; text-align: center; height: 18px; bottom: 207px; width: 82px;; font-size: 15px">三通阀故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_KG2_FT2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 809px; left: 1313px; color: red; text-align: center; height: 18px; bottom: 185px; width: 70px;; font-size: 15px">系统故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_KG2_RN3>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 828px; left: 1193px; color: #4cff00; text-align: center; height: 18px; bottom: 166px; width: 100px;; font-size: 15px">润滑系统运行</div>

          <%--棒图--%>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_KWT02_W_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:9px; height:84px; position:absolute; top: 457px; left: 372px;"></div>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_KWT01_W_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:9px; height:143px; position:absolute; top: 240px; left: 1002px;"></div>

    </div>
</body>
</html>
