<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_cogeneration02_qjxtlct.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_cogeneration02_qjxtlct" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
        
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc_cogeneration02";
        publicData.sceneName = "2号余热发电";
    </script>
  
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style="width: 1547px; height:1016px; margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
<div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_cogeneration02_qjxtlct.png');width: 1547px; height: 1016px;  overflow: hidden; top: 0px; left: 0px;">
     <div id="ConnectionGround" style="width: 1547px; height: 1016px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
   <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1547px;height: 1016px;"></div>   
        <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div> 
     <%--<button onclick="CheckTags()">检查标签</button>--%>
       <%--模拟量--%>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TT09>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 34px; left: 28px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_APT08>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 36px; left: 113px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_STT06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 167px; left: 3px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_SPT04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 167px; left: 89px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT01A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 96px; left: 291px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 135px; left: 290px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TFT01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 100px; left: 491px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TSE03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 103px; left: 612px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TSE01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 129px; left: 612px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_DEH>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 155px; left: 612px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 98px; left: 863px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TZDQ01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 117px; left: 1019px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT02A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 162px; left: 1006px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 136px; left: 1121px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE20A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 126px; left: 1204px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE20B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 125px; left: 1292px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TXE02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 177px; left: 1149px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TZQ01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 169px; left: 1276px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE21>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 145px; left: 1416px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TXE01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 190px; left: 903px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT03A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 222px; left: 1049px; position: absolute; color: blue;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TXE03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 236px; left: 1271px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE18A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 297px; left: 1199px; position: absolute; color: #4cff00;text-align:right"></div>
<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE18B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 295px; left: 1286px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE24>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 289px; left: 1370px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE25>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 290px; left: 1448px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE19A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 340px; left: 1203px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE19B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 341px; left: 1289px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE26>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 341px; left: 1406px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE07B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 362px; left: 937px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE08B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 360px; left: 1065px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_W3M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 391px; left: 1268px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_W4M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 389px; left: 1404px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_W3M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 421px; left: 1268px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_W4M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 420px; left: 1404px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE10>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 466px; left: 960px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE09>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 470px; left: 1101px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLZ01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 447px; left: 102px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_TLZ01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 472px; left: 102px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT08>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 498px; left: 648px; position: absolute; color: #4cff00;text-align:right"></div>           
<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT09>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 525px; left: 996px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_WLT03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 563px; left: 1352px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 571px; left: 11px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 617px; left: 11px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT05>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 603px; left: 213px; position: absolute; color: blue;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TFT03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 679px; left: 11px; position: absolute; color: #4cff00;text-align:right"></div>
<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 615px; left: 643px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 665px; left: 643px; position: absolute; color: #4cff00;text-align:right"></div>
<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE11>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 656px; left: 1000px; position: absolute; color: #4cff00;text-align:right"></div>
<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT01A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 721px; left: 1085px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT05>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 814px; left: 206px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT12A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 842px; left: 73px; position: absolute; color: #4cff00;text-align:right; height: 22px;"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT10A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 874px; left: 73px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT13A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 909px; left: 73px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT11A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 943px; left: 73px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT14A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 979px; left: 73px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE22A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 862px; left: 162px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE22D>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 890px; left: 162px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE22B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 863px; left: 233px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE22E>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 888px; left: 233px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE22C>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 862px; left: 303px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE22F>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 888px; left: 303px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE14A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 862px; left: 386px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE14B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 889px; left: 386px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE15A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 861px; left: 474px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE15B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 885px; left: 474px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 950px; left: 165px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 950px; left: 239px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23C>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 950px; left: 306px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE16A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 950px; left: 390px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE17A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 950px; left: 475px; position: absolute; color: #4cff00;text-align:right"></div>

<%--    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 975px; left: 167px; position: absolute; color: #4cff00;text-align:right"></div>--%>
<div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23A>DCS'" style="width:65px; display:block; top: 975px; left: 167px; position:absolute;"></div>
<%--    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 975px; left: 239px; position: absolute; color: #4cff00;text-align:right"></div>--%>
<div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23B>DCS'" style="width:65px; display:block; top: 975px; left: 239px; position:absolute;"></div>
<div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23C>DCS'" style="width:65px; display:block; top: 975px; left: 306px; position:absolute;"></div>
<%--    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE23C>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 975px; left: 306px; position: absolute; color: #4cff00;text-align:right"></div>--%>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE16B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 975px; left: 390px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE17B>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 975px; left: 475px; position: absolute; color: #4cff00;text-align:right"></div>
<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 812px; left: 458px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TFT02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 793px; left: 552px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE05>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 845px; left: 577px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TPT04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 909px; left: 577px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_T21M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 799px; left: 821px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_T21M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 820px; left: 821px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE07A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 811px; left: 923px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_T22M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 932px; left: 821px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_T22M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 953px; left: 821px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TTE08A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 810px; left: 1105px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_W1M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 798px; left: 1270px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_W1M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 822px; left: 1270px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_W2M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 798px; left: 1368px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AO1_W2M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 822px; left: 1368px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TT03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 922px; left: 1124px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_APT03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 922px; left: 1219px; position: absolute; color: #4cff00;text-align:right"></div>

    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_STT01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 922px; left: 1340px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_SPT01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 922px; left: 1448px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TT06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 962px; left: 1123px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_APT04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 962px; left: 1220px; position: absolute; color: #4cff00;text-align:right"></div>
    <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_STT04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 962px; left: 1344px; position: absolute; color: #4cff00;text-align:right"></div>
<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_SPT02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 64px; display: block; top: 960px; left: 1449px; position: absolute; color: #4cff00;text-align:right"></div>
       <%--开关量--%>
     <%--方形--%>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T10YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T10YM,Cogeneration02_DI3_T10YM,Cogeneration02_DI1_T10YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 90px; left: 133px; height: 19px; width: 45px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T12YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T12YM,Cogeneration02_DI3_T12YM,Cogeneration02_DI1_T12YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 59px; left: 109px; height: 36px; width: 19px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T11YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T11YM,Cogeneration02_DI3_T11YM,Cogeneration02_DI1_T11YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 233px; left: 136px; height: 19px; width: 45px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T13YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T13YM,Cogeneration02_DI3_T13YM,Cogeneration02_DI1_T13YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 198px; left: 113px; height: 36px; width: 19px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T15YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T15YM,Cogeneration02_DI3_T15YM,Cogeneration02_DI1_T15YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 71px; left: 244px; height: 36px; width: 19px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T14YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T14YM,Cogeneration02_DI3_T14YM,Cogeneration02_DI1_T14YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 116px; left: 415px; height: 19px; width: 45px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T20YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T20YM,Cogeneration02_DI3_T20YM,Cogeneration02_DI1_T20YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 601px; left: 546px; height: 35px; width: 18px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T16YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T16YM,Cogeneration02_DI3_T16YM,Cogeneration02_DI1_T16YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 657px; left: 946px; height: 36px; width: 17px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_Y9M>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_Y9M,Cogeneration02_DI3_Y9M,Cogeneration02_DI1_Y9M',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 763px; left: 303px; height: 19px; width: 45px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T18YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T18YM,Cogeneration02_DI3_T18YM,Cogeneration02_DI1_T18YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 650px; left: 1147px; height: 39px; width: 17px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T17YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T17YM,Cogeneration02_DI3_T17YM,Cogeneration02_DI1_T17YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 392px; left: 995px; height: 41px; width: 19px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_T19YM>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_T19YM,Cogeneration02_DI3_T19YM,Cogeneration02_DI1_T19YM',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 391px; left: 1098px; height: 41px; width: 19px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_352V02M>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_352V02M,Cogeneration02_DI3_352V02M,Cogeneration02_DI1_352V02M',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 740px; left: 1358px; height: 41px; width: 19px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_DI4_352V01M>BoolSignal" data-option="RelatedTags='Cogeneration02_DI4_352V01M,Cogeneration02_DI3_352V01M,Cogeneration02_DI1_352V01M',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:blueS,101:blueS,110:redS,111:redS'" style="position: absolute; top: 738px; left: 1282px; height: 41px; width: 19px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_W3M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_W3M,Cogeneration02_DI2_W3M,Cogeneration02_DI1_W3M',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'" style="position: absolute; top: 450px; left: 1289px; height: 19px; width: 45px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_W4M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_W4M,Cogeneration02_DI2_W4M,Cogeneration02_DI1_W4M',Display='000:lightBlueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'" style="position: absolute; top: 450px; left: 1419px; height: 19px; width: 45px;"></div>

  <%--圆形--%>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_T7aM>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_T7aM,Cogeneration02_DI2_T7aM,Cogeneration02_DI1_T7aM',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 566px; left: 406px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_T7bM>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_T7bM,Cogeneration02_DI2_T7bM,Cogeneration02_DI1_T7bM',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 616px; left: 406px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_C1M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_C1M,Cogeneration02_DI2_C1M,Cogeneration02_DI1_C1M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 721px; left: 101px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_C2M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_C2M,Cogeneration02_DI2_C2M,Cogeneration02_DI1_C2M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 778px; left: 101px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_W7M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_W7M,Cogeneration02_DI2_W7M,Cogeneration02_DI1_W7M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 738px; left: 390px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_W8M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_W8M,Cogeneration02_DI2_W8M,Cogeneration02_DI1_W8M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 777px; left: 390px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_T8M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_T8M,Cogeneration02_DI2_T8M,Cogeneration02_DI1_T8M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 616px; left: 758px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_T9M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_T9M,Cogeneration02_DI2_T9M,Cogeneration02_DI1_T9M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 615px; left: 820px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_T21M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_T21M,Cogeneration02_DI2_T21M,Cogeneration02_DI1_T21M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 849px; left: 791px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_T22M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_T22M,Cogeneration02_DI2_T22M,Cogeneration02_DI1_T22M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 904px; left: 791px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_W1M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_W1M,Cogeneration02_DI2_W1M,Cogeneration02_DI1_W1M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 708px; left: 1278px; height: 28px; width: 28px;"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cogeneration02_ALM_W2M>BoolSignal" data-option="RelatedTags='Cogeneration02_ALM_W2M,Cogeneration02_DI2_W2M,Cogeneration02_DI1_W2M',Display='000:lightBlueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'" style="position: absolute; top: 709px; left: 1354px; height: 28px; width: 28px;"></div>

   <%--汉字隐藏--%>
        <div id="zc_nxjc_qtx_efc>Cogeneration02_DI19_TK12>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 173px; left: 197px; color: gray;font-size:12px">505控制OK</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI16_TK9>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 187px; left: 197px; color: gray;font-size:12px">505报警</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI15_TK8>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 201px; left: 197px; color: gray;font-size:12px">505跳闸</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI3_K3>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 285px; left: 36px; color: gray;font-size:12px">汽机排气压力高于-0.062MPa</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI8_K8>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 301px; left: 36px; color: gray;font-size:12px">汽机排气压力高于-0.065MPa</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI11_TSL22>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 315px; left: 36px; color: gray;font-size:12px">主汽门速关阀打开行程开关信号</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI2_TXE03>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 330px; left: 36px; color: gray;font-size:12px">发电机后轴承振动超过25um</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI1_TZQ01>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 346px; left: 37px; color: gray;font-size:12px">汽轮机轴向位移超过+-0.6mm</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI7_K7>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 361px; left: 37px; color: gray;font-size:12px">汽机润滑油压低于0.13MPa</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI10_K10>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 285px; left: 217px; color: gray;font-size:12px">汽机高压油压低于0.65MPa启电动油泵</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI5_K5>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 301px; left: 217px; color: gray;font-size:12px">汽机润滑油压低于0.07MPa停机启直流油泵</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI2_K2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 317px; left: 216px; color: gray;font-size:12px">汽机润滑油压低于0.08MPa停机启交流油泵</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI14_TK2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 333px; left: 216px; color: gray;font-size:12px">发电机主保护动作</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI20_TK13>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 347px; left: 216px; color: gray;font-size:12px">超速试验投入</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI13_TK5>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 361px; left: 216px; color: gray;font-size:12px">主汽门速关阀关闭</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI18_TK11>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 347px; left: 372px; color: gray;font-size:12px">远速给定已投</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI12_TK4>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 363px; left: 373px; color: gray;font-size:12px">盘车装置投入</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI1_TLS01B>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 685px; left: 906px; color: gray;font-size:12px">水位高</div>
    <div id="zc_nxjc_qtx_efc>Cogeneration02_DI1_TLS01C>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; top: 726px; left: 910px; color: gray;font-size:12px">水位低</div>

   <%--棒图--%>
    <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT02>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:18px; height:69px; position:absolute; top: 555px; left: 159px;"></div>
    <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT05>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:78px; height:93px; position:absolute; top: 704px; left: 217px;"></div>
    <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT06>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:73px; height:99px; position:absolute; top: 711px; left: 457px;"></div>
    <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT03>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:121px; height:49px; position:absolute; top: 693px; left: 615px;"></div>
    <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_TLT01A>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:85px; height:82px; position:absolute; top: 677px; left: 1006px;"></div>
    <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Cogeneration02_AI1_WLT03>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:251px; height:62px; position:absolute; top: 604px; left: 1226px;"></div>
                                                                                 
    </div>
</body>

</html>
