<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_clinker02_ylfmjfqcl.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_clinker02_ylfmjfqcl" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc_clinker02";
        publicData.sceneName = "2号窑";
    </script>
</head>
<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style="width: 1684px; height:1017px; margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_clinker02_ylfmjfqcl.png'); width: 1684px; height: 1017px; overflow: hidden;">
    <div id="ConnectionGround" style="width: 1684px; height: 1017px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6"></div>
    <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1684px;height: 1017px;"></div>   
    <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div> 
    <%--贴标签处--%>
        <%--<button onclick="CheckTags()">检查标签</button>--%>
    <%--模拟量--%>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ07_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 21px; left: 203px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20M_SZDV_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 133px; left: 6px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20M_SZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 156px; left: 6px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 140px; left: 147px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361SR02T01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 217px; left: 77px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AIVFD361SR02C_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 180px; left: 220px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AIVFD361SR02S_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 212px; left: 219px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AISST361BE01C_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 261px; left: 492px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361SR02P01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 352px; left: 171px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AISST361BE02C_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 389px; left: 308px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_ZFLJL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 442px; left: 382px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 472px; left: 363px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361SR01P01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 549px; left: 100px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361SR01T01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 571px; left: 110px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LD05Z01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 601px; left: 94px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LC01W01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 386px; left: 552px; position:absolute;color:blue;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GLZ_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 501px; left: 472px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HLZ_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 502px; left: 618px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GMC_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 625px; left: 509px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01LX_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 651px; left: 496px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HMC_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 623px; left: 624px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01RX_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 652px; left: 606px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE39_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 15px; left: 386px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE40_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 47px; left: 386px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE41_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 82px; left: 388px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE37_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 118px; left: 388px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE45_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 149px; left: 390px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE42_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 15px; left: 459px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE43_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 47px; left: 461px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE44_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 82px; left: 461px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE38_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 118px; left: 462px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE46_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 149px; left: 459px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT08_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:61px; display:block; top: 81px; left: 572px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 124px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ06_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 55px; left: 956px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_VOT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 100px; left: 901px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LD02Z01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 21px; left: 1084px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LD03Z01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 106px; left: 1112px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LD01Z01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 136px; left: 992px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LD04Z01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 195px; left: 896px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361FN01P01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:61px; display:block; top: 238px; left: 895px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361FN01T02_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 263px; left: 907px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT06_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:63px; display:block; top: 234px; left: 1066px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 262px; left: 1079px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361FN01V01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 295px; left: 865px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361FN01V02_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 314px; left: 865px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361CN01P02_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 398px; left: 760px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361CN01P01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 443px; left: 664px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_CUN_A_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 331px; left: 1027px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 360px; left: 1026px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361FN01T01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 388px; left: 1011px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361FN01MT01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 418px; left: 1013px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361FN01MT02_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 443px; left: 1014px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361CN01P03_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 549px; left: 747px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361CN01P04_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 549px; left: 818px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B10M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 507px; left: 985px; position:absolute;color:#4cff00;text-align:right"></div>
      
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT04_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 10px; left: 1195px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT05_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 46px; left: 1209px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ09_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 242px; left: 1288px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT12_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 185px; left: 1408px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BFT05_LW_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 230px; left: 1414px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ08_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 263px; left: 1437px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BFT04_LW_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 226px; left: 1510px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT11_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 301px; left: 1511px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT10_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 339px; left: 1372px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BLT02_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 492px; left: 1392px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 446px; left: 1490px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B60M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 445px; left: 1588px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B4M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 542px; left: 1470px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI391DG01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 690px; left: 1092px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI391DG02_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 802px; left: 1018px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M_391FM01F01LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 864px; left: 1287px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI391FM01F01_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 893px; left: 1261px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BLT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 764px; left: 1566px; position:absolute;color:blue;text-align:right"></div>
      
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_TOTAL_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 691px; left: 141px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AFEED_TOTF>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 695px; left: 375px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_RAT888>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 731px; left: 109px; position:absolute;color:#4cff00;text-align:right"></div>  
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AFEED_TOLLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:86px; display:block; top: 732px; left: 356px; position:absolute;color:#4cff00;text-align:right"></div>
      
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 813px; left: 121px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 813px; left: 223px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 813px; left: 320px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 813px; left: 408px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 854px; left: 121px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 854px; left: 223px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 854px; left: 320px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 854px; left: 408px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 900px; left: 121px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 900px; left: 223px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 900px; left: 320px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 900px; left: 408px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 941px; left: 121px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 941px; left: 223px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 941px; left: 320px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 941px; left: 408px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 980px; left: 121px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT02_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 980px; left: 223px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT04_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 980px; left: 320px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT03_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:60px; display:block; top: 980px; left: 408px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01LGT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 810px; left: 582px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01RGT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 838px; left: 582px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GJT1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 864px; left: 582px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GJT2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 895px; left: 582px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GMQT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 924px; left: 582px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GMHT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 953px; left: 582px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GMT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 983px; left: 582px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01LHT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 810px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01RHT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 838px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HJT1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 864px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HJT2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 895px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HMQT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 924px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HMHT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 953px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HMT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 983px; left: 630px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_AI361LQ01LX_M>DCS'" style="display:block; top:838px; left: 797px;  position:absolute;color:#4cff00;text-align:right; height: 16px; width: 50px; "></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01LP_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 864px; left: 797px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GYT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 895px; left: 797px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GJYXT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 924px; left: 797px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01GYP_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 953px; left: 797px; position:absolute;color:#4cff00;text-align:right"></div>
      
      <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_AI361LQ01RX_M>DCS'" style="display:block; top:838px; left: 843px;  position:absolute;color:#4cff00;text-align:right; height: 16px; width: 50px; "></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01RP_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 864px; left: 843px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HYT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 895px; left: 843px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HJYXT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 924px; left: 843px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01HYP_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 953px; left: 843px; position:absolute;color:#4cff00;text-align:right"></div>

      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AO361LQ01PST_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 776px; left: 829px; position:absolute;color:#4cff00;text-align:right"></div>
      <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AI361LQ01BOXT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 982px; left: 828px; position:absolute;color:#4cff00;text-align:right"></div>     
    <%--开关量--%>  
    <%--圆形--%>  
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20ALP_AM>BoolSignal" style="position: absolute; top:84px; left: 95px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_B20ALP_AM,Clinker02_B20ALP_RN1,Clinker02_B20ALP_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20M_AM>BoolSignal" style="position: absolute; top:61px; left: 132px; height: 35px; width: 35px;" data-option="RelatedTags='Clinker02_B20M_AM,Clinker02_B20M_RN,Clinker02_B20M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361SR02_AM>BoolSignal" style="position: absolute; top:198px; left: 166px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_M361SR02_AM,Clinker02_DI361SR02FCR,Clinker02_DI361SR02FCRD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A3M_AM>BoolSignal" style="position: absolute; top:288px; left: 31px; height: 28px; width: 28px;" data-option="RelatedTags='Clinker02_A3M_AM,Clinker02_A3M_RN,Clinker02_A3M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361BC01_AM>BoolSignal" style="position: absolute; top:360px; left: 110px; height: 28px; width: 28px;" data-option="RelatedTags='Clinker02_M361BC01_AM,Clinker02_DIM361BC01R,Clinker02_DIM361BC01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361LQ05_AM>BoolSignal" style="position: absolute; top:276px; left: 246px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_M361LQ05_AM,Clinker02_DI361LQ05A1,Clinker02_DI361LQ05RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361LQ05A2>BoolSignal" style="position: absolute; top:276px; left: 270px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_M361LQ05_AM,Clinker02_DI361LQ05A2,Clinker02_DI361LQ05RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361H01_AM>BoolSignal" style="position: absolute; top:275px; left: 310px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361H01_AM,Clinker02_DI361H01R,Clinker02_DI361H01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361DG01_AM>BoolSignal" style="position: absolute; top:410px; left: 187px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361DG01_AM,Clinker02_DI361DG01R,Clinker02_DI361DG01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361SG05_AM>BoolSignal" style="position: absolute; top:478px; left: 250px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361SG05_AM,Clinker02_M361SG05_RN,Clinker02_DIM361SG05RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361BE02_AM>BoolSignal" style="position: absolute; top:415px; left: 304px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361BE02_AM,Clinker02_DI361BE02R,Clinker02_DI361BE02RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_AM>BoolSignal" style="position: absolute; top:497px; left: 414px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_A8M_AM,Clinker02_A8M_RN,Clinker02_A8M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361FN04_AM>BoolSignal" style="position: absolute; top:578px; left: 391px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361FN04_AM,Clinker02_DIM361FN04R,Clinker02_DIM361FN04RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>

      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B26AC_AM>BoolSignal" style="position: absolute; top:109px; left: 780px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B26AC_AM,Clinker02_B26AC_RN,Clinker02_B26AC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B24M_RN>BoolSignal" style="position: absolute; top:191px; left: 712px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B26AC_AM,Clinker02_B24M_RN,Clinker02_B26AC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B26AC_RD>BoolSignal" style="position: absolute; top:236px; left: 752px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B26AC_AM,Clinker02_B25M_RN,Clinker02_B26AC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B22M_RN>BoolSignal" style="position: absolute; top:281px; left: 708px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B26AC_AM,Clinker02_B22M_RN,Clinker02_B26AC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B23M_RN>BoolSignal" style="position: absolute; top:281px; left: 753px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B26AC_AM,Clinker02_B23M_RN,Clinker02_B26AC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B21M_AM>BoolSignal" style="position: absolute; top:344px; left: 868px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B21M_AM,Clinker02_B21M_RN,Clinker02_B21M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_AM>BoolSignal" style="position: absolute; top:361px; left: 961px; height: 35px; width: 35px;" data-option="RelatedTags='Clinker02_B52ACP_AM,Clinker02_B52ACP_OK,Clinker02_B52ACP_RD1',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361BE01_AM>BoolSignal" style="position: absolute; top:257px; left: 446px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361BE01_AM,Clinker02_DI361BE01R,Clinker02_DI361BE01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361MS01_AM>BoolSignal" style="position: absolute; top:307px; left: 517px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361MS01_AM,Clinker02_DI361MS01R,Clinker02_DI361MS01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361SG02_AM>BoolSignal" style="position: absolute; top:361px; left: 506px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361SG02_AM,Clinker02_M361SG02_RN,Clinker02_DIM361SG02RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361LQ01YV_AM>BoolSignal" style="position: absolute; top:454px; left: 597px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361LQ01YV_AM,Clinker02_DO361LQ01D4,Clinker02_M361LQ01M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361RF01_AM>BoolSignal" style="position: absolute; top:582px; left: 781px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361RF01_AM,Clinker02_DIM361RF01R,Clinker02_DIM361RF01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361RF02_AM>BoolSignal" style="position: absolute; top:582px; left: 844px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361RF02_AM,Clinker02_DIM361RF02R,Clinker02_DIM361RF02RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361FN02_AM>BoolSignal" style="position: absolute; top:680px; left: 775px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361FN02_AM,Clinker02_DIM361FN02R,Clinker02_DIM361FN02RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361FN03_AM>BoolSignal" style="position: absolute; top:680px; left: 861px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M361FN03_AM,Clinker02_DIM361FN03R,Clinker02_DIM361FN03RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F29M_AM>BoolSignal" style="position: absolute; top:27px; left: 1479px; height: 35px; width: 35px;" data-option="RelatedTags='Clinker02_F29M_AM,Clinker02_F29M_ZRN,Clinker02_F29M_ZRD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59AC_AM>BoolSignal" style="position: absolute; top:390px; left: 1494px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B59AC_AM,Clinker02_B59AC_RN,Clinker02_B59AC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B60AC_AM>BoolSignal" style="position: absolute; top:390px; left: 1595px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B60AC_AM,Clinker02_B60AC_RN,Clinker02_B60AC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B10M_AM>BoolSignal" style="position: absolute; top:532px; left: 974px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B10M_AM,Clinker02_B10M_RN,Clinker02_B10M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B15M_AM>BoolSignal" style="position: absolute; top:423px; left: 1143px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B15M_AM,Clinker02_B15M_RN,Clinker02_B15M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B17M_AM>BoolSignal" style="position: absolute; top:488px; left: 1158px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B17M_AM,Clinker02_B17M_RN,Clinker02_B17M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B16M_AM>BoolSignal" style="position: absolute; top:488px; left: 1196px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B16M_AM,Clinker02_B16M_RN,Clinker02_B16M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B18M_AM>BoolSignal" style="position: absolute; top:433px; left: 1319px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B18M_AM,Clinker02_B18M_RN,Clinker02_B18M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B14M_AM>BoolSignal" style="position: absolute; top:464px; left: 1285px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B14M_AM,Clinker02_B14M_RN,Clinker02_B14M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B13M_AM>BoolSignal" style="position: absolute; top:583px; left: 1113px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B13M_AM,Clinker02_B13M_RN,Clinker02_B13M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B7ALC_AM>BoolSignal" style="position: absolute; top:617px; left: 1190px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B7ALC_AM,Clinker02_B7ALC_RN,Clinker02_B7ALC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B6ALC_AM>BoolSignal" style="position: absolute; top:608px; left: 1355px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B6ALC_AM,Clinker02_B6ALC_RN,Clinker02_B6ALC_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B9M_AM>BoolSignal" style="position: absolute; top:783px; left: 1114px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B9M_AM,Clinker02_B9M_RN,Clinker02_B9M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B8M_AM>BoolSignal" style="position: absolute; top:783px; left: 1225px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B8M_AM,Clinker02_B8M_RN,Clinker02_B8M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M391SG01_AM>BoolSignal" style="position: absolute; top:762px; left: 1297px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M391SG01_AM,Clinker02_M391SG01_RN,Clinker02_DI391SG01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M391SG02_AM>BoolSignal" style="position: absolute; top:819px; left: 1297px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M391SG02_AM,Clinker02_M391SG02_RN,Clinker02_DI391SG02RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B65M_AM>BoolSignal" style="position: absolute; top:764px; left: 1369px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B65M_AM,Clinker02_B65M_RN,Clinker02_B65M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M391FN01_AM>BoolSignal" style="position: absolute; top:923px; left: 1081px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M391FN01_AM,Clinker02_DIM391FN01R,Clinker02_DIM391FN01RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M391FN02_AM>BoolSignal" style="position: absolute; top:970px; left: 1226px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_M391FN02_AM,Clinker02_DIM391FN02R,Clinker02_DIM391FN02RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B4M_AM>BoolSignal" style="position: absolute; top:539px; left: 1421px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B4M_AM,Clinker02_B4M_RN,Clinker02_B4M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B2M_AM>BoolSignal" style="position: absolute; top:527px; left: 1591px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B2M_AM,Clinker02_B2M_RN,Clinker02_B2M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B3M_AM>BoolSignal" style="position: absolute; top:666px; left: 1526px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B3M_AM,Clinker02_B3M_RN,Clinker02_B3M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
        
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_AM>BoolSignal" style="position: absolute; top:767px; left: 160px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A4M_AM,Clinker02_A4M_RN,Clinker02_A4M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_AM>BoolSignal" style="position: absolute; top:767px; left: 254px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A7M_AM,Clinker02_A7M_RN,Clinker02_A7M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_AM>BoolSignal" style="position: absolute; top:767px; left: 360px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A5M_AM,Clinker02_A5M_RN,Clinker02_A5M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_AM>BoolSignal" style="position: absolute; top:767px; left: 449px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A6M_AM,Clinker02_A6M_RN,Clinker02_A6M_RD',Display='000:lightblueC,001:yellowC,010:greenCB,011:greenC,100:redCB,101:redC,110:redC,111:redC'"></div>

      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01ACC1JX>BoolSignal" style="position: absolute; top:526px; left: 525px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_DI361RP01ACC1JX,Clinker02_DI361RP01ACC1TX',Display='00:whiteC,01:yellowC,10:greenC,011:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01ACC2JX>BoolSignal" style="position: absolute; top:526px; left: 625px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_DI361RP01ACC2JX,Clinker02_DI361RP01ACC2TX',Display='00:whiteC,01:yellowC,10:greenC,011:redC'"></div>

      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01GMR>BoolSignal" style="position: absolute; top:544px; left: 536px; height: 38px; width: 38px;" data-option="RelatedTags='Clinker02_DI361RP01GMR,Clinker02_DI361RP01GMRD',Display='00:lightblueC,01:yellowC,10:greenCB,011:greenC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01HMR>BoolSignal" style="position: absolute; top:544px; left: 596px; height: 38px; width: 38px;" data-option="RelatedTags='Clinker02_DI361RP01HMR,Clinker02_DI361RP01HMRD',Display='00:lightblueC,01:yellowC,10:greenCB,011:greenC'"></div>
     
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BHSB_RN>BoolSignal" style="position: absolute; top:73px; left: 1579px; height: 38px; width: 38px;" data-option="RelatedTags='Clinker02_BHSB_RN,Clinker02_BHSB_RD',Display='00:lightblueC,01:yellowC,10:redCB,011:greenCB'"></div>

      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DIM361BE02MT02R>BoolSignal" style="position: absolute; top:457px; left: 304px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_DIM361BE02MT02R',Display='0:lightblueC,1:greenC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DIM361BE01MT02R>BoolSignal" style="position: absolute; top:298px; left: 446px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_DIM361BE01MT02R',Display='0:lightblueC,1:greenC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DIB211_10R>BoolSignal" style="position: absolute; top:906px; left: 1389px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_DIB211_10R',Display='0:lightblueC,1:greenC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B5M_RN>BoolSignal" style="position: absolute; top:584px; left: 1421px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker02_B5M_RN',Display='0:lightblueC,1:greenCB'"></div>          
    <%--方形--%>
      <%--三个变量--%> 
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A1ALC_AM>BoolSignal" style="position: absolute; top:264px; left: 18px; height: 18px; width: 40px;" data-option="RelatedTags='Clinker02_A1ALC_AM,Clinker02_A1ALC_RN,Clinker02_A1ALC_RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361BF01_AM>BoolSignal" style="position: absolute; top:273px; left: 89px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_M361BF01_AM,Clinker02_DI361BF01R,Clinker02_DI361BF01RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361RP01EH02_AM>BoolSignal" style="position: absolute; top:582px; left: 605px; height: 15px; width: 30px;" data-option="RelatedTags='Clinker02_M361RP01EH02_AM,Clinker02_DI361RP01EH02R,Clinker02_DI361RP01EH02RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361RP01ACC1_AM>BoolSignal" style="position: absolute; top:537px; left: 483px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_M361RP01ACC1_AM,Clinker02_DI361RP01ACC1JX,Clinker02_DI361RP01ACC1RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361RP01ACC2_AM>BoolSignal" style="position: absolute; top:537px; left: 651px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_M361RP01ACC2_AM,Clinker02_DI361RP01ACC2JX,Clinker02_DI361RP01ACC2RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_AM>BoolSignal" style="position: absolute; top:73px; left: 768px; height: 30px; width: 50px;" data-option="RelatedTags='Clinker02_B41AC_AM,Clinker02_B41AC_RN,Clinker02_B41AC_RD1',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B7ALC_RN>BoolSignal" style="position: absolute; top:657px; left: 1186px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_B7ALC_AM,Clinker02_B7ALC_RN,Clinker02_B7ALC_RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B6ALC_RN>BoolSignal" style="position: absolute; top:647px; left: 1351px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_B6ALC_AM,Clinker02_B6ALC_RN,Clinker02_B6ALC_RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M391BF01_AM>BoolSignal" style="position: absolute; top:796px; left: 1175px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_M391BF01_AM,Clinker02_DI391BF01R,Clinker02_DI391BF01RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B62M_AM>BoolSignal" style="position: absolute; top:337px; left: 1498px; height: 35px; width: 16px;" data-option="RelatedTags='Clinker02_B62M_AM,Clinker02_B62M_RN,Clinker02_B62M_RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B63M_AM>BoolSignal" style="position: absolute; top:337px; left: 1599px; height: 35px; width: 16px;" data-option="RelatedTags='Clinker02_B63M_AM,Clinker02_B63M_RN,Clinker02_B63M_RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B1ALC_AM>BoolSignal" style="position: absolute; top:580px; left: 1587px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_B1ALC_AM,Clinker02_B1ALC_RN,Clinker02_B1ALC_RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361LQ01M_AM>BoolSignal" style="position: absolute; top:745px; left: 542px; height: 35px; width: 20px;" data-option="RelatedTags='Clinker02_M361LQ01M_AM,Clinker02_DI361LQ01R,Clinker02_M361LQ01M_RD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_M361LQ01Y_AM>BoolSignal" style="position: absolute; top:742px; left: 828px; height: 20px; width: 35px;" data-option="RelatedTags='Clinker02_M361LQ01Y_AM,Clinker02_DI361LQ01YR1,Clinker02_DI361LQ01YRD',Display='000:lightblueS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:redS'"></div>
      <%--两个变量--%>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361LD05LF>BoolSignal" style="position: absolute; top:563px; left: 70px; height: 40px; width: 18px;" data-option="RelatedTags='Clinker02_DI361LD05LF,Clinker02_DI361LD05LR',Display='00:lightblueS,01:yellowS,10:blueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361LD02LF>BoolSignal" style="position: absolute; top:2px; left: 1058px; height: 15px; width: 35px;" data-option="RelatedTags='Clinker02_DI361LD02LF,Clinker02_DI361LD02LR',Display='00:lightblueS,01:yellowS,10:blueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361LD04LF>BoolSignal" style="position: absolute; top:170px; left: 903px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_DI361LD04LF,Clinker02_DI361LD04LR',Display='00:lightblueS,01:yellowS,10:blueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361LD01LF>BoolSignal" style="position: absolute; top:125px; left: 976px; height: 35px; width: 18px;" data-option="RelatedTags='Clinker02_DI361LD01LF,Clinker02_DI361LD01LR',Display='00:lightblueS,01:yellowS,10:blueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361LD03LF>BoolSignal" style="position: absolute; top:67px; left: 1188px; height: 35px; width: 18px;" data-option="RelatedTags='Clinker02_DI361LD03LF,Clinker02_DI361LD03LR',Display='00:lightblueS,01:yellowS,10:blueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI391DG02LF>BoolSignal" style="position: absolute; top:792px; left: 1006px; height: 35px; width:18px;" data-option="RelatedTags='Clinker02_DI391DG02LF,Clinker02_DI391DG02LR',Display='00:lightblueS,01:yellowS,10:blueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI391DG01LF>BoolSignal" style="position: absolute; top:640px; left: 1085px; height: 35px; width: 18px;" data-option="RelatedTags='Clinker02_DI391DG01LF,Clinker02_DI391DG01LR',Display='00:lightblueS,01:yellowS,10:blueS,11:redS'"></div>
    
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DIM361SG05FSQ>BoolSignal" style="position: absolute; top:485px; left: 277px; height: 15px; width: 30px;" data-option="RelatedTags='Clinker02_DIM361SG05FSQ,Clinker02_DIM361SG05RSQ',Display='00:lightblueS,01:yellowS,10:lightblueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DIM361SG02FSQ>BoolSignal" style="position: absolute; top:371px; left: 471px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_DIM361SG02FSQ,Clinker02_DIM361SG02RSQ',Display='00:lightblueS,01:yellowS,10:lightblueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361SG01SQF>BoolSignal" style="position: absolute; top:457px; left: 559px; height: 18px; width: 35px;" data-option="RelatedTags='Clinker02_DI361SG01SQF,Clinker02_DI361SG01SQR',Display='00:lightblueS,01:yellowS,10:lightblueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI391SG01LF>BoolSignal" style="position: absolute; top:732px; left: 1300px; height: 30px; width: 18px;" data-option="RelatedTags='Clinker02_DI391SG01LF,Clinker02_DI391SG01LR',Display='00:lightblueS,01:yellowS,10:lightblueS,11:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI391SG02LF>BoolSignal" style="position: absolute; top:786px; left: 1300px; height: 30px; width: 18px;" data-option="RelatedTags='Clinker02_DI391SG02LF,Clinker02_DI391SG02LR',Display='00:lightblueS,01:yellowS,10:lightblueS,11:redS'"></div>      
      <%--一个变量--%>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20ALP_RD>BoolSignal" style="position: absolute; top:44px; left: 32px; height: 16px; width: 30px;" data-option="RelatedTags='Clinker02_B20ALP_RD',Display='0:whiteS,1:yellowS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20ALP_OK>BoolSignal" style="position: absolute; top:65px; left: 32px; height: 16px; width: 30px;" data-option="RelatedTags='Clinker02_B20ALP_OK',Display='0:whiteS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_EZZ02_LM>BoolSignal" style="position: absolute; top:63px; left: 210px; height: 16px; width: 30px;" data-option="RelatedTags='Clinker02_EZZ02_LM',Display='0:lightblueS,1:yellowS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361SR02CC>BoolSignal" style="position: absolute; top:179px; left: 162px; height: 16px; width: 30px;" data-option="RelatedTags='Clinker02_DI361SR02CC',Display='0:NULL,1:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361SR02F>BoolSignal" style="position: absolute; top:209px; left: 191px; height: 30px; width: 16px;" data-option="RelatedTags='Clinker02_DI361SR02F',Display='0:NULL,1:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B55ALC_FT>BoolSignal" style="position: absolute; top:272px; left: 27px; height: 9px; width: 22px;" data-option="RelatedTags='Clinker02_B55ALC_FT',Display='0:NULL,1:redS'"></div>

      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361LQ05EHA>BoolSignal" style="position: absolute; top:326px; left: 231px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_DI361LQ05EHA',Display='0:lightblueS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DIM361BE01MT02SQ>BoolSignal" style="position: absolute; top:281px; left: 446px; height: 15px; width: 24px;" data-option="RelatedTags='Clinker02_DIM361BE01MT02SQ',Display='0:whiteS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DIM361BE02MT02SQ>BoolSignal" style="position: absolute; top:440px; left: 304px; height: 15px; width: 24px;" data-option="RelatedTags='Clinker02_DIM361BE02MT02SQ',Display='0:whiteS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361BE01F>BoolSignal" style="position: absolute; top:367px; left: 451px; height: 28px; width: 15px;" data-option="RelatedTags='Clinker02_DI361BE01F',Display='0:NULL,1:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361MS01F>BoolSignal" style="position: absolute; top:314px; left: 552px; height: 28px; width: 15px;" data-option="RelatedTags='Clinker02_DI361MS01F',Display='0:NULL,1:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01LSR1RD>BoolSignal" style="position: absolute; top:557px; left: 487px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_DI361RP01LSR1RD',Display='0:whiteS,1:yellowS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01LSR1OK>BoolSignal" style="position: absolute; top:573px; left: 487px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_DI361RP01LSR1OK',Display='0:whiteS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01LSR1EH>BoolSignal" style="position: absolute; top:589px; left: 487px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_DI361RP01LSR1EH',Display='0:lightblueS,1:greenS'"></div>    
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01LSR2RD>BoolSignal" style="position: absolute; top:557px; left: 655px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_DI361RP01LSR2RD',Display='0:whiteS,1:yellowS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01LSR2OK>BoolSignal" style="position: absolute; top:573px; left: 655px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_DI361RP01LSR2OK',Display='0:whiteS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DI361RP01LSR2EH>BoolSignal" style="position: absolute; top:589px; left: 655px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_DI361RP01LSR2EH',Display='0:lightblueS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52M_RN>BoolSignal" style="position: absolute; top:409px; left: 932px; height: 15px; width: 28px;" data-option="RelatedTags='Clinker02_B52M_RN',Display='0:lightblueS,1:greenS'"></div>
      <%--箭头--%>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B17M_SEL>BoolSignal" style="position: absolute; top:452px; left: 1153px; height: 15px; width: 40px;" data-option="RelatedTags='Clinker02_B17M_SEL',Display='0:NULL,1:arrowYellowLeft'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B17M_SEL1>BoolSignal" style="position: absolute; top:452px; left: 1197px; height: 15px; width: 40px;" data-option="RelatedTags='Clinker02_B17M_SEL',Display='0:arrowYellowRight,1:NULL'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59AC_SEL>BoolSignal" style="position: absolute; top:399px; left: 1521px; height: 15px; width: 40px;" data-option="RelatedTags='Clinker02_B59AC_SEL',Display='0:NULL,1:arrowYellowLeft'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59AC_SEL1>BoolSignal" style="position: absolute; top:398px; left: 1555px; height: 15px; width: 40px;" data-option="RelatedTags='Clinker02_B59AC_SEL',Display='0:arrowYellowRight,1:NULL'"></div>
    <%--汉字隐藏--%>
      <div id="zc_nxjc_qtx_efc>Clinker02_B20ALP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 104px; left: 19px; color:yellow;font-size:15px;">允许启动</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 194px; left: 13px; color:red;font-size:15px;">一度跑偏</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 211px; left: 13px; color:red;font-size:15px;">二度跑偏</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 228px; left: 13px; color:red;font-size:15px;">速度报警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DIM361BC01SRP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 365px; left: 69px; color:red;font-size:15px;">拉绳</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DIM361BC01SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 392px; left: 36px; color:red;font-size:15px;">一度跑偏</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DIM361BC01SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 409px; left: 36px; color:red;font-size:15px;">二度跑偏</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DIM361BC01SR>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 426px; left: 36px; color:red;font-size:15px;">速度报警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DI361LQ05OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 326px; left: 263px; color:yellow;font-size:15px;">允许启动</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DI361BE01SF>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 262px; left: 426px; color:yellow;font-size:15px;">起<br/>动<br/>完<br/>毕</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DI361BE02SF>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 419px; left: 332px; color:yellow;font-size:15px;">起<br/>动<br/>完<br/>毕</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DI361BE01QC2C>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 459px; left: 450px; color:red;font-size:15px;">速<br/>度<br/>报<br/>警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DI361BE02QC2C>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 542px; left: 308px; color:red;font-size:15px;">速<br/>度<br/>报<br/>警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DIM361BE02LS>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 658px; left: 244px; color:red;font-size:15px;">料位报警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DIM361BE01LS>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 661px; left: 370px; color:red;font-size:15px;">料位报警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_QCX_SEL>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 639px; left: 9px; color:yellow;font-size:15px;">QCX配料</div>
      <%--<div id="zc_nxjc_qtx_efc>Clinker02_QCX_SEL>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 180px; left: 612px; color:yellow;font-size:15px;">人工配料</div>--%>
      <div id="zc_nxjc_qtx_efc>Clinker02_QCX_RN2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 657px; left: 9px; color:#4cff00;font-size:15px;">QCX运行</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_DI361LQ01CCR>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 752px; left: 592px; color:#4cff00;font-size:15px;">中控</div>
              
      <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_RN1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 434px; left: 940px; color:#4cff00;font-size:15px;">启动中</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 471px; left: 940px; color:#4cff00;font-size:15px;">变频器允许运行</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 471px; left: 947px; color:red;font-size:15px;">变频器轻故障</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_BPID_SEL>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 273px; left: 1238px; color:yellow;font-size:15px;">自<br/>动</div>
      <%--<div id="zc_nxjc_qtx_efc>Clinker02_BPID_SEL>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 317px; left: 1238px; color:yellow;font-size:15px;">手<br/>动</div>--%>
      <div id="zc_nxjc_qtx_efc>Clinker02_B62M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 337px; left: 1521px; color:yellow;font-size:15px;">开</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B62M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 357px; left: 1521px; color:yellow;font-size:15px;">关</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B63M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 337px; left: 1621px; color:yellow;font-size:15px;">开</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B63M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 357px; left: 1621px; color:yellow;font-size:15px;">关</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B10M_LVS>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 709px; left: 978px; color:red;font-size:15px;">料<br/>位<br/>报<br/>警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B4M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 657px; left: 1427px; color:red;font-size:15px;">速<br/>度<br/>报<br/>警</div>
      <div id="zc_nxjc_qtx_efc>Clinker02_B4M_LVS>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 853px; left: 1405px; color:red;font-size:15px;">料位报警</div>
    <%--棒图--%>
      <div class="BarGraph mchart" id="zc_nxjc_qtx_efc>Clinker02_BLT02_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:40px; height:74px; position:absolute; top: 411px; left: 1406px;"></div> 
    </div>
</body>
</html>

