<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_clinker02_slfmjfqcl.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_clinker02_slfmjfqcl" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc";
        publicData.sceneName = "2#生料粉磨及废气处理";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
<div id="ForeGround" style=" width: 1480px; height: 760px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_clinker02_slfmjfqcl.png'); width: 1480px; height: 760px; overflow: hidden; top: 0px; left: 0px;">
         <div id="ConnectionGround" style="width: 1480px; height: 760px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
   <div id="TextGround"style="font-size:large;padding-left:1000px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1480px;height: 760px;"></div>   
        <div id="Picture"style="position: absolute; top: 4px; left: 976px; height: 20px; width: 20px; background-size:100% auto"></div> 
    <%--标签粘贴处--%>
        <%--<button onclick="CheckTags()">检查标签</button>--%>
        <%--开关量--%>  
        <%--库罐图形左面面圆形开关量--%>  
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BHSB_RD>BoolSignal" style="position: absolute; top:17px; left: 70px; height: 29px; width: 52px;" data-option="RelatedTags='Clinker02_BHSB_RD,Clinker02_BHSB_RN',Display='00:lightBlueC,01:yellowCB,10:redC,11:greenCB'"></div>    
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20M_RD>BoolSignal" style="position: absolute; top:84px; left: 180px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_B20M_RD,Clinker02_B20M_RN,Clinker02_B20M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20LP_RD>BoolSignal" style="position: absolute; top:158px; left: 165px; height: 19px; width: 20px;" data-option="RelatedTags='Clinker02_B20ALP_RD,Clinker02_B20ALP_RN1,Clinker02_B20ALP_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B26AC_RD>BoolSignal" style="position: absolute; top:101px; left: 449px; height: 19px; width: 20px;" data-option="RelatedTags='Clinker02_B26AC_RD,Clinker02_B26AC_RN,Clinker02_B26AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B24M_RN>BoolSignal" style="position: absolute; top:177px; left: 463px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B26AC_RD,Clinker02_B24M_RN,Clinker02_B26AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B22M_RN>BoolSignal" style="position: absolute; top:194px; left: 474px; height: 12px; width: 13px;" data-option="RelatedTags='Clinker02_B26AC_RD,Clinker02_B22M_RN,Clinker02_B26AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B21M_AM>BoolSignal" style="position: absolute; top:230px; left: 536px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B21M_RD ,Clinker02_B21M_RN,Clinker02_B21M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B25M_RN>BoolSignal" style="position: absolute; top:152px; left: 477px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B26AC_RD,Clinker02_B25M_RN,Clinker02_B26AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B23M_RN>BoolSignal" style="position: absolute; top:171px; left: 491px; height: 17px; width: 16px;" data-option="RelatedTags='Clinker02_B26AC_RD,Clinker02_B23M_RN,Clinker02_B26AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B2ALP_RD>BoolSignal" style="position: absolute; top:140px; left: 608px; height: 19px; width: 20px;" data-option="RelatedTags='Clinker02_B52ALP_RD,Clinker02_B52ALP_RN1,Clinker02_B52ALP_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B51ALC_RD>BoolSignal" style="position: absolute; top:196px; left: 621px; height: 19px; width: 20px;" data-option="RelatedTags='Clinker02_B51ALC_RD,Clinker02_B51ALC_RN1,Clinker02_B51ALC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B51ALC_RN2>BoolSignal" style="position: absolute; top:196px; left: 647px; height: 19px; width: 20px;" data-option="RelatedTags='Clinker02_B51ALC_RD,Clinker02_B51ALC_RN2,Clinker02_B51ALC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52M_RD>BoolSignal" style="position: absolute; top:268px; left: 774px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_B52M_RD,Clinker02_B52M_RN,Clinker02_B52M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
      
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A3M_RD>BoolSignal" style="position: absolute; top: 275px; left: 129px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_A3M_RD,Clinker02_A3M_RN,Clinker02_A3M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>             
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A2M_RN>BoolSignal" style="position: absolute; top: 291px; left: 208px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_A2M_RD,Clinker02_A2M_RN,Clinker02_A2M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>      
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A1ALC_RD>BoolSignal" style="position: absolute; top:267px; left: 245px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_A1ALC_RD,Clinker02_A1ALC_RN,Clinker02_A1ALC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B55ALC_RD2>BoolSignal" style="position: absolute; top:327px; left: 158px; height: 23px; width: 23px;" data-option="RelatedTags='Clinker02_B55ALC_RD2,Clinker02_B55ALC_RN,Clinker02_B55ALC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B55ALC_FT>BoolSignal" style="position: absolute; top:305px; left: 163px; height: 13px; width: 13px;" data-option="RelatedTags='Clinker02_B55ALC_FT',Display='0:NULL,1:redS'"></div>      
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B46M_RD>BoolSignal" style="position: absolute; top:265px; left: 300px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_B46M_RD,Clinker02_B46M_RN,Clinker02_B46M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B55M_RD>BoolSignal" style="position: absolute; top:348px; left: 337px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_B55M_RD,Clinker02_B55M_RN,Clinker02_B55M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B54M_RD>BoolSignal" style="position: absolute; top:401px; left: 358px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_B54M_RD,Clinker02_B54M_RN,Clinker02_B54M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BG4_RN1>BoolSignal" style="position: absolute; top:425px; left: 394px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_BG4_RN1',Display='0:lightBlueC,1:greenC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALP_RN1>BoolSignal" style="position: absolute; top:363px; left: 442px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B49ALP_RD,Clinker02_B49ALP_RN1,Clinker02_B49ALP_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC2_RD>BoolSignal" style="position: absolute; top:294px; left: 547px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_B49ALC2_RD,Clinker02_B49ALC2_RN1,Clinker02_B49ALC2_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC2_RN2>BoolSignal" style="position: absolute; top:294px; left: 576px; height: 20px; width: 20px;" data-option="RelatedTags='Clinker02_B49ALC2_RD,Clinker02_B49ALC2_RN2,Clinker02_B49ALC2_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_RN1>BoolSignal" style="position: absolute; top:337px; left: 549px; height: 15px; width: 15px; " data-option="RelatedTags='Clinker02_B49ALC1_RD,Clinker02_B49ALC1_RN1,Clinker02_B49ALC1_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_RN2>BoolSignal" style="position: absolute; top:337px; left: 574px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B49ALC1_RD,Clinker02_B52M_RN,Clinker02_B49ALC1_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_RN3>BoolSignal" style="position: absolute; top:356px; left: 549px; height: 15px; width: 15px; right: 917px;" data-option="RelatedTags='Clinker02_B49ALC1_RD,Clinker02_B49ALC1_RN3,Clinker02_B49ALC1_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_RN4>BoolSignal" style="position: absolute; top:356px; left: 574px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B49ALC1_RD,Clinker02_B49ALC1_RN4,Clinker02_B49ALC1_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>   

 
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_Q2ALC1_RD>BoolSignal" style="position: absolute; top:434px; left: 72px; height: 19px; width: 19px;" data-option="RelatedTags='Clinker02_Q2ALC1_RD,Clinker02_Q2ALC1_RN,Clinker02_Q2ALC1_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_Q2ALC2_RD>BoolSignal" style="position: absolute; top:510px; left: 119px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_Q2ALC2_RD,Clinker02_Q2ALC2_RN,Clinker02_Q2ALC2_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A13M_RD>BoolSignal" style="position: absolute; top:462px; left: 202px; height: 18px; width: 17px;" data-option="RelatedTags='Clinker02_A13M_RD,Clinker02_A13M_RN,Clinker02_A13M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B47M_RD>BoolSignal" style="position: absolute; top:548px; left: 324px; height: 19px; width: 19px;" data-option="RelatedTags='Clinker02_B47M_RD,Clinker02_B47M_RN,Clinker02_B47M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_RD>BoolSignal" style="position: absolute; top:607px; left: 171px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_A8M_RD,Clinker02_A8M_RN,Clinker02_A8M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_RD>BoolSignal" style="position: absolute; top:674px; left: 56px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_A4M_RD,Clinker02_A4M_RN,Clinker02_A4M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_RD>BoolSignal" style="position: absolute; top:695px; left: 56px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_A7M_RD,Clinker02_A7M_RN,Clinker02_A7M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_RD>BoolSignal" style="position: absolute; top:715px; left: 56px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_A5M_RD,Clinker02_A5M_RN,Clinker02_A5M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_RD>BoolSignal" style="position: absolute; top:736px; left: 56px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_A6M_RD,Clinker02_A6M_RN,Clinker02_A6M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B60M_DR1>BoolSignal" style="position: absolute; top:544px; left: 428px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B60M_DR1',Display='0:lightBlueC,1:grayCB'"></div> 
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_RD>BoolSignal" style="position: absolute; top:430px; left: 537px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B50M_RD,Clinker02_B50M_RN',Display='00:lightBlueC,01:greenCB,10:yellowC,11:greenC'"></div> 
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B61M_RD>BoolSignal" style="position: absolute; top:491px; left: 656px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B61M_RD,Clinker02_B61M_RN,Clinker02_B61M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48M_RD>BoolSignal" style="position: absolute; top:573px; left: 664px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B48M_RD,Clinker02_B48M_RN,Clinker02_B48M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B11M_RN>BoolSignal" style="position: absolute; top:626px; left: 745px; height: 15px; width: 15px; right: 720px;" data-option="RelatedTags='Clinker02_B11M_RD,Clinker02_B11M_RN,Clinker02_B11M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B11M_RD>BoolSignal" style="position: absolute; top:625px; left: 860px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B11M_RD,Clinker02_B11M_RN,Clinker02_B11M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B42M_RD>BoolSignal" style="position: absolute; top:541px; left: 729px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B42M_RD,Clinker02_B42M_RN,Clinker02_B42M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B43M_RD>BoolSignal" style="position: absolute; top:542px; left: 783px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B43M_RD,Clinker02_B43M_RN,Clinker02_B43M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B44M_RD>BoolSignal" style="position: absolute; top:541px; left: 831px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B44M_RD,Clinker02_B44M_RN,Clinker02_B44M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B45M_RD>BoolSignal" style="position: absolute; top:541px; left: 872px; height: 17px; width: 17px;" data-option="RelatedTags='Clinker02_B45M_RD,Clinker02_B45M_RN,Clinker02_B45M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>




    <%--圆形--%>       
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B12ALC_RN>BoolSignal" style="position: absolute; top: 540px; left: 933px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B12ALC_RD,Clinker02_B12ALC_RN,Clinker02_B12ALC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B10M_RD>BoolSignal" style="position: absolute; top: 498px; left: 979px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_B10M_RD,Clinker02_B10M_RN,Clinker02_B10M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B13M_RD>BoolSignal" style="position: absolute; top: 382px; left: 1013px; height: 21px; width: 21px;" data-option="RelatedTags='Clinker02_B13M_RD,Clinker02_B13M_RN,Clinker02_B13M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B17M_RD>BoolSignal" style="position: absolute; top: 284px; left: 1082px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_B17M_RD,Clinker02_B17M_RN,Clinker02_B17M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B15M_RD>BoolSignal" style="position: absolute; top: 313px; left: 1082px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_B15M_RD,Clinker02_B15M_RN,Clinker02_B15M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B16M_RD>BoolSignal" style="position: absolute; top: 313px; left: 1156px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_B16M_RD,Clinker02_B16M_RN,Clinker02_B16M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B18M_RD>BoolSignal" style="position: absolute; top: 330px; left: 1205px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_B18M_RD,Clinker02_B18M_RN,Clinker02_B18M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B14M_RD>BoolSignal" style="position: absolute; top: 362px; left: 1155px; height: 18px; width: 18px;" data-option="RelatedTags='Clinker02_B14M_RD,Clinker02_B14M_RN,Clinker02_B14M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B7ALC_RD>BoolSignal" style="position: absolute; top: 498px; left: 1083px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B7ALC_RD,Clinker02_B7ALC_RN,Clinker02_B7ALC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B6ALC_RD>BoolSignal" style="position: absolute; top: 498px; left: 1136px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B6ALC_RD,Clinker02_B6ALC_RN,Clinker02_B6ALC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B9M_RD>BoolSignal" style="position: absolute; top: 616px; left: 1017px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B9M_RD,Clinker02_B9M_RN,Clinker02_B9M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B8M_RD>BoolSignal" style="position: absolute; top: 613px; left: 1091px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B8M_RD,Clinker02_B8M_RN,Clinker02_B8M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B4M_RD>BoolSignal" style="position: absolute; top: 422px; left: 1219px; height: 19px; width: 18px;" data-option="RelatedTags='Clinker02_B4M_RD,Clinker02_B4M_RN,Clinker02_B4M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B5M_RN>BoolSignal" style="position: absolute; top: 456px; left: 1224px; height: 8px; width: 9px;" data-option="RelatedTags='Clinker02_B5M_RN',Display='0:lightBlueC,1:greenCB'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B61_RD>BoolSignal" style="position: absolute; top: 284px; left: 1416px; height: 19px; width: 18px;" data-option="RelatedTags='Clinker02_B61M_RD,Clinker02_B61M_RN,Clinker02_B61M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B60AC_RD>BoolSignal" style="position: absolute; top: 335px; left: 1417px; height: 19px; width: 18px;" data-option="RelatedTags='Clinker02_B60AC_RD,Clinker02_B60AC_RN,Clinker02_B60AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59AC_RD>BoolSignal" style="position: absolute; top: 390px; left: 1417px; height: 19px; width: 18px;" data-option="RelatedTags='Clinker02_B59AC_RD,Clinker02_B59AC_RN,Clinker02_B59AC_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>  
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B2M_RD>BoolSignal" style="position: absolute; top: 567px; left: 1440px; height: 15px; width: 15px; right: 25px;" data-option="RelatedTags='Clinker02_B2M_RD,Clinker02_B2M_RN,Clinker02_B2M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B3M_RD>BoolSignal" style="position: absolute; top: 563px; left: 1260px; height: 15px; width: 15px;" data-option="RelatedTags='Clinker02_B3M_RD,Clinker02_B3M_RN,Clinker02_B3M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F29M_RD>BoolSignal" style="position: absolute; top: 94px; left: 1315px; height: 26px; width: 26px;" data-option="RelatedTags='Clinker02_F29M_RD,Clinker02_F29M_RN,Clinker02_F29M_AM',Display='000:lightBlueC,001:redCB,010:greenCB,011:redC,100:yellowC,101:redC,110:greenC,111:redC,111:redC'"></div>

         <%--方形--%>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BHSB_RD1>BoolSignal" style="position: absolute; top:17px; left: 72px; height: 30px; width: 51px;" data-option="RelatedTags='Clinker02_BHSB_RD,Clinker02_BHSB_RN',Display='00:lightBlueS,01:yellowSB,10:redS,11:greenSB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_RD1>BoolSignal" style="position: absolute; top:68px; left: 436px; height: 28px; width: 44px;" data-option="RelatedTags='Clinker02_B41AC_RD1,Clinker02_B41AC_RN,Clinker02_B41AC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>      
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_RD1>BoolSignal" style="position: absolute; top:148px; left: 688px; height: 22px; width: 40px;" data-option="RelatedTags='Clinker02_B52ACP_RD1,Clinker02_B52ACP_OK,Clinker02_B52ACP_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_EZZ02_LM>BoolSignal" style="position: absolute; top:86px; left: 248px; height: 11px; width: 28px;" data-option="RelatedTags='Clinker02_EZZ02_LM',Display='0:lightBlueS,1:yellow'"></div>        
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ALP_RD>BoolSignal" style="position: absolute; top:130px; left: 632px; height: 17px; width: 47px;" data-option="RelatedTags='Clinker02_A1ALC_FT',Display='0:whiteS,1:yellowS'"></div>        
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ALP_OK>BoolSignal" style="position: absolute; top:148px; left: 632px; height: 17px; width: 47px;" data-option="RelatedTags='Clinker02_A1ALC_FT',Display='0:whiteS,1greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20ALP_RD>BoolSignal" style="position: absolute; top:153px; left: 189px; height: 11px; width: 31px;" data-option="RelatedTags='Clinker02_B20ALP_RD',Display='0:whiteS,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20ALP_OK>BoolSignal" style="position: absolute; top:165px; left: 189px; height: 11px; width: 31px;" data-option="RelatedTags='Clinker02_B20ALP_OK',Display='0:whiteS,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALP_OK>BoolSignal" style="position: absolute; top:355px; left: 459px; height: 12px; width: 41px;" data-option="RelatedTags='Clinker02_B49ALP_OK',Display='0:whiteS,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ACP_RD>BoolSignal" style="position: absolute; top:299px; left: 453px; height: 28px; width: 42px;" data-option="RelatedTags='Clinker02_B49ACP_RD,Clinker02_B49ACP_OK,Clinker02_B49ACP_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49ALP_RD>BoolSignal" style="position: absolute; top:370px; left: 459px; height: 12px; width: 41px;" data-option="RelatedTags='Clinker02_B49ALP_RD',Display='0:whiteS,1:yellowS'"></div>   
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_Q2ALC2_RD1>BoolSignal" style="position: absolute; top:439px; left: 106px; height: 25px; width: 19px;" data-option="RelatedTags='Clinker02_Q2ALC2_RD1,Clinker02_Q2ALC2_RN,Clinker02_Q2ALC2_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BG4_RD>BoolSignal" style="position: absolute; top:562px; left: 490px; height: 17px; width: 49px;" data-option="RelatedTags='Clinker02_BG4_RD,Clinker02_BG4_RN,Clinker02_BG42_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_LALM>BoolSignal" style="position: absolute; top:670px; left: 328px; height: 21px; width: 50px;" data-option="RelatedTags='Clinker02_A4M_LALM',Display='0:grayS,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_LALM>BoolSignal" style="position: absolute; top:692px; left: 328px; height: 21px; width: 50px;" data-option="RelatedTags='Clinker02_A7M_LALM',Display='0:grayS,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_LALM>BoolSignal" style="position: absolute; top:714px; left: 328px; height: 21px; width: 50px;" data-option="RelatedTags='Clinker02_A5M_LALM',Display='0:grayS,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_LALM>BoolSignal" style="position: absolute; top:736px; left: 328px; height: 20px; width: 50px;" data-option="RelatedTags='Clinker02_A6M_LALM',Display='0:grayS,1:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_RD>BoolSignal" style="position: absolute; top:557px; left: 591px; height: 25px; width: 19px;" data-option="RelatedTags='Clinker02_B49M_RD,Clinker02_B49M_RN,Clinker02_B49M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48M1_RD>BoolSignal" style="position: absolute; top:536px; left: 604px; height: 12px; width: 19px;" data-option="RelatedTags='Clinker02_B48M1_RD,Clinker02_B48M1_RN,Clinker02_B48M1_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_FT>BoolSignal" style="position: absolute; top:433px; left: 508px; height: 12px; width: 19px;" data-option="RelatedTags='Clinker02_B50M_RN,Clinker02_B50M_RN,Clinker02_B50M__AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48M2_RD>BoolSignal" style="position: absolute; top:536px; left: 625px; height: 12px; width: 19px;" data-option="RelatedTags='Clinker02_B48M2_RD,Clinker02_B48M2_RN,Clinker02_B48M2_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>     
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48RE_RD>BoolSignal" style="position: absolute; top:601px; left: 590px; height: 17px; width: 27px;" data-option="RelatedTags='Clinker02_B48RE_RD,Clinker02_B48RE_RN,Clinker02_B48RE_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B12ALC_RD>BoolSignal" style="position: absolute; top:504px; left: 894px; height: 25px; width: 19px;" data-option="RelatedTags='Clinker02_B12ALC_RD1,Clinker02_B12ALC_RN,Clinker02_B12ALC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B7ALC_RN>BoolSignal" style="position: absolute; top:467px; left: 1042px; height: 25px; width: 19px;" data-option="RelatedTags='Clinker02_B7ALC_RD,Clinker02_B7ALC_RN,Clinker02_B7ALC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B6ALC_AM>BoolSignal" style="position: absolute; top:467px; left: 1179px; height: 22px; width: 18px;" data-option="RelatedTags='Clinker02_B6ALC_RD,Clinker02_B6ALC_RN,Clinker02_B6ALC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B1ALC_RD>BoolSignal" style="position: absolute; top:510px; left: 1395px; height: 25px; width: 19px;" data-option="RelatedTags='Clinker02_B1ALC_RD,Clinker02_B1ALC_RN,Clinker02_B1ALC_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B64M_RD>BoolSignal" style="position: absolute; top:288px; left: 1310px; height: 15px; width: 27px;" data-option="RelatedTags='Clinker02_B64M_RD,Clinker02_B64M_RN,Clinker02_B64M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B63M_RD>BoolSignal" style="position: absolute; top:342px; left: 1310px; height: 15px; width: 27px;" data-option="RelatedTags='Clinker02_B63M_RD,Clinker02_B63M_RN,Clinker02_B63M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B62M_RD>BoolSignal" style="position: absolute; top:396px; left: 1310px; height: 15px; width: 27px;" data-option="RelatedTags='Clinker02_B62M_RD,Clinker02_B62M_RN,Clinker02_B62M_AM',Display='000:lightBlueS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ03_LM>BoolSignal" style="position: absolute; top:430px; left: 1013px; height: 11px; width: 28px;" data-option="RelatedTags='Clinker02_BZZ03_LM',Display='0:lightBlueS,1:greenS'"></div>
      <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ04_LM>BoolSignal" style="position: absolute; top:310px; left: 785px; height: 21px; width: 11px;" data-option="RelatedTags='Clinker02_BZZ04_LM',Display='0:lightBlueS,1:greenS'"></div>
     <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ05_LM>BoolSignal" style="position: absolute; top:184px; left: 917px; height: 21px; width: 11px;" data-option="RelatedTags='Clinker02_BZZ05_LM',Display='0:lightBlueS,1:greenS'"></div>
     <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ01_LM>BoolSignal" style="position: absolute; top:290px; left: 918px; height: 21px; width: 11px;" data-option="RelatedTags='Clinker02_BZZ01_LM',Display='0:lightBlueS,1:greenS'"></div>
     <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ02_LM>BoolSignal" style="position: absolute; top:308px; left: 980px; height: 21px; width: 11px;" data-option="RelatedTags='Clinker02_BZZ02_LM',Display='0:lightBlueS,1:greenS'"></div>
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59AC_SEL>BoolSignal" style="position: absolute; top:336px; left: 1375px; height: 10px; width: 26px; bottom: 409px;" data-option="RelatedTags='Clinker02_B59AC_SEL',Display='0:lightBlueS,1:greenS'"></div>        
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59AC>BoolSignal" style="position: absolute; top:392px; left: 1375px; height: 10px; width: 26px;" data-option="RelatedTags='Clinker02_B59AC_SEL',Display='0:lightBlueS,1:greenS'"></div>        
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B17M_SEL>BoolSignal" style="position: absolute; top:298px; left: 1105px; height: 10px; width: 26px;" data-option="RelatedTags='Clinker02_B17M_SEL',Display='0:lightBlueS,1:greenS'"></div>        
    <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B17M>BoolSignal" style="position: absolute; top:298px; left: 1132px; height: 10px; width: 26px;" data-option="RelatedTags='Clinker02_B17M_SEL',Display='0:yellowS,1:lightBlueS'"></div>        


        <%--模拟量--%>
        <%--各库下百分比--%>
       <%-- 时间--%>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BHSB_TIME>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 57px; left: 73px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1355px;"></div>--%>
       <%-- 时间--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B20M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 124px; left: 162px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1261px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ07_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 102px; left: 226px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1202px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT08_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 73px; left: 291px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1137px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 38px; left: 421px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1007px; bottom: 742px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B41AC_VOT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 52px; display: block; top: 73px; left: 541px; position: absolute; color: #4cff00; text-align: right; height: 17px; right: 887px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_EA01_A_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:52px; display:block; top: 104px; left: 561px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 867px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE39_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:29px; display:block; top: 157px; left: 88px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1362px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE40_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:29px; display:block; top: 178px; left: 88px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1361px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE41_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:29px; display:block; top: 200px; left: 88px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1362px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE37_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:29px; display:block; top: 223px; left: 88px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1364px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE42_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 156px; left: 124px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1324px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE43_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 179px; left: 124px; position:absolute;color: #4cff00;text-align:right; height: 17px; "></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE44_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 200px; left: 124px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1327px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE38_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 223px; left: 124px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1328px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE45_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:39px; display:block; top: 200px; left: 193px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1259px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE46_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:39px; display:block; top: 224px; left: 194px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1259px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B29AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:35px; display:block; top: 245px; left: 305px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1140px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A13M_CUN_A>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 443px; left: 184px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1255px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:95px; display:block; top: 570px; left: 171px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 1214px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT01_L_M>DCS'" data-option="Alarm='HH,H,LL,L',Range='Max,Min'"style="width:38px; display:block; top: 517px; left: 195px; position:absolute;color:blue;text-align:right; height: 17px; right: 1247px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_ZFLJL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 95px; display: block; top: 589px; left: 171px; position: absolute; color: #4cff00; text-align: right; height: 16px; right: 1214px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:48px; display:block; top: 579px; left: 490px; position:absolute;color:blue;text-align:right; height: 20px; "></div>
        <%--时间--%>
        <%--<div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B21M_TIME>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:71px; display:block; top: 610px; left: 480px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 929px;"></div>--%>
        <%--时间--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_TOTAL_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 628px; left: 78px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1346px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AFEED_TOTF>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:58px; display:block; top: 628px; left: 196px; position:absolute;color: #4cff00;text-align:right; height: 18px; right: 1226px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_RAT888>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 626px; left: 329px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 1104px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AFEED_TOLLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:71px; display:block; top: 628px; left: 451px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 958px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 56px; display: block; top: 669px; left: 78px; position: absolute; color: #4cff00; text-align: right; height: 21px; right: 1345px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 669px; left: 136px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1285px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 669px;left: 199px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1225px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; top: 669px; left: 261px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1157px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 669px; left: 401px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1005px;"></div>
         <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_ALT01_L_M>DCS"  style="width:47px; display:block; top: 669px;left: 477px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 957px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 691px; left: 78px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1346px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 692px; left: 136px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1287px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 692px; left: 199px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1225px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; top: 692px; left: 261px; position:absolute;color: #4cff00;text-align:right; height: 21px;right: 1157px; "></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 693px; left: 401px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1005px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT02_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 692px; left: 477px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 957px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 711px; left: 78px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1346px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 713px; left: 136px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1285px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 713px; left: 199px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1223px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; top: 714px; left: 261px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 1157px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 714px; left: 401px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 1006px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT04_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 713px; left: 477px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 957px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZG_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 735px; left: 78px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1346px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AQCX_SP4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 735px; left: 136px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1287px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 735px; left: 199px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1225px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; top: 735px; left: 261px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 1157px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZFLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 736px; left: 401px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 1006px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ALT03_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 735px; left: 477px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 957px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ06_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 102px; left: 963px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 468px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT05_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 77px; left: 1213px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 218px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT04_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 104px; left: 1213px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 218px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE35_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 193px; left: 823px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 608px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE36_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 219px; left: 824px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 607px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ05_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:36px; display:block; top: 186px; left: 932px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 512px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT06_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 228px; left: 1015px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 414px; bottom: 515px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 250px; left: 1015px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 413px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ09_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:44px; display:block; top: 228px; left: 1185px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 251px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BFT04_LW_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:43px; display:block; top: 199px; left: 1285px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 152px; bottom: 544px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT11_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 217px; left: 1285px; position: absolute; color: #4cff00; text-align: right; height: 16px; right: 151px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BFT03_LW_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 273px; left: 1335px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 96px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT09_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 298px; left: 1331px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 100px;"></div>

       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 258px; left: 690px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 734px; bottom: 481px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_CUN_A_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 287px; left: 690px; position:absolute;color: #4cff00;text-align:right; height: 20px; right: 735px; bottom: 453px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B52ACP_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 311px; left: 690px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 743px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ04_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 313px; left: 800px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 631px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 313px; left: 869px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 562px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ02_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:36px; display:block; top: 308px; left: 998px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 445px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 341px; left: 869px; position:absolute;color: #4cff00;text-align:right; height: 20px; right: 562px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 371px; left: 721px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 710px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_BTT03_T_M>DCS'" style="width:49px; display:block; top: 348px; left: 721px; position:absolute; right: 710px; bottom: 396px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 412px; left: 600px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 825px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 431px; left: 600px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 825px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 458px; left: 557px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 874px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B50M_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:49px; display:block; top: 478px; left: 557px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 874px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BPT01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 613px; left: 630px; position:absolute;color: #4cff00;text-align:right; height: 18px; right: 792px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 632px; left: 630px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 793px;"></div>
              
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B10M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 479px; left: 965px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 458px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 410px; left: 988px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 435px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B4M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 401px; left: 1188px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 235px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BZZ08_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:39px; display:block; top: 424px; left: 1278px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 163px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B59M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 420px; left: 1376px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 47px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B60M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 365px; left: 1375px; position:absolute;color: #4cff00;text-align:right; height: 16px; right: 48px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BLT02_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 463px; left: 1347px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 91px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BLT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 625px; left: 1356px; position:absolute;color: blue;text-align:right; height: 17px; right: 82px;"></div>

      
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE17_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:32px; display:block; top: 669px; left: 907px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 538px;"></div>
       <%--时间--%>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B48M_TIME>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 668px; left: 602px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 821px;"></div>--%>
       <%--时间--%>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 690px; left: 604px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 820px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_SZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 713px; left: 604px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 818px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_CZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:57px; display:block; top: 735px; left: 604px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 819px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE09_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 669px; left: 773px; position:absolute;color: #4cff00;text-align:right; height: 18px; right: 675px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE11_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 689px; left: 773px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 675px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE13_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 715px; left: 773px; position:absolute;color: #4cff00;text-align:right; height: 18px; right: 675px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 737px; left: 773px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 675px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE10_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:32px; display:block; top: 669px; left: 812px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 638px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE12_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:32px; display:block; top: 689px; left: 812px; position:absolute;color: #4cff00;text-align:right; height: 20px; right: 638px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE14_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:32px; display:block; top: 715px; left: 812px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 638px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE08_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:32px; display:block; top: 737px; left: 812px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 638px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE15_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:31px; display:block; top: 669px; left: 871px; position:absolute;color: #4cff00;text-align:right; height: 20px; right: 579px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE18_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:31px; display:block; top: 691px; left: 871px; position:absolute;color: #4cff00;text-align:right; height: 20px; right: 579px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE16_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:31px; display:block; top: 713px; left: 871px; position:absolute;color: #4cff00;text-align:right; height: 20px; right: 579px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE19_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:31px; display:block; top: 735px; left: 871px; position:absolute;color: #4cff00;text-align:right; height: 20px; right: 579px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 691px; left: 907px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 530px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 716px; left: 907px; position:absolute;color: #4cff00;text-align:right; height: 17px; right: 531px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 735px; left: 907px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 531px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:39px; display:block; top: 690px; left: 979px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 460px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:39px; display:block; top: 714px; left: 979px; position:absolute;color: #4cff00;text-align:right; height: 21px; right: 461px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BP03_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:39px; display:block; top: 736px; left: 979px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 462px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE29_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 671px; left: 1152px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 287px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE31_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 692px; left: 1152px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 288px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE33_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 714px; left: 1152px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 286px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE27_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 736px; left: 1152px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 288px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE30_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 671px; left: 1196px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 244px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE32_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 693px; left: 1196px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 244px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE34_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 715px; left: 1196px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 244px;"></div>
       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BTE28_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 736px; left: 1196px; position:absolute;color: #4cff00;text-align:right; height: 19px; right: 244px;"></div>
        
         <%--汉字隐藏--%>

         <%--汉字隐藏--%>
        <div id="zc_nxjc_qtx_efc>Clinker02_B22M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 136px; left: 225px; color:red; text-align: center; height: 15px; right: 1124px; bottom: 609px;">袋收尘1#星型下料器故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B24M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 156px; left: 226px; color:red; text-align: center; height: 15px; right: 1123px; bottom: 589px;">袋收尘1#拉链机器故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B20ALP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 184px; left: 178px; color:yellow; text-align: center; height: 12px; right: 1258px; bottom: 564px;">允许起动</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B23M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 199px; left: 228px; color:red; text-align: center; height: 15px; right: 1121px; bottom: 546px;">袋收尘2#星型下料器故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B25M_RN>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 217px; left: 228px; color:red; text-align: center; height: 15px; right: 1121px; bottom: 528px;">袋收尘2#拉链机器故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 278px; left: 30px; color:red; text-align: center; height: 15px; right: 1370px; bottom: 467px;">一度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 298px; left: 7px; color:red; text-align: center; height: 15px; right: 1403px; bottom: 449px;">速度报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_A3M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 298px; left: 83px; color:red; text-align: center; height: 15px; right: 1339px; bottom: 447px;">二度跑偏</div>

        <div id="zc_nxjc_qtx_efc>Clinker02_B55M_ES1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 351px; left: 213px; color:red; text-align: center; height: 14px; right: 1187px; bottom: 395px;">一度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B55M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 372px; left: 215px; color:red; text-align: center; height: 12px; right: 1190px; bottom: 376px;">二度跑偏</div>

        <div id="zc_nxjc_qtx_efc>Clinker02_A13M_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 555px; left: 92px; color:red; text-align: center; height: 15px; right: 1308px; bottom: 190px;">一度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_A13M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 555px; left: 9px; color:red; text-align: center; height: 15px; right: 1392px; bottom: 190px;">速度报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_A13M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 579px; left: 10px; color:red; text-align: center; height: 15px; right: 1412px; bottom: 166px;">二度跑偏</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_Q2ALC2_AUTO>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size:16px; top: 440px; left: 138px; color:yellow; text-align: center; height: 31px; right: 1319px; bottom: 326px;">现场</div>

        <div id="zc_nxjc_qtx_efc>Clinker02_B55M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 474px; left: 306px; color:red; text-align: center; height: 72px; right: 1164px; bottom: 214px;">速度报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_BG4_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 591px; left: 324px; color:red; text-align: center; height: 15px; right: 1086px; bottom: 154px;">立磨故障调停</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_BG4_FT2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 608px; left: 324px; color: red; text-align: center; height: 15px; right: 1088px; bottom: 137px;">立磨综合报警</div>

        <div id="zc_nxjc_qtx_efc>Clinker02_B52ALP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 166px; left: 603px; color:yellow; text-align: center; height: 15px; right: 809px; bottom: 616px;">允许起动</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B51ALC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 222px; left: 611px; color:yellow; text-align: center; height: 15px; right: 801px; bottom: 560px;">允许起动</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B49ACP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 335px; left: 440px; color:yellow; text-align: center; height: 15px; right: 972px; bottom: 447px;">允许进相</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B49ALP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 392px; left: 446px; color:yellow; text-align: center; height: 15px; right: 974px; bottom: 353px;">允许起动</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B49ALC2_LK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 319px; left: 538px; color:yellow; text-align: center; height: 15px; right: 874px; bottom: 463px;">允许起动</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_LK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 376px; left: 537px; color:yellow; text-align: center; height: 15px; right: 875px; bottom: 406px;">允许起动</div>

        <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_RN1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 0px; left: 731px; color: #4cff00; text-align: center; height: 15px; right: 701px; bottom: 593px; margin-top: 152px;">启动中</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 175px; left: 699px; color: #4cff00; text-align: center; height: 15px; right: 713px; bottom: 607px;">允许运行</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B52ACP_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 201px; left: 699px; color:red; text-align: center; height: 12px; right: 713px; bottom: 584px;">轻故障</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B49ALC1_YB1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 394px; left: 537px; color:red; text-align: center; height: 10px; right: 875px; bottom: 356px;">油站报警</div>

        <div id="zc_nxjc_qtx_efc>Clinker02_B10M_LVS>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 579px; left: 985px; color:red; text-align: center; height: 72px; right: 485px; bottom: 109px;">料位报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B4M_SS1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 10px; top: 491px; left: 1223px; color:red; text-align: center; height: 72px; right: 247px; bottom: 197px;">速度报警</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B4M_LVS>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 580px; left: 1223px; color:red; text-align: center; height: 72px; right: 247px; bottom: 145px;">料位报警</div>
        
        <div id="zc_nxjc_qtx_efc>Clinker02_B48M1_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 520px; left: 601px; color:yellow; text-align: center; height: 11px; right: 869px; bottom: 229px;">合</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B48M1_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 520px; left: 630px; color:yellow; text-align: center; height: 11px; right: 840px; bottom: 228px;">分</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B64M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 276px; left: 1309px; color:yellow; text-align: center; height: 11px; right: 161px; bottom: 510px;">开</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B64M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 276px; left: 1322px; color:yellow; text-align: center; height: 11px; right: 148px; bottom: 510px;">关</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B63M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 328px; left: 1311px; color:yellow; text-align: center; height: 11px; right: 159px; bottom: 458px;">开</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B63M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 327px; left: 1327px; color:yellow; text-align: center; height: 11px; right: 143px; bottom: 459px;">关</div>             
        <div id="zc_nxjc_qtx_efc>Clinker02_B62M_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 379px; left: 1307px; color:yellow; text-align: center; height: 11px; right: 163px; bottom: 407px;">开</div>
        <div id="zc_nxjc_qtx_efc>Clinker02_B62M_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 379px; left: 1324px; color:yellow; text-align: center; height: 11px; right: 146px; bottom: 407px;">关</div> 
         <%--棒图--%>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_tys>Clinker02_B62M_LMF>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:19px; height:31px; position:absolute; top: 445px; left: 1325px;"></div>
        <div class="BarGraph mchart" id="zc_nxjc_qtx_tys>Clinker02_BLT01_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:13px; height:111px; position:absolute; top: 625px; left: 1431px;"></div>        
    </div>
</body>
</html>