<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_clinker02_sctj.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_clinker02_sctj" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>

    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc";
        publicData.sceneName = "青水公司2#窑系统生产情况统计";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
 <div id="ForeGround" style=" width: 1684px; height: 1017px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>

   <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_clinker02_sctj.png'); width: 1684px; height: 1017px; overflow: hidden; top: 0px; left: 0px;">
    <div id="ConnectionGround" style="width: 1684px; height: 1017px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
 <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1684px;height: 1017px;"></div>   
    <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div> 

    <%--贴标签处--%>>--%>
         <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B1LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1328px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B2LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1201px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B3LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1073px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_ZLJYAO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 933px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_LJYAO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 791px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_LJLMYAO>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 636px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_SLCLLJ2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 468px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YBQL2_RYSLJLYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 281px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YBQL2_RYSLLLLJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 140px; left: 1505px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 62px;"></div>

       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B3TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1238px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B2TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B1TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B1TMLD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_DAYTM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B1TMLM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F4ARC_YZJYLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B1TMLY>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F4ARC_YZJNLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 177px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 60px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_YBTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1236px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_BBTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_ZBTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_SRTSCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_BRTSCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_HZYSYTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_HZYBYTSCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_HZYSNTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_HZYBNTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 215px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 280px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B1LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1237px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B2LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B3LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_SLM_LLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_DAYLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_SLM_LMLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_SLM_MLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_SLM_LNCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_SLM_BNCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 258px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 62px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B1TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1237px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B2TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B3TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_LDYX>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_DAYTM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_SYYX>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_YXYLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_LNYX>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_YXNLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 299px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 61px;"></div>

       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B1TC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1238px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B2TC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_B3TC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_SLMSRTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_BRTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_SYTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_BYTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_SNTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_B49M_BNTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 341px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 61px;"></div>

       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_B1LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1236px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_B2LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_B3LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_MM_LDCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_DAYLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_MM_LYCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_MM_YCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_MM_LNCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_MM_NCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 381px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 60px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_B1TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1240px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_B2TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_B3TM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_LDYX>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_DAYTM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_LYYX>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_MMYLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_LNYX>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_MMNLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 420px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 61px;"></div>

               <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_ZBTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1236px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_BBTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1117px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_YBTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1000px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_SRTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_BRTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_SYTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_MM_BYTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_SNTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_K18M_BNTC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 458px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 61px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YBCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1236px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BBCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ZBCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_FDZL_SR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_FDZL_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_FDZL_SY>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_FDZL_BY>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_FDZL_SN>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_FDZL_BN>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 497px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 60px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YB_YXSJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1235px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_BB_YXSJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_ZB_YXSJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_YXSJ_SR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_YXSJ_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_YXSJ_SN>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_YXSJ_BY>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Clinker02_YR_YXSJ_SN>DCS'" style="width:117px; display:block; top: 536px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YR_YXSJ_BN>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 536px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 60px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1234px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_SR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_BR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_SY>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_BY>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_SN>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_DSLFDL_BN>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 575px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 61px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B1LJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1236px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B2LJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1090px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F5M_B3LJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_ZLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_TOL_MLM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_F45AC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YBQL2_RYSLLLLJLY>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YBQL2_RYSLLLLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 623px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 60px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMYL_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1233px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMYL_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMYL_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMF_LDCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMF_DCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMF_LYCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMF_YCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMF_LNCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YTMF_NCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 667px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 62px;"></div>

       <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMYL_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1236px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMYL_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMYL_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMF_LDCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMF_DCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMF_LYCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMF_YCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMF_LNCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_YWMF_NCL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 708px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 61px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1234px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_LLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_LLJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_LMLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_MLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_LNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A4M_BNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 754px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 61px;"></div>

         <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1234px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_LLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_LLJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_LMLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_MLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_LNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A7M_BNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 797px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 61px;"></div>
    
          <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1234px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_LLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_LLJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_LMLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_MLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_LNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A5M_BNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 841px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 61px;"></div>

         <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1234px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_LLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_LLJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_LMLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_MLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_LNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A6M_BNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 884px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 60px;"></div>

         <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_YB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1234px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_BB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_ZB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_LLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_LLJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_LMLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_MLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_LNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_A8M_BNYL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 932px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 60px;"></div>

        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALYBLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 239px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1234px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALBBLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 366px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALZBLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 494px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALSRLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 634px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALBRLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 776px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALSYLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 931px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALBYLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 1099px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALSNLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Clinker02_AS2_PALBNLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 981px; left: 1506px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 61px;"></div>


    </div>
</body>
</html>
