<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_klqc_klqf_clinker01_yaotoubilengji.aspx.cs" Inherits="Monitor_klqc.web.UI_Monitor.DCSMonitor.zc_nxjc_klqc_klqf.zc_nxjc_klqc_klqf_clinker01_yaotoubilengji" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>  
<script>
    publicData.organizationId = "zc_nxjc_klqc_klqf_clinker01";
    publicData.sceneName = "烧成窑头篦冷机";
</script>
</head>
<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style="width: 1481px; height:722px; margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('/UI_Monitor/images/page/DCS/zc_nxjc_klqc_klqf/zc_nxjc_klqc_klqf_clinker01_yaotoubilengji.png'); width: 1481px; height: 722px; overflow: hidden;">
     <div id="ConnectionGround" style="width: 1481px; height: 7722px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
   <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1557px;height: 807px;"></div>   
        <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div> 
        <%--标签粘贴处--%>
      <%--  <button onclick="CheckTags()">检查标签</button>--%>
 <%--贴标签处--%>
        <%--马海峰--%>
        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YTZ_T>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 149px; left: 125px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5701P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 166px; left: 125px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702a11_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 250px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702a12_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 271px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702a13_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 290px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702a14_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 313px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702a15_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 331px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 278px; left: 187px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 278px; left: 251px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 278px; left: 310px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 314px; left: 187px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T05>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 314px; left: 253px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 314px; left: 313px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d13_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 305px; left: 393px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d14_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 324px; left: 393px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d15_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 341px; left: 393px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GPGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 260px; left: 429px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702b11_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 372px; left: 441px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702b12_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 394px; left: 441px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702b13_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 415px; left: 441px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d11_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 314px; left: 567px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d12_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 338px; left: 567px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702d02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 314px; left: 636px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702d03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 338px; left: 636px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_LT_5702L01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 376px; left: 674px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_M5702dT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 238px; left: 373px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 15px; left: 332px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 35px; left: 332px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 55px; left: 332px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 15px; left: 427px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 35px; left: 427px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 55px; left: 427px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5706P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 186px; left: 366px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702g1_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 112px; left: 529px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702g2_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 112px; left: 635px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 237px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 252px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 268px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 287px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702T07>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 245px; left: 729px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5716Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 209px; left: 750px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_EDGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 314px; left: 727px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SD_FK2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 337px; left: 727px; position: absolute; color:#4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_LFG_P>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 391px; left: 901px; position: absolute; color:#4cff00; text-align: right; height: 16px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_6501_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 453px; left: 1310px; position: absolute; color:#4cff00; text-align: right; height: 16px;"></div>        
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 45px; display: block; top: 43px; left: 848px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5717P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 45px; display: block; top: 63px; left: 848px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5719P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 45px; display: block; top: 52px; left: 995px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T04_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 45px; display: block; top: 71px; left: 995px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5718Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 108px; left: 978px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5719P01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 11px; left: 1114px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5721aZ01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 79px; left: 1228px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_AH5_57E_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 119px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5721T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 139px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5721MT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 158px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5721MT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 178px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 92px; left: 1058px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 92px; left: 1165px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_XT_5722X01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 120px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 140px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 160px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_R1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 177px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_5721VT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 311px; left: 1289px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_5721VT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 327px; left: 1289px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YXWD_TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 544px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px; bottom: 168px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 561px;left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px; right: 545px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 577px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 595px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 611px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_GSD_1>DCS'" style="width: 39px; display: block; top: 627px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_GSD_2>DCS'" style="width: 39px; display: block; top: 643px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_GSD_3>DCS'" style="width: 39px; display: block; top: 544px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_GSD_4>DCS'" style="width: 39px; display: block; top: 561px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px; right: 395px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YWG_TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'"style="width: 39px; display: block; top: 577px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_YDGD>DCS'" style="width: 39px; display: block; top: 643px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_SD_FK2>DCS'" style="width: 39px; display: block; top: 595px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_EDGD>DCS'" style="width: 39px; display: block; top: 643px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
         <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_SD_FK>DCS'" style="width: 39px; display: block; top: 595px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M1_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 611px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M2_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 627px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M3_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 544px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M4_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 561px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YWG_TT2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 577px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M1_PP2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 611px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M2_PP2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 627px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px; bottom: 87px;font-size:10px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 137px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5708F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 137px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5708T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 137px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 222px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5709F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 222px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5709T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 222px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 306px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5710F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 306px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5710T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 306px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5711F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5711T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
    
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P05>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 472px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5712F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 472px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5712T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 472px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 553px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5713F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 553px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5713T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 553px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P07>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 638px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5714F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 638px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5714T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 638px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P08>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 720px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5715F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 720px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5715T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 513px; left: 720px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
           <%-- 查--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5708Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 613px; left: 102px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5709Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 613px; left: 191px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5710Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 613px; left: 276px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 601px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 619px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 637px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 601px; left: 476px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 619px; left: 476px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 637px; left: 476px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 601px; left: 559px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 619px; left: 559px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 637px; left: 559px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 601px; left: 643px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 619px; left: 643px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 637px; left: 643px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 601px; left: 725px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 619px; left: 725px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 637px; left: 725px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_08_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 656px; left: 142px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5709MT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 640px; left: 223px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5709MT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 660px; left: 223px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_AH3_57E_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 679px; left: 223px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5710MT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 640px; left: 305px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5710MT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 660px; left: 305px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_AH4_57E_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 679px; left: 305px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SD_FK>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 347px; left: 183px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YDGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 366px; left: 183px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_6600L01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 618px; left: 1352px; position: absolute; color: blue; text-align: right; height: 14px;"></div>
        <%--开关量--%>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_57_02e_RN>BoolSignal" style="position: absolute; top: 231px; left: 275px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_SCP_57_02e_RD,dcs01_SCP_57_02e_RN,dcs01_SCP_57_02e_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_1_RD>BoolSignal" style="position: absolute; top: 244px; left: 152px; height: 18px; width: 23px; bottom: 460px;" data-option="RelatedTags='dcs01_M57_2a1_1_RD,dcs01_M57_2a1_1_RN,dcs01_M57_2a1_1_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_2_RD>BoolSignal" style="position: absolute; top: 268px; left: 152px; height: 18px; width: 23px;" data-option="RelatedTags='dcs01_M57_2a1_2_RD,dcs01_M57_2a1_2_RN,dcs01_M57_2a1_2_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_3_RD>BoolSignal" style="position: absolute; top: 291px; left: 152px; height: 18px; width: 23px;" data-option="RelatedTags='dcs01_M57_2a1_3_RD,dcs01_M57_2a1_3_RN,dcs01_M57_2a1_3_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_4_RD>BoolSignal" style="position: absolute; top: 315px; left: 152px; height: 18px; width: 23px; bottom: 389px;" data-option="RelatedTags='dcs01_M57_2a1_4_RD,dcs01_M57_2a1_4_RN,dcs01_M57_2a1_4_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_5_RD>BoolSignal" style="position: absolute; top: 337px; left: 152px; height: 18px; width: 23px;" data-option="RelatedTags='dcs01_M57_2a1_5_RD,dcs01_M57_2a1_5_RN,dcs01_M57_2a1_5_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_BLJ_RD>BoolSignal" style="position: absolute; top: 373px; left: 301px; height: 24px; width: 15px;" data-option="RelatedTags='dcs01_BLJ_RD,dcs01_BLJ_RN,dcs01_BLJ_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_57_26_RD>BoolSignal" style="position: absolute; top: 432px; left: 18px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_SCP_57_26_RD,dcs01_SCP_57_26_RN,dcs01_SCP_57_26_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a3_RD>BoolSignal" style="position: absolute; top: 358px; left: 123px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_M57_2a3_RD,dcs01_M57_2a3_RN,dcs01_M57_2a3_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d3_RD>BoolSignal" style="position: absolute; top: 359px; left: 415px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_M57_2d3_RD,dcs01_M57_2d3_RN,dcs01_M57_2d3_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_9EE_RD>BoolSignal" style="position: absolute; top: 532px; left: 244px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_M57_9EE_RD,dcs01_M57_9EE_RN,dcs01_M57_9EE_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_10EE_RD>BoolSignal" style="position: absolute; top: 532px; left: 325px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_M57_10EE_RD,dcs01_M57_10EE_RN,dcs01_M57_10EE_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b3_RD>BoolSignal" style="position: absolute; top: 363px; left: 589px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_M57_2b3_RD,dcs01_M57_2b3_RN,dcs01_M57_2b3_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_21EE_RD>BoolSignal" style="position: absolute; top: 264px; left: 1334px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_M57_21EE_RD,dcs01_M57_21EE_RN,dcs01_M57_21EE_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_RD>BoolSignal" style="position: absolute; top: 269px; left: 1403px; height: 21px; width: 12px;" data-option="RelatedTags='dcs01_M_57_21HAV_RD,dcs01_M_57_21HAV_RN,dcs01_M_57_21HAV_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>        
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_BLJ2_RD>BoolSignal" style="position: absolute; top: 316px; left: 826px; height: 27px; width: 16px;" data-option="RelatedTags='dcs01_BLJ2_RD,dcs01_BLJ2_RN,dcs01_BLJ2_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GPKZG_RD>BoolSignal" style="position: absolute; top: 270px; left: 513px; height: 29px; width: 19px;" data-option="RelatedTags='dcs01_GPKZG_RD,dcs01_GPKZG_RN,dcs01_GPKZG_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_02e_RD>BoolSignal" style="position: absolute; top: 399px; left: 790px; height: 29px; width: 19px;" data-option="RelatedTags='dcs01_M57_02e_RD,dcs01_M57_02e_RN',Display='00:yellowS,01:redS,10:greenS,11:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b1_1_RD>BoolSignal" style="position: absolute; top: 377px; left: 559px; height: 15px; width: 23px;" data-option="RelatedTags='dcs01_M57_2b1_1_RD,dcs01_M57_2b1_1_RN,dcs01_M57_2b1_1_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b1_2_RD>BoolSignal" style="position: absolute; top: 399px; left: 559px; height: 15px; width: 23px;" data-option="RelatedTags='dcs01_M57_2b1_2_RD,dcs01_M57_2b1_2_RN,dcs01_M57_2b1_2_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b1_3_RD>BoolSignal" style="position: absolute; top: 419px; left: 559px; height: 15px; width: 23px; right: 898px;" data-option="RelatedTags='dcs01_M57_2b1_3_RD,dcs01_M57_2b1_3_RN,dcs01_M57_2b1_3_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_57_02e_RD>BoolSignal" style="position: absolute; top: 231px; left: 275px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_SCP_57_02e_RD,dcs01_SCP_57_02e_RN,dcs01_SCP_57_02e_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>--%>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a2_RD>BoolSignal" style="position: absolute; top: 378px; left: 80px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2a2_RD,dcs01_M57_2a2_RN,dcs01_M57_2a2_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d2_RD>BoolSignal" style="position: absolute; top: 350px; left: 335px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d2_RD,dcs01_M57_2d2_RN,dcs01_M57_2d2_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d1_4_RD>BoolSignal" style="position: absolute; top: 331px; left: 473px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d1_4_RD,dcs01_M57_2d1_4_RN,dcs01_M57_2d1_4_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d1_3_RD>BoolSignal" style="position: absolute; top: 330px; left: 502px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d1_3_RD,dcs01_M57_2d1_3_RN,dcs01_M57_2d1_3_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d1_2_RD>BoolSignal" style="position: absolute; top: 330px; left: 529px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d1_2_RD,dcs01_M57_2d1_2_RN,dcs01_M57_2d1_2_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b2_RD>BoolSignal" style="position: absolute; top: 225px; left: 490px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2b2_RD,dcs01_M57_2b2_RN,dcs01_M57_2b2_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M714_V01_RD>BoolSignal" style="position: absolute; top: 187px; left: 532px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M714_V01_RD,dcs01_M714_V01_RN,dcs01_M714_V01_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_BP_RD>BoolSignal" style="position: absolute; top: 87px; left: 377px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_4_BP_RD,dcs01_M57_4_BP_RN,dcs01_M57_4_BP_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_BP_RD>BoolSignal" style="position: absolute; top: 87px; left: 440px; height: 22px; width: 24px; right: 1017px;" data-option="RelatedTags='dcs01_M57_5_BP_RD,dcs01_M57_5_BP_RN,dcs01_M57_5_BP_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2g1_RD>BoolSignal" style="position: absolute; top: 87px; left: 586px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2g1_RD,dcs01_M57_2g1_RN,dcs01_M57_2g1_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2g2_RD>BoolSignal" style="position: absolute; top: 87px; left: 633px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2g2_RD,dcs01_M57_2g2_RN,dcs01_M57_2g2_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_8_RD>BoolSignal" style="position: absolute; top: 572px; left: 182px; height: 22px; width: 24px; right: 1275px;" data-option="RelatedTags='dcs01_M57_8_RD,dcs01_M57_8_RN,dcs01_M57_8_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_09_RD>BoolSignal" style="position: absolute; top: 572px; height: 22px; width: 24px; right: 1190px;" data-option="RelatedTags='dcs01_M_57_09_RD,dcs01_M_57_09_HZ,dcs01_M_57_09_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_10_RD>BoolSignal" style="position: absolute; top: 572px; height: 22px; width: 24px; left: 346px;" data-option="RelatedTags='dcs01_M_57_10_RD,dcs01_M_57_10_HZ,dcs01_M_57_10_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 429px; height: 22px; width: 24px; right: 1028px;" data-option="RelatedTags='dcs01_M57_11_BP_RD,dcs01_M57_11_BP_RN,dcs01_M57_11_BP_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 511px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_12_BP_RD,dcs01_M57_12_BP_RN,dcs01_M57_12_BP_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 596px; height: 22px; width: 24px; right: 861px;" data-option="RelatedTags='dcs01_M57_13_BP_RD,dcs01_M57_13_BP_RN,dcs01_M57_13_BP_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 679px; height: 22px; width: 24px; right: 778px;" data-option="RelatedTags='dcs01_M57_14_BP_RD,dcs01_M57_14_BP_RN,dcs01_M57_14_BP_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 761px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_15_BP_RD,dcs01_M57_15_BP_RN,dcs01_M57_15_BP_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_77_7_RD>BoolSignal" style="position: absolute; top: 411px; left: 1369px; height: 17px; width: 18px;" data-option="RelatedTags='dcs01_SCP_77_7_RD,dcs01_SCP_77_7_RN,dcs01_SCP_77_7_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M77_8_RD>BoolSignal" style="position: absolute; top: 454px; left: 1405px; height: 13px; width: 14px;" data-option="RelatedTags='dcs01_M77_8_RD,dcs01_M77_8_RN,dcs01_M77_8_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21_RD>BoolSignal" style="position: absolute; top: 249px; left: 1361px; height: 31px; width: 32px;" data-option="RelatedTags='dcs01_M_57_21_RD,dcs01_M_57_21_HZ,dcs01_M_57_21_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_21f1_RD>BoolSignal" style="position: absolute; top: 288px; left: 1360px; height: 12px; width: 13px;" data-option="RelatedTags='dcs01_M57_21f1_RD,dcs01_M57_21f1_RN,dcs01_M57_21f1_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_21f2_RD>BoolSignal" style="position: absolute; top: 288px; left: 1380px; height: 12px; width: 13px;" data-option="RelatedTags='dcs01_M57_21f2_RD,dcs01_M57_21f2_RN,dcs01_M57_21f2_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5719AR_RD>BoolSignal" style="position: absolute; top: 63px; left: 1150px; height: 18px; width: 17px;" data-option="RelatedTags='dcs01_F_5719AR_RD,dcs01_F_5719AR_RN,dcs01_F_5719AR_ERR',Display='000:yellowCB,001:redCB,010:greenCB,011:redCB,100:yellowC,101:redCB,110:greenC,111:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_6_RD>BoolSignal" style="position: absolute; top: 128px; left: 378px; height: 45px; width: 13px;" data-option="RelatedTags='dcs01_M57_6_RD,dcs01_M57_6_RN,dcs01_M57_6_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_7_RD>BoolSignal" style="position: absolute; top: 128px; left: 440px; height: 45px; width: 13px;" data-option="RelatedTags='dcs01_M57_7_RD,dcs01_M57_7_RN,dcs01_M57_7_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_20_RD>BoolSignal" style="position: absolute; top: 395px; left: 1270px; height: 18px; width: 17px;" data-option="RelatedTags='dcs01_M57_20_RD,dcs01_M57_20_RN,dcs01_M57_20_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M65_1_RD>BoolSignal" style="position: absolute; top: 474px; left: 1341px; height: 13px; width: 23px;" data-option="RelatedTags='dcs01_M65_1_RD,dcs01_M65_1_RN,dcs01_M65_1_ERR',Display='000:yellowS,001:redS,010:greenS,011:redS,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <%--汉字隐藏--%>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_8_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 561px; left: 125px; color: red; text-align: center; height: 14px; right: 1323px; bottom: 147px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_57_26_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 410px; left: 13px; color: red; text-align: center; height: 14px; right: 1435px; bottom: 298px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_57_26_YK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 478px; left: 13px; color: red; text-align: center; height: 14px; right: 1414px; bottom: 224px;">远控手动</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_09_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 585px; left: 226px; color: red; text-align: center; height: 14px; right: 1222px; bottom: 126px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_10_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 585px; left: 306px; color: red; text-align: center; height: 14px; right: 1142px; bottom: 123px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_11_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 388px; color: red; text-align: center; height: 14px; right: 1060px; bottom: 131px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_12_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 471px; color: red; text-align: center; height: 14px; right: 977px; bottom: 134px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_13_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 555px; color: red; text-align: center; height: 14px; right: 893px; bottom: 133px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_14_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 639px; color: red; text-align: center; height: 14px; right: 816px; bottom: 131px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_15_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 722px; color: red; text-align: center; height: 14px; right: 726px; bottom: 134px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_09_ALM>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 559px; left: 226px; color: red; text-align: center; height: 14px; right: 1223px; bottom: 149px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_10_ALM>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 560px; left: 306px; color: red; text-align: center; height: 14px; right: 1143px; bottom: 148px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_BLJ_GZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 416px; left: 293px; color: red; text-align: center; height: 14px; right: 1155px; bottom: 292px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_8_WB>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 115px; color: #4cff00; text-align: center; height: 14px; right: 1312px; bottom: 131px;">软起完毕</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_8_PL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 597px; left: 115px; color: #4cff00; text-align: center; height: 14px; bottom: 111px;">软起旁路</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5708Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 597px; left: 190px; color: #4cff00; text-align: center; height: 13px; right: 1260px; bottom: 111px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5709Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 597px; left: 273px; color: #4cff00; text-align: center; height: 13px; right: 1174px; bottom: 111px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5710Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 597px; left: 354px; color: #4cff00; text-align: center; height: 13px; right: 1097px; bottom: 111px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5708Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 631px; left: 190px; color: #4cff00; text-align: center; height: 14px; right: 1260px; bottom: 77px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5709Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 631px; left: 273px; color: #4cff00; text-align: center; height: 14px; right: 1174px; bottom: 77px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5710Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 631px; left: 354px; color: #4cff00; text-align: center; height: 14px; right: 1097px; bottom: 77px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_4_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 99px; left: 321px; color: red; text-align: center; height: 14px; right: 1127px; bottom: 609px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_5_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 99px; left: 483px; color: red; text-align: center; height: 14px; right: 965px; bottom: 609px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_57_02e_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 245px; left: 309px; color: red; text-align: center; height: 14px; right: 1139px; bottom: 463px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_02e_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 817px; color: red; text-align: center; height: 14px; right: 631px; bottom: 305px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_BLJ2_GZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 358px; left: 817px; color: red; text-align: center; height: 14px; right: 634px; bottom: 350px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_6_LIM1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 13px; top: 132px; left: 323px; color: #4cff00; text-align: center; height: 14px; right: 1105px; bottom: 575px;">正限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_6_LIM2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 13px; top: 157px; left: 323px; color: #4cff00; text-align: center; height: 14px; right: 1105px; bottom: 550px;">反限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_7_LIM1>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 13px; top: 132px; left: 461px; color: #4cff00; text-align: center; height: 14px; right: 967px; bottom: 575px;">正限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_7_LIM2>DCS" class="TextDisplay" data-option="Display='0'" style="position: absolute; font-size: 13px; top: 157px; left: 461px; color: #4cff00; text-align: center; height: 14px; right: 967px; bottom: 550px;">反限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5716Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 190px; left: 810px; color: #4cff00; text-align: center; height: 14px; right: 634px; bottom: 518px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5716Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 239px; left: 810px; color: #4cff00; text-align: center; height: 14px; right: 634px; bottom: 467px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5718Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 129px; left: 972px; color: #4cff00; text-align: center; height: 14px; right: 473px; bottom: 579px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5718Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 129px; left: 1035px; color: #4cff00; text-align: center; height: 14px; right: 405px; bottom: 579px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5721aZ01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 60px; left: 1218px; color: #4cff00; text-align: center; height: 14px; bottom: 648px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5721aZ01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 60px; left: 1278px; color: #4cff00; text-align: center; height: 14px; right: 163px; bottom: 650px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_20_SD>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 383px; left: 1171px; color: #4cff00; text-align: center; height: 14px; right: 245px; bottom: 323px;">速度开关</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_SD>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 474px; left: 1228px; color: #4cff00; text-align: center; height: 18px; right: 178px; bottom: 230px;">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_STB>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 202px; left: 1413px; color: #4cff00; text-align: left; height: 14px; right: 10px; bottom: 506px;">待机状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_GP>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 218px; left: 1413px; color: #4cff00; text-align: left; height: 14px; right: 13px; bottom: 490px;">工频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_BP>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1413px; color: #4cff00; text-align: left; height: 14px; right: 13px; bottom: 474px;">变频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_F_5719AR_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1177px; color: red; text-align: center; height: 14px; right: 271px; bottom: 658px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_F_5719AR_GW>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1177px; color: red; text-align: center; height: 14px; right: 271px; bottom: 638px;">高温</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_QFT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1413px; color: red; text-align: left; height: 14px; right: 12px; bottom: 564px;">轻故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_ZFT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1413px; color: red; text-align: left; height: 14px; right: 12px; bottom: 550px;">重故障</div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_M_57_21_FT>DCS'" style="position: absolute; font-size: 13px; left: 1413px; color: red; text-align: left; height: 14px; right: 11px; bottom: 536px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_BP_TC>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1413px; color: red; text-align: left; height: 14px; right: -10px; bottom: 522px;">变频器退出</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_LS>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1073px; color: red; text-align: center; height: 14px; right: 373px; bottom: 230px;">拉绳</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_PP1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1116px; color: red; text-align: center; height: 14px; right: 326px; bottom: 230px;">跑偏1</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_PP2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1159px; color: red; text-align: center; height: 14px; right: 281px; bottom: 230px;">跑偏2</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: left; height: 14px; right: 45px; bottom: 404px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMa1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: left; height: 14px; right: 21px; bottom: 385px;">振动A报警1</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMa2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: left; height: 14px; right: 21px; bottom: 366px;">振动A报警2</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMb1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: left; height: 14px; right: 21px; bottom: 348px;">振动B报警1</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMb2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: left; height: 14px; right: 21px; bottom: 325px;">振动B报警2</div>
    
    </div>
</body>
</html>
