<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_byc_byf_clinker01_ylm.aspx.cs" Inherits="Monitor_byc.web.UI_Monitor.DCSMonitor.zc_nxjc_byc_byf.zc_nxjc_byc_byf_clinker01_ylm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_byc_byf";
        publicData.sceneName = "1#原料磨";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style="width: 1480px; height:760px; margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_byc_byf/zc_nxjc_byc_byf_clinker01_ylm.png'); width: 1480px; height: 760px; overflow: hidden;">
      <div id="ConnectionGround" style="width: 1480px; height: 760px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
   <div id="TextGround"style="font-size:large;padding-left:500px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1480px;height: 760px;"></div>   
        <div id="Picture"style="position: absolute; top: 4px; left: 476px; height: 20px; width: 20px; background-size:100% auto"></div>  
          <%-- <button onclick="CheckTags()">检查标签</button>--%>
     <%--   贴标签处--%>
 <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A12AC_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 28px; left: 88px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_AnalogOut4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 46px; left: 88px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A12AC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 64px; left: 88px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A12AC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 82px; left: 88px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A12AC_ZF1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:55px; display:block; top: 99px; left: 80px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>       
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A11AC_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 28px; left: 143px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_AnalogOut2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 46px; left: 143px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A11AC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 64px; left: 143px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A11AC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 82px; left: 143px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A11AC_ZF1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:56px; display:block; top: 99px; left: 133px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A10AC_FF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:72px; display:block; top: 28px; left: 196px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_AnalogOut5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:72px; display:block; top: 46px; left: 196px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A10AC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:72px; display:block; top: 64px; left: 196px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A10AC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:72px; display:block; top: 82px; left: 196px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A10AC_FF1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:72px; display:block; top: 99px; left: 196px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>     
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A9AC_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 28px; left: 295px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_AnalogOut1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 46px; left: 295px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A9AC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 64px; left: 295px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A9AC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 82px; left: 295px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A9AC_ZF1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:64px; display:block; top: 99px; left: 277px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>       
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A_FF>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 28px; left: 377px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A_RAT2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 46px; left: 377px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A_RAT1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 64px; left: 377px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_AFEED_TOL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 82px; left: 377px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_A_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 99px; left: 348px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1P9AC_AI_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 35px; left: 537px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_2P9AC_AI_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 35px; left: 604px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_3P9AC_AI_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 35px; left: 669px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1P6M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 58px; left: 522px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_2P6M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 58px; left: 586px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_3P6M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 58px; left: 650px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_4P6M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 58px; left: 714px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_Q1M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 151px; left: 465px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X1M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 176px; left: 524px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X2M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 176px; left: 587px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X8ALP_QWD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 208px; left: 531px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X8ALP_HWD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 208px; left: 587px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_W13M_CUM_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 164px; left: 187px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B47M_CUN_MJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; top: 188px; left: 281px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B47M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:53px; display:block; top: 203px; left: 281px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B40M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 265px; left: 15px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B25AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 311px; left: 233px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B25M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 325px; left: 239px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE23_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 397px; left: 185px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE33_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 413px; left: 185px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE24_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 429px; left: 185px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BFT01_F_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 457px; left: 117px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 486px; left: 118px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BPT02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 506px; left: 117px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 548px; left: 115px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B42M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 579px; left: 1px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_V1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 549px; left: 151px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_V2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 565px; left: 154px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_V4_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 582px; left: 151px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_P1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 615px; left: 211px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_P3_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 630px; left: 211px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALCLM2_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 363px; left: 254px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALCLM6_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 379px; left: 254px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALCLM4_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 363px; left: 305px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALCLM8_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 379px; left: 305px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B33M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 373px; left: 386px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BPT012_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 449px; left: 285px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 457px; left: 399px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 587px; left: 288px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BLT01_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 418px; left: 471px; position:absolute;color:blue;text-align:center;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B45AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 450px; left: 513px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B45AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 466px; left: 513px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ10_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 489px; left: 574px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 662px; left: 1px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 699px; left: -7px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE08_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 732px; left: 12px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE06_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 662px; left: 57px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 681px; left: 31px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ZD1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 699px; left: 53px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE09_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 732px; left: 66px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE26_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 671px; left: 125px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE28_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 692px; left: 125px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE30_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 714px; left: 125px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE27_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 670px; left: 182px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE29_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 692px; left: 182px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE31_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 714px; left: 182px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE32_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 735px; left: 182px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_T2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 706px; left: 276px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_P2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 706px; left: 331px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_T1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:45px; display:block; top: 681px; left: 422px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ05_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 78px; left: 795px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ02_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 14px; left: 954px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 95px; left: 952px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 61px; left: 1039px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EPT01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 37px; left: 1118px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 51px; left: 1118px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 22px; left: 1301px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EPT02_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 8px; left: 1298px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_E14AC_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 89px; left: 1342px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_E14AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 103px; left: 1342px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EPT_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 129px; left: 1269px; position:absolute;color:blue;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ07_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 129px; left: 664px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ09_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 149px; left: 664px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 191px; left: 755px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BPT03_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 210px; left: 755px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ZD_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 127px; left: 960px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ZD1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 144px; left: 960px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BVT02_V_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 161px; left: 960px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BVT03_V_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 176px; left: 960px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BZZ06_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 216px; left: 1130px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EZZ02_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 215px; left: 1171px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 196px; left: 893px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_E12M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 371px; left: 856px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B7M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:37px; display:block; top: 416px; left: 1147px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_E8M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 350px; left: 1302px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_byc_byf>dcs01_EZZ02_ZF_M>DCS'" style="width:59px; display:block; top: 367px; left: 1302px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 386px; left: 1309px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE04_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 402px; left: 1307px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EVT01_V_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 350px; left: 1368px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_EVT02_V_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 368px; left: 1368px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ZD2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 385px; left: 1368px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ZD3_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 402px; left: 1368px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>            
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 658px; left: 748px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 658px; left: 790px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T3_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 658px; left: 835px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T4_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 658px; left: 880px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T42_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 673px; left: 746px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T51_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 688px; left: 746px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T6_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 701px; left: 746px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T64_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 716px; left: 746px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T73_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 731px; left: 746px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T43_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 673px; left: 806px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T52_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 688px; left: 806px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T61_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 701px; left: 806px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T7_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 716px; left: 806px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T74_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 731px; left: 806px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T44_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 673px; left: 869px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T53_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 688px; left: 869px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T62_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 701px; left: 869px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T71_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 716px; left: 869px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T8_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 731px; left: 869px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T5_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 673px; left: 924px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T54_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 688px; left: 924px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T63_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 701px; left: 924px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T72_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 716px; left: 924px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T10_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 730px; left: 924px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_T9_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 743px; left: 934px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE09_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 659px; left: 994px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE11_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 675px; left: 994px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE10_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 659px; left: 1052px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 706px; left: 1000px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 739px; left: 1000px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE08_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 706px; left: 1053px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_ETE06_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 739px; left: 1053px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE17_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 666px; left: 1336px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE15_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 709px; left: 1338px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE13_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 740px; left: 1338px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE18_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 666px; left: 1391px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE19_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 680px; left: 1336px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE16_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 709px; left: 1393px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_BTE14_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 740px; left: 1393px; position:absolute;color:#4cff00;text-align:right;font-size:14px"></div>
     <%--汉字隐藏--%>
        <div id="zc_nxjc_byc_byf>dcs01_F_9CWG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 78px; left: 559px; color:red;font-size:20px;"> 9号库满</div> 
        <div id="zc_nxjc_byc_byf>dcs01_F_10CWG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 78px; left: 646px; color:red;font-size:20px;"> 10号库满</div>
        <div id="zc_nxjc_byc_byf>dcs01_B36ALC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 253px; left: 122px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B38M_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 282px; left: 203px; color:#4cff00;font-size:12px;"> 速度正常</div>
        <div id="zc_nxjc_byc_byf>dcs01_B25AC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 342px; left: 306px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B30ALC2_KTG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 414px; left: 289px; color:#4cff00;font-size:12px;"> 快速抬辊</div>
        <div id="zc_nxjc_byc_byf>dcs01_B30ALC2_TG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 430px; left: 299px; color:#4cff00;font-size:12px;"> 抬辊</div>
        <div id="zc_nxjc_byc_byf>dcs01_B30ALC2_LG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 514px; left: 299px; color:#4cff00;font-size:12px;"> 落辊</div>
        <div id="zc_nxjc_byc_byf>dcs01_B30ALC2_ZLG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 530px; left: 289px; color:#4cff00;font-size:12px;"> 自重落辊</div>
        <div id="zc_nxjc_byc_byf>dcs01_B26ALP_RN2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 533px; left: 190px; color:yellow;font-size:12px;"> 启动完毕</div>
        <div id="zc_nxjc_byc_byf>dcs01_B26ACP_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 569px; left: 252px; color:yellow;font-size:10px;"> 备妥</div>
        <div id="zc_nxjc_byc_byf>dcs01_B26ACP_STA>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 580px; left: 242px; color:#4cff00;font-size:10px;"> 进相状态</div>
        <div id="zc_nxjc_byc_byf>dcs01_B26ACP_PMT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 591px; left: 242px; color:#4cff00;font-size:10px;"> 允许进相</div>
        <div id="zc_nxjc_byc_byf>dcs01_B34AC_LM>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 630px; left: 131px; color:red;font-size:12px;"> 磨辅转离合器</div>
        <div id="zc_nxjc_byc_byf>dcs01_BPT04_P_M_HH>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 438px; left: 406px; color:red;font-size:12px;"> 压力低</div>
        <div id="zc_nxjc_byc_byf>dcs01_B40M_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 403px; left: 570px; color:#4cff00;font-size:12px;"> 速度正常</div>
        <div id="zc_nxjc_byc_byf>dcs01_B40M_LV>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 418px; left: 570px; color:red;font-size:12px;"> 料位开关</div>
        <div id="zc_nxjc_byc_byf>dcs01_B44ALC_AM1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 465px; left: 464px; color:red;font-size:12px;"> 发现金属</div>
        <div id="zc_nxjc_byc_byf>dcs01_B45AC_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 513px; left: 464px; color:#4cff00;font-size:12px;"> 速度正常</div>
        <div id="zc_nxjc_byc_byf>dcs01_B43ALC_AM>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 597px; left: 477px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B30ALC_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 691px; left: 334px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B30ALC_FT2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 660px; left: 504px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B31ALC_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 668px; left: 605px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B28ALC_STO>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 725px; left: 560px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B28ALC_AM>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 725px; left: 593px; color:red;font-size:12px;"> 预报警</div>
        <div id="zc_nxjc_byc_byf>dcs01_B28ALC_PMT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 742px; left: 560px; color:#4cff00;font-size:12px;"> 允许主机运行</div>
        <div id="zc_nxjc_byc_byf>dcs01_B29ALC_PMT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 726px; left: 662px; color:#4cff00;font-size:12px;"> 允许主机运行</div>
        <div id="zc_nxjc_byc_byf>dcs01_B29ALC_AM>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 742px; left: 662px; color:red;font-size:12px;"> 预报警</div>
        <div id="zc_nxjc_byc_byf>dcs01_B29ALC_STO>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 742px; left: 708px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ALC1_STO>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 726px; left: 1155px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ALC1_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 726px; left: 1192px; color:red;font-size:12px;"> 预报警</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ALC1_RS1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 742px; left: 1155px; color:#4cff00;font-size:12px;"> 允许主机运行</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ALC2_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 726px; left: 1253px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ALC2_AM>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 726px; left: 1288px; color:red;font-size:12px;"> 预报警</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ALC2_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 742px; left: 1253px; color:#4cff00;font-size:12px;"> 允许主机运行</div>
        <div id="zc_nxjc_byc_byf>dcs01_B1ALC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 441px; left: 1376px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B7M_SE1>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 484px; left: 1112px; color:red;font-size:12px; height: 39px; width: 14px;"> 左跑偏</div>
        <div id="zc_nxjc_byc_byf>dcs01_B7M_SE2>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 484px; left: 1139px; color:red;font-size:12px; width: 14px; height: 39px;"> 右跑偏</div>
        <div id="zc_nxjc_byc_byf>dcs01_B7M_LV>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 593px; left: 1109px; color:red;font-size:12px;"> 料位开关</div>
        <div id="zc_nxjc_byc_byf>dcs01_B7M_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 610px; left: 1109px; color:#4cff00;font-size:12px;"> 速度正常</div>
        <div id="zc_nxjc_byc_byf>dcs01_E12M_LV>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 593px; left: 888px; color:red;font-size:12px;"> 料位开关</div>
        <div id="zc_nxjc_byc_byf>dcs01_E12M_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 610px; left: 888px; color:#4cff00;font-size:12px;"> 速度正常</div>
        <div id="zc_nxjc_byc_byf>dcs01_E8M_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 332px; left: 1327px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B12ALC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 344px; left: 996px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_YLKYJGZ1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 620px; left: 590px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_YLKYJGZ2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 620px; left: 623px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_YLKYJGZ3>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 620px; left: 656px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_YLKYJGZ4>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 620px; left: 690px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_E7AC1_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 164px; left: 1227px; color:red;font-size:12px;"> 故障</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ALP_RN2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 247px; left: 910px; color:yellow;font-size:12px;"> 启动完毕</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ACP_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 230px; left: 976px; color:yellow;font-size:10px;"> 备妥</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ACP_STA>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 243px; left: 976px; color:#4cff00;font-size:10px;"> 进相状态</div>
        <div id="zc_nxjc_byc_byf>dcs01_B23ACP_PMT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 256px; left: 976px; color:#4cff00;font-size:10px;"> 允许进相</div>
         <%--开关量--%>  
        <%--圆形--%>  
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_Q1MALM>BoolSignal" style="position: absolute; top:169px; left: 486px; height: 21px; width: 24px;" data-option="RelatedTags='dcs01_Q1MALM,dcs01_Q1MRN,dcs01_Q1MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_X9ACALM>BoolSignal" style="position: absolute; top:147px; left: 572px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_X9ACALM,dcs01_X9ACRN,dcs01_X9ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_X8MALM>BoolSignal" style="position: absolute; top:147px; left: 629px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_X8MALM,dcs01_X8MRN,dcs01_X8MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_X1MALM>BoolSignal" style="position: absolute; top:160px; left: 572px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_X1MALM,dcs01_X1MRN,dcs01_X1MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_X2MALM>BoolSignal" style="position: absolute; top:160px; left: 629px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_X2MALM,dcs01_X2MRN,dcs01_X2MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_A13MALM>BoolSignal" style="position: absolute; top:184px; left: 254px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_A13MALM,dcs01_A13MRN,dcs01_A13MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B47MALM>BoolSignal" style="position: absolute; top:232px; left: 365px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B47MALM,dcs01_B47MRN,dcs01_B47MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B37MALM>BoolSignal" style="position: absolute; top:218px; left: 176px; height: 21px; width: 24px;" data-option="RelatedTags='dcs01_B37MALM,dcs01_B37MRN,dcs01_B37MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B40MALM>BoolSignal" style="position: absolute; top:254px; left: 84px; height: 21px; width: 24px;" data-option="RelatedTags='dcs01_B40MALM,dcs01_B40MRN,dcs01_B40MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B38MALM>BoolSignal" style="position: absolute; top:295px; left: 390px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B38MALM,dcs01_B38MRN,dcs01_B38MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B35YVALM>BoolSignal" style="position: absolute; top:326px; left: 374px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B35YVALM,dcs01_B35YVRN,dcs01_B35YVRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B33MALM>BoolSignal" style="position: absolute; top:392px; left: 393px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B33MALM,dcs01_B33MRN,dcs01_B33MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B32MALM>BoolSignal" style="position: absolute; top:529px; left: 437px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B32MALM,dcs01_B32MRN,dcs01_B32MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B45ACALM>BoolSignal" style="position: absolute; top:487px; left: 578px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B45ACALM,dcs01_B45ACRN,dcs01_B45ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B46YVALM>BoolSignal" style="position: absolute; top:516px; left: 569px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B46YVALM,dcs01_B46YVRN,dcs01_B46YVRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B34ACALM>BoolSignal" style="position: absolute; top:580px; left: 362px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B34ACALM,dcs01_B34ACRN,dcs01_B34ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26MALM>BoolSignal" style="position: absolute; top:560px; left: 303px; height: 21px; width: 24px;" data-option="RelatedTags='dcs01_B26MALM,dcs01_B26MRN,dcs01_B26MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B42MALM>BoolSignal" style="position: absolute; top:583px; left: 73px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B42MALM,dcs01_B42MRN,dcs01_B42MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_RN7>BoolSignal" style="position: absolute; top:667px; left: 257px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B30ALC_RN7',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_RN6>BoolSignal" style="position: absolute; top:682px; left: 257px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B30ALC_RN6',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_RN5>BoolSignal" style="position: absolute; top:697px; left: 257px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B30ALC_RN5',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_RN4>BoolSignal" style="position: absolute; top:712px; left: 257px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B30ALC_RN4',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_RN3>BoolSignal" style="position: absolute; top:727px; left: 257px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B30ALC_RN3',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_RN1>BoolSignal" style="position: absolute; top:670px; left: 282px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_B30ALC2_RN1',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_BY>BoolSignal" style="position: absolute; top:670px; left: 302px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_B30ALC2_BY',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_JY>BoolSignal" style="position: absolute; top:670px; left: 322px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_B30ALC2_JY',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_AM1>BoolSignal" style="position: absolute; top:724px; left: 282px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC2_AM1',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_AM2>BoolSignal" style="position: absolute; top:724px; left: 302px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC2_AM2',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_LLL>BoolSignal" style="position: absolute; top:724px; left: 322px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC2_LLL',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM4>BoolSignal" style="position: absolute; top:724px; left: 342px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM4',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM1>BoolSignal" style="position: absolute; top:742px; left: 282px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM1',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM2>BoolSignal" style="position: absolute; top:742px; left: 302px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM2',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM3>BoolSignal" style="position: absolute; top:742px; left: 322px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM3',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM>BoolSignal" style="position: absolute; top:742px; left: 342px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM4',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_RN2>BoolSignal" style="position: absolute; top:655px; left: 448px; height: 21px; width: 24px;" data-option="RelatedTags='dcs01_B30ALC2_RN2',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_RN3>BoolSignal" style="position: absolute; top:655px; left: 477px; height: 21px; width: 24px;" data-option="RelatedTags='dcs01_B30ALC2_RN3',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_RN2>BoolSignal" style="position: absolute; top:699px; left: 415px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B30ALC_RN2',Display='0:NULL,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM6>BoolSignal" style="position: absolute; top:721px; left: 415px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM6',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_TL>BoolSignal" style="position: absolute; top:721px; left: 440px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC2_TL',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_TH>BoolSignal" style="position: absolute; top:721px; left: 465px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC2_TH',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_LTLL>BoolSignal" style="position: absolute; top:721px; left: 490px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC2_LTLL',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_FL>BoolSignal" style="position: absolute; top:721px; left: 515px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC2_FL',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM5>BoolSignal" style="position: absolute; top:740px; left: 440px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM5',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM61>BoolSignal" style="position: absolute; top:740px; left: 465px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM6',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM7>BoolSignal" style="position: absolute; top:740px; left: 490px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM7',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_AM8>BoolSignal" style="position: absolute; top:740px; left: 515px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_B30ALC_AM8',Display='0:NULL,1:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_BHSB_RN>BoolSignal" style="position: absolute; top:24px; left: 454px; height: 21px; width: 24px;" data-option="RelatedTags='dcs01_BHSB_RN,dcs01_BHSB_RD',Display='00:grayC,01:whiteC,10:redCB,11:greenCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_RN1>BoolSignal" style="position: absolute; top:703px; left: 601px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B28ALC_RN1',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_RN2>BoolSignal" style="position: absolute; top:703px; left: 614px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B28ALC_RN2',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALC_RN1>BoolSignal" style="position: absolute; top:676px; left: 669px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B29ALC_RN1',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALC_RN2>BoolSignal" style="position: absolute; top:676px; left: 690px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B29ALC_RN2',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALC_RN3>BoolSignal" style="position: absolute; top:696px; left: 669px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B29ALC_RN3',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALC_RN4>BoolSignal" style="position: absolute; top:696px; left: 690px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B29ALC_RN4',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALC_RN5>BoolSignal" style="position: absolute; top:696px; left: 711px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B29ALC_RN5',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALC_RN6>BoolSignal" style="position: absolute; top:696px; left: 732px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B29ALC_RN6',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ALC1_RN1>BoolSignal" style="position: absolute; top:688px; left: 1167px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B23ALC1_RN1',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ALC1_RN2>BoolSignal" style="position: absolute; top:688px; left: 1198px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B23ALC1_RN2',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ALC2_RN1>BoolSignal" style="position: absolute; top:688px; left: 1266px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B23ALC2_RN1',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ALC2_RN2>BoolSignal" style="position: absolute; top:688px; left: 1295px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B23ALC2_RN2',Display='0:whiteC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_YLKYJYX3>BoolSignal" style="position: absolute; top:600px; left: 595px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_YLKYJYX3',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_YLKYJYX4>BoolSignal" style="position: absolute; top:600px; left: 629px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_YLKYJYX4',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_YLKYJYX1>BoolSignal" style="position: absolute; top:600px; left: 662px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_YLKYJYX1',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_YLKYJYX2>BoolSignal" style="position: absolute; top:600px; left: 695px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_YLKYJYX2',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_BPYU1>BoolSignal" style="position: absolute; top:609px; left: 738px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_BPYU1',Display='0:redC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_BPYU2>BoolSignal" style="position: absolute; top:609px; left: 764px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_BPYU2',Display='0:redC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_BPYU3>BoolSignal" style="position: absolute; top:609px; left: 789px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_BPYU3',Display='0:redC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_GPYU1>BoolSignal" style="position: absolute; top:609px; left: 816px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_GPYU1',Display='0:redC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_GPYU2>BoolSignal" style="position: absolute; top:609px; left: 840px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_GPYU2',Display='0:redC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_GPYU3>BoolSignal" style="position: absolute; top:609px; left: 863px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_GPYU3',Display='0:redC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B16M2ALM>BoolSignal" style="position: absolute; top:496px; left: 725px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B16M2ALM,dcs01_B16M2RN,dcs01_B16M2RD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B16MALM>BoolSignal" style="position: absolute; top:494px; left: 790px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B16MALM,dcs01_B16MRN,dcs01_B16MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B16M1ALM>BoolSignal" style="position: absolute; top:494px; left: 825px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B16M1ALM,dcs01_B16M1RN,dcs01_B16M1RD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B19MALM>BoolSignal" style="position: absolute; top:404px; left: 692px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B19MALM,dcs01_B19MRN,dcs01_B19MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B20MALM>BoolSignal" style="position: absolute; top:404px; left: 742px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B20MALM,dcs01_B20MRN,dcs01_B20MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B21MALM>BoolSignal" style="position: absolute; top:404px; left: 789px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B21MALM,dcs01_B21MRN,dcs01_B21MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B22MALM>BoolSignal" style="position: absolute; top:404px; left: 839px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B22MALM,dcs01_B22MRN,dcs01_B22MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_E12MALM>BoolSignal" style="position: absolute; top:389px; left: 901px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_E12MALM,dcs01_E12MRN,dcs01_E12MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_E13M_RN>BoolSignal" style="position: absolute; top:419px; left: 901px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_E13M_RN',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B17MALM>BoolSignal" style="position: absolute; top:455px; left: 926px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B17MALM,dcs01_B17MRN,dcs01_B17MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B14MALM>BoolSignal" style="position: absolute; top:455px; left: 959px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B14MALM,dcs01_B14MRN,dcs01_B14MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B18MALM>BoolSignal" style="position: absolute; top:503px; left: 1011px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B18MALM,dcs01_B18MRN,dcs01_B18MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B10MALM>BoolSignal" style="position: absolute; top:516px; left: 1064px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B10MALM,dcs01_B10MRN,dcs01_B10MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B11MALM>BoolSignal" style="position: absolute; top:408px; left: 1096px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B11MALM,dcs01_B11MRN,dcs01_B11MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B15MALM>BoolSignal" style="position: absolute; top:454px; left: 1064px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B15MALM,dcs01_B15MRN,dcs01_B15MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B7MALM>BoolSignal" style="position: absolute; top:389px; left: 1126px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_B7MALM,dcs01_B7MRN,dcs01_B7MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B8M_RN>BoolSignal" style="position: absolute; top:419px; left: 1125px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B8M_RN',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B13MALM>BoolSignal" style="position: absolute; top:357px; left: 1051px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B13MALM,dcs01_B13MRN,dcs01_B13MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B4MALM>BoolSignal" style="position: absolute; top:547px; left: 1275px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B4MALM,dcs01_B4MRN,dcs01_B4MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B5MALM>BoolSignal" style="position: absolute; top:534px; left: 1355px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B5MALM,dcs01_B5MRN,dcs01_B5MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B3MALM>BoolSignal" style="position: absolute; top:547px; left: 1429px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B3MALM,dcs01_B3MRN,dcs01_B3MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B6MALM>BoolSignal" style="position: absolute; top:465px; left: 1331px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B6MALM,dcs01_B6MRN,dcs01_B6MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B2MALM>BoolSignal" style="position: absolute; top:483px; left: 1427px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_B2MALM,dcs01_B2MRN,dcs01_B2MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_E8MALM>BoolSignal" style="position: absolute; top:267px; left: 1312px; height: 38px; width: 45px;" data-option="RelatedTags='dcs01_E8MALM,dcs01_E8MRN,dcs01_E8MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F29ACRN>BoolSignal" style="position: absolute; top:41px; left: 1251px; height: 31px; width: 36px;" data-option="RelatedTags='dcs01_F29ACRN',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_E14ACALM>BoolSignal" style="position: absolute; top:11px; left: 1393px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_E14ACALM,dcs01_E14ACRN,dcs01_E14ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23MALM>BoolSignal" style="position: absolute; top:156px; left: 910px; height: 34px; width: 49px;" data-option="RelatedTags='dcs01_B23MALM,dcs01_B23MRN,dcs01_B23MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayCB'"></div>
         <%--方形--%>  
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_A12ACALM>BoolSignal" style="position: absolute; top:117px; left: 101px; height: 11px; width: 22px;" data-option="RelatedTags='dcs01_A12ACALM,dcs01_A12ACRN,dcs01_A12ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_A11ACALM>BoolSignal" style="position: absolute; top:117px; left: 154px; height: 11px; width: 22px;" data-option="RelatedTags='dcs01_A11ACALM,dcs01_A11ACRN,dcs01_A11ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_A10ACALM>BoolSignal" style="position: absolute; top:117px; left: 243px; height: 11px; width: 22px;" data-option="RelatedTags='dcs01_A10ACALM,dcs01_A10ACRN,dcs01_A10ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_A9ACALM>BoolSignal" style="position: absolute; top:117px; left: 315px; height: 11px; width: 22px;" data-option="RelatedTags='dcs01_A9ACALM,dcs01_A9ACRN,dcs01_A9ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_Q6AC2ALM>BoolSignal" style="position: absolute; top:169px; left: 425px; height: 21px; width: 39px;" data-option="RelatedTags='dcs01_Q6AC2ALM,dcs01_Q6AC2RN,dcs01_Q6AC2RD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B25ACALM>BoolSignal" style="position: absolute; top:320px; left: 304px; height: 17px; width: 28px; margin-bottom: 4px;" data-option="RelatedTags='dcs01_B25ACALM,dcs01_B25ACRN,dcs01_B25ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM2>BoolSignal" style="position: absolute; top:399px; left: 269px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM2',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM4>BoolSignal" style="position: absolute; top:399px; left: 295px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM4',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM6>BoolSignal" style="position: absolute; top:399px; left: 322px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM6',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM8>BoolSignal" style="position: absolute; top:399px; left: 348px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM8',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM1>BoolSignal" style="position: absolute; top:543px; left: 269px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM1',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM3>BoolSignal" style="position: absolute; top:543px; left: 295px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM3',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM5>BoolSignal" style="position: absolute; top:543px; left: 322px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM5',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_LM7>BoolSignal" style="position: absolute; top:543px; left: 348px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B30ALC_LM7',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B27EHALM>BoolSignal" style="position: absolute; top:563px; left: 344px; height: 12px; width: 21px;" data-option="RelatedTags='dcs01_B27EHALM,dcs01_B27EHRN,dcs01_B27EHRD',Display='000:grayS,001:whiteS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B44ALC_AM2>BoolSignal" style="position: absolute; top:478px; left: 480px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B44ALC_AM2',Display='0:whiteS,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B43ALCALM>BoolSignal" style="position: absolute; top:563px; left: 506px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B43ALCALM,dcs01_B43ALCRN,dcs01_B43ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_PO1>BoolSignal" style="position: absolute; top:612px; left: 408px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_PO1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_DIS1>BoolSignal" style="position: absolute; top:612px; left: 430px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_DIS1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_PTR1>BoolSignal" style="position: absolute; top:612px; left: 452px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_PTR1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_AM1>BoolSignal" style="position: absolute; top:612px; left: 474px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_AM1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_FT1>BoolSignal" style="position: absolute; top:612px; left: 496px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_FT1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_PO2>BoolSignal" style="position: absolute; top:627px; left: 408px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_PO2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_DIS2>BoolSignal" style="position: absolute; top:627px; left: 430px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_DIS2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_PTR2>BoolSignal" style="position: absolute; top:627px; left: 452px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_PTR2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_AM2>BoolSignal" style="position: absolute; top:627px; left: 474px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_AM2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26M_FT2>BoolSignal" style="position: absolute; top:627px; left: 496px; height: 12px; width: 19px;" data-option="RelatedTags='dcs01_B26M_FT2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_RN4>BoolSignal" style="position: absolute; top:670px; left: 358px; height: 17px; width: 22px;" data-option="RelatedTags='dcs01_B30ALC2_RN4',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC_RD1>BoolSignal" style="position: absolute; top:691px; left: 282px; height: 12px; width: 23px;" data-option="RelatedTags='dcs01_B30ALC_RD1',Display='0:grayS,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2ALM>BoolSignal" style="position: absolute; top:655px; left: 415px; height: 21px; width: 20px;" data-option="RelatedTags='dcs01_B30ALC2ALM,dcs01_B30ALC2RN,dcs01_B30ALC2RD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B30ALC2_RN5>BoolSignal" style="position: absolute; top:699px; left: 505px; height: 15px; width: 25px;" data-option="RelatedTags='dcs01_B30ALC2_RN5',Display='0:NULL,1:greenS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B26ALP_RD>BoolSignal" style="position: absolute; top:514px; left: 203px; height: 11px; width: 24px;" data-option="RelatedTags='dcs01_B26ALP_RD',Display='0:whiteS,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B36ALCALM>BoolSignal" style="position: absolute; top:216px; left: 125px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B36ALCALM,dcs01_B36ALCRN,dcs01_B36ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ALP_RD>BoolSignal" style="position: absolute; top:219px; left: 929px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23ALP_RD',Display='0:whiteS,1:yellowS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B24EHALM>BoolSignal" style="position: absolute; top:200px; left: 992px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B24EHALM,dcs01_B24EHRN,dcs01_B24EHRD',Display='000:grayS,001:whiteS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_PO1>BoolSignal" style="position: absolute; top:216px; left: 1034px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_PO1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_DIS1>BoolSignal" style="position: absolute; top:216px; left: 1052px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_DIS1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_PTR1>BoolSignal" style="position: absolute; top:216px; left: 1071px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_PTR1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_AM1>BoolSignal" style="position: absolute; top:228px; left: 1034px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_AM1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_FT1>BoolSignal" style="position: absolute; top:228px; left: 1052px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_FT1',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_PO2>BoolSignal" style="position: absolute; top:240px; left: 1034px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_PO2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_DIS2>BoolSignal" style="position: absolute; top:240px; left: 1052px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_DIS2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_PTR2>BoolSignal" style="position: absolute; top:240px; left: 1071px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_PTR2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_AM2>BoolSignal" style="position: absolute; top:252px; left: 1034px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_AM2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23M_FT2>BoolSignal" style="position: absolute; top:252px; left: 1052px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B23M_FT2',Display='0:NULL,1:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_E7ACALM>BoolSignal" style="position: absolute; top:130px; left: 1221px; height: 23px; width: 40px;" data-option="RelatedTags='dcs01_E7ACALM,dcs01_E7ACRN,dcs01_E7ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_E9EHALM>BoolSignal" style="position: absolute; top:306px; left: 1354px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_E9EHALM,dcs01_E9EHRN,dcs01_E9EHRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B12ALCALM>BoolSignal" style="position: absolute; top:369px; left: 1014px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B12ALCALM,dcs01_B12ALCRN,dcs01_B12ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B17ALCALM>BoolSignal" style="position: absolute; top:493px; left: 970px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B17ALCALM,dcs01_B17ALCRN,dcs01_B17ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B1ALCALM>BoolSignal" style="position: absolute; top:462px; left: 1380px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B1ALCALM,dcs01_B1ALCRN,dcs01_B1ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B31ALCALM>BoolSignal" style="position: absolute; top:666px; left: 566px; height: 14px; width: 28px;" data-option="RelatedTags='dcs01_B31ALCALM,dcs01_B31ALCRN,dcs01_B31ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALC_RN3>BoolSignal" style="position: absolute; top:709px; left: 565px; height: 10px; width: 16px;" data-option="RelatedTags='dcs01_B28ALC_RN3',Display='0:grayS,1:greenS'"></div>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B28ALCALM>BoolSignal" style="position: absolute; top:702px; left: 595px; height: 17px; width: 40px;" data-option="RelatedTags='dcs01_B28ALCALM,dcs01_B28ALCRN,dcs01_B28ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALCALM>BoolSignal" style="position: absolute; top:669px; left: 662px; height: 49px; width: 90px;" data-option="RelatedTags='dcs01_B29ALCALM,dcs01_B29ALCRN,dcs01_B29ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ALC1ALM>BoolSignal" style="position: absolute; top:682px; left: 1155px; height: 28px; width: 71px;" data-option="RelatedTags='dcs01_B23ALC1ALM,dcs01_B23ALC1RN,dcs01_B23ALC1RD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B23ALC2ALM>BoolSignal" style="position: absolute; top:682px; left: 1253px; height: 28px; width: 71px;" data-option="RelatedTags='dcs01_B23ALC2ALM,dcs01_B23ALC2RN,dcs01_B23ALC2RD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>--%>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B29ALC_RN7>BoolSignal" style="position: absolute; top:339px; left: 411px; height: 11px; width: 20px;" data-option="RelatedTags='dcs01_B29ALC_RN7',Display='0:grayS,1:greenS'"></div>
        <%--箭头--%>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B35YVRN>BoolSignal" style="position: absolute; top:350px; left: 395px; height: 40px; width: 9px;" data-option="RelatedTags='dcs01_B35YVRN',Display='0:arrowGreenDown,1:NULL'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_B46YVRN>BoolSignal" style="position: absolute; top:550px; left: 572px; height: 53px; width: 10px;" data-option="RelatedTags='dcs01_B46YVRN',Display='0:NULL,1:arrowGreenDown'"></div>
         <%--棒图--%>
        <div class="BarGraph mchart" id="zc_nxjc_byc_byf>dcs01_BLT01_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:10px;height:44px; position:absolute; top: 394px; left: 449px;"></div>
        <div class="BarGraph mchart" id="zc_nxjc_byc_byf>dcs01_ELT01_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:25px; height:71px; position:absolute; top: 29px; left: 1445px;"></div>
    </div>
</body>
</html>
