<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_byc_byf_cementmill01_snfm.aspx.cs" Inherits="Monitor_byc.web.UI_Monitor.DCSMonitor.zc_nxjc_byc_byf.zc_nxjc_byc_byf_cementmill01_snfm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_byc_byf";
        publicData.sceneName = "1#水泥粉磨";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="ForeGround" style="width: 1480px; height:760px; margin: 0px auto; position:absolute;z-index:5555;overflow: auto; background-color: #FFFFFF;"></div>
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_byc_byf/zc_nxjc_byc_byf_cementmill01_snfm.png'); width: 1480px; height: 760px; overflow: hidden;">
         <div id="ConnectionGround" style="width: 1480px; height: 760px;margin: 0px auto; position:absolute;z-index:5555;overflow: auto;background-color:gray;opacity:0.6">
   </div>
   <div id="TextGround"style="font-size:large;padding-left:40px;padding-bottom:200px;padding-right:500px;padding-top:0px;width:1480px;height: 760px;"></div>   
        <div id="Picture"style="position: absolute; top: 4px; left: 7px; height: 20px; width: 20px; background-size:100% auto"></div> 
      <%--   贴标签处--%>
<%--      <button onclick="CheckTags()">检查标签</button>--%>
        <%--圆形--%>  
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_SNMKYJYX1>BoolSignal" style="position: absolute; top:116px; left: 20px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_SNMKYJYX1',Display='0:grayC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_SNMKYJYX2>BoolSignal" style="position: absolute; top:116px; left: 71px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_SNMKYJYX2',Display='0:grayC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_SNMKYJYX3>BoolSignal" style="position: absolute; top:116px; left: 134px; height: 17px; width:17px;" data-option="RelatedTags='dcs01_SNMKYJYX3',Display='0:grayC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_SNMKYJYX4>BoolSignal" style="position: absolute; top:116px; left: 200px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_SNMKYJYX4',Display='0:grayC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M33Ma_RN>BoolSignal" style="position: absolute; top:48px; left: 274px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M33Ma_RN',Display='0:grayC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M30YVALM>BoolSignal" style="position: absolute; top:132px; left: 459px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_F_1M30YVALM,dcs01_F_1M30YVRN,dcs01_F_1M30YVRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L5MbALM>BoolSignal" style="position: absolute; top:210px; left: 121px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_L5MbALM, dcs01_L5MbRN,dcs01_L5MbRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L13MALM>BoolSignal" style="position: absolute; top:253px; left: 132px; height: 19px; width: 19px;" data-option="RelatedTags='dcs01_L13MALM,dcs01_L13MRN,dcs01_L13MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M35ACALM>BoolSignal" style="position: absolute; top:353px; left: 232px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M35ACALM,dcs01_F_1M35ACRN,dcs01_F_1M35ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_H10ACALM>BoolSignal" style="position: absolute; top:385px; left: 128px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_H10ACALM,dcs01_H10ACRN,dcs01_H10ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_H11ACALM>BoolSignal" style="position: absolute; top:411px; left: 146px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_H11ACALM,dcs01_H11ACRN,dcs01_H11ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_H12ACALM>BoolSignal" style="position: absolute; top:438px; left: 156px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_H12ACALM,dcs01_H12ACRN,dcs01_H12ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_H9MALM>BoolSigna" style="position: absolute; top:467px; left: 24px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_H9MALM,dcs01_H9MRN,dcs01_H9MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L24MALM>BoolSigna" style="position: absolute; top:499px; left: 6px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_L24MALM,dcs01_L24MRN,dcs01_L24MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L2MaALM>BoolSigna" style="position: absolute; top:398px; left: 252px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_L2MaALM,dcs01_L2MaRN,dcs01_L2MaRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L3MaALM>BoolSigna" style="position: absolute; top:437px; left: 252px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_L3MaALM, dcs01_L3MaRN,dcs01_L3MaRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M26ACALM>BoolSigna" style="position: absolute; top:449px; left: 301px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M26ACALM,dcs01_F_1M26ACRN,dcs01_F_1M26ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M17MALM>BoolSigna" style="position: absolute; top:393px; left: 444px; height: 19px; width: 19px;" data-option="RelatedTags='dcs01_F_1M17MALM,dcs01_F_1M17MRN,dcs01_F_1M17MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M16MALM>BoolSigna" style="position: absolute; top:394px; left: 492px; height: 19px; width: 19px;" data-option="RelatedTags='dcs01_F_1M16MALM, dcs01_F_1M16MRN,dcs01_F_1M16MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M42MALM>BoolSigna" style="position: absolute; top:433px; left: 575px; height: 19px; width: 19px;" data-option="RelatedTags='dcs01_F_1M42MALM, dcs01_F_1M42MRN,dcs01_F_1M42MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M41MALM>BoolSigna" style="position: absolute; top:520px; left: 681px; height: 19px; width: 19px;" data-option="RelatedTags='dcs01_F_1M41MALM, dcs01_F_1M41MRN,dcs01_F_1M41MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M46MALM>BoolSigna" style="position: absolute; top:567px; left: 392px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_F_1M46MALM, dcs01_F_1M46MRN,dcs01_F_1M46MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M43MALM>BoolSigna" style="position: absolute; top:608px; left: 511px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M43MALM, dcs01_F_1M43MRN,dcs01_F_1M43MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M27MALM>BoolSigna" style="position: absolute; top:635px; left: 993px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M27MALM, dcs01_F_1M16MRN,dcs01_F_1M16MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M23ACALM>BoolSigna" style="position: absolute; top:439px; left: 1367px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M23ACALM, dcs01_F_1M23ACRN,dcs01_F_1M23ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M28MALM>BoolSigna" style="position: absolute; top:337px; left: 1113px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M28MALM, dcs01_F_1M28MRN,dcs01_F_1M28MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M6MALM>BoolSigna" style="position: absolute; top:191px; left: 906px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M6MALM, dcs01_F_1M6MRN,dcs01_F_1M6MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M5MALM>BoolSigna" style="position: absolute; top:219px; left: 991px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M5MALM, dcs01_F_1M5MRN,dcs01_F_1M5MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M9MALM>BoolSigna" style="position: absolute; top:223px; left: 1068px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M9MALM, dcs01_F_1M9MRN,dcs01_F_1M9MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M10MALM>BoolSigna" style="position: absolute; top:227px; left: 1165px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M10MALM, dcs01_F_1M10MRN,dcs01_F_1M10MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M11M_RN>BoolSigna" style="position: absolute; top:246px; left: 1166px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_F_1M11M_RN',Display='0:grayC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M12MALM>BoolSigna" style="position: absolute; top:225px; left: 1259px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M12MALM, dcs01_F_1M12MRN,dcs01_F_1M12MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M1MALM>BoolSigna" style="position: absolute; top:233px; left: 1334px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M1MALM, dcs01_F_1M1MRN,dcs01_F_1M1MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M2M_RN>BoolSigna" style="position: absolute; top:252px; left: 1335px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_F_1M2M_RN',Display='0:grayC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M25ACALM>BoolSigna" style="position: absolute; top:52px; left: 714px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_F_1M25ACALM,dcs01_F_1M25ACRN,dcs01_F_1M25ACRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M8MALM>BoolSigna" style="position: absolute; top:92px; left: 1160px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M8MALM, dcs01_F_1M8MRN,dcs01_F_1M8MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M4MALM>BoolSigna" style="position: absolute; top:104px; left: 1318px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M4MALM, dcs01_F_1M4MRN,dcs01_F_1M4MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M31MALM>BoolSigna" style="position: absolute; top:8px; left: 1315px; height: 15px; width: 15px;" data-option="RelatedTags='dcs01_F_1M31MALM, dcs01_F_1M31MRN,dcs01_F_1M31MRD',Display='000:grayC,001:yellowC,010:greenCB,011:greenC,100:redC,101:redC,110:redC,111:grayC'"></div>


        
        <%--方形--%>  
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29ACALM>BoolSigna" style="position: absolute; top:384px; left: 406px; height: 13px; width: 21px;" data-option="RelatedTags='dcs01_F_1M29ACALM,dcs01_F_1M29ACRN,dcs01_F_1M29ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M38EHALM>BoolSigna" style="position: absolute; top:422px; left: 406px; height: 12px; width: 18px;" data-option="RelatedTags='dcs01_F_1M38EHALM,dcs01_F_1M38EHRN,dcs01_F_1M38EHRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M37EHALM>BoolSigna" style="position: absolute; top:408px; left: 530px; height: 12px; width: 23px;" data-option="RelatedTags='dcs01_F_1M37EHALM,dcs01_F_1M37EHRN,dcs01_F_1M37EHRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M44ACALM>BoolSigna" style="position: absolute; top:540px; left: 444px; height: 12px; width: 39px;" data-option="RelatedTags='dcs01_F_1M44ACALM,dcs01_F_1M44ACRN,dcs01_F_1M44ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M45ALCALM>BoolSigna" style="position: absolute; top:550px; left: 311px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M45ALCALM,dcs01_F_1M45ALCRN,dcs01_F_1M45ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L5AFCALM1>BoolSigna" style="position: absolute; top:736px; left: 78px; height: 20px; width: 55px;" data-option="RelatedTags='dcs01_L5AFCALM1,dcs01_L5AFCRN1,dcs01_L5AFCRD1',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L7AFCALM>BoolSigna" style="position: absolute; top:736px; left: 135px; height: 20px; width: 84px;" data-option="RelatedTags='dcs01_L7AFCALM,dcs01_L7AFCRN,dcs01_L7AFCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L9AFCALM>BoolSigna" style="position: absolute; top:736px; left: 222px; height: 20px; width: 84px;" data-option="RelatedTags='dcs01_L9AFCALM,dcs01_L9AFCRN,dcs01_L9AFCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_L11AFCALM>BoolSigna" style="position: absolute; top:736px; left: 308px; height: 20px; width: 51px;" data-option="RelatedTags='dcs01_L11AFCALM,dcs01_L11AFCRN,dcs01_L11AFCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M44ACALM1>BoolSigna" style="position: absolute; top:736px; left: 361px; height: 20px; width: 46px;" data-option="RelatedTags='dcs01_F_1M44ACALM,dcs01_F_1M44ACRN,dcs01_F_1M44ACRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_X1AFCALM>BoolSigna" style="position: absolute; top:736px; left: 410px; height: 20px; width: 51px;" data-option="RelatedTags='dcs01_X1AFCALM,dcs01_X1AFCRN,dcs01_X1AFCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_X2AFCALM>BoolSigna" style="position: absolute; top:736px; left: 463px; height: 20px; width: 61px;" data-option="RelatedTags='dcs01_X2AFCALM,dcs01_X2AFCRN,dcs01_X2AFCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M15EHALM>BoolSigna" style="position: absolute; top:513px; left: 1021px; height: 19px; width: 9px;" data-option="RelatedTags='dcs01_F_1M15EHALM,dcs01_F_1M15EHRN,dcs01_F_1M15EHRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M13MALM>BoolSigna" style="position: absolute; top:493px; left: 1040px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_F_1M13MALM,dcs01_F_1M13MRN,dcs01_F_1M13MRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M22ALCALM>BoolSigna" style="position: absolute; top:447px; left: 1185px; height: 12px; width: 27px;" data-option="RelatedTags='dcs01_F_1M22ALCALM,dcs01_F_1M22ALCRN,dcs01_F_1M22ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M7ALCALM>BoolSigna" style="position: absolute; top:88px; left: 996px; height: 16px; width: 32px;" data-option="RelatedTags='dcs01_F_1M7ALCALM,dcs01_F_1M7ALCRN,dcs01_F_1M7ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M39EHALM>BoolSigna" style="position: absolute; top:103px; left: 1137px; height: 12px; width: 23px;" data-option="RelatedTags='dcs01_F_1M39EHALM,dcs01_F_1M39EHRN,dcs01_F_1M39EHRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M3ALCALM>BoolSigna" style="position: absolute; top:111px; left: 1242px; height: 17px; width: 17px;" data-option="RelatedTags='dcs01_F_1M3ALCALM,dcs01_F_1M3ALCRN,dcs01_F_1M3ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
        
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M19ALCALM>BoolSigna" style="position: absolute; top:585px; left: 750px; height: 18px; width: 90px;" data-option="RelatedTags='dcs01_F_1M19ALCALM,dcs01_F_1M19ALCRN,dcs01_F_1M19ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M20ALCALM>BoolSigna" style="position: absolute; top:619px; left: 750px; height: 18px; width: 89px;" data-option="RelatedTags='dcs01_F_1M20ALCALM,dcs01_F_1M20ALCRN,dcs01_F_1M20ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M18ALCALM>BoolSigna" style="position: absolute; top:586px; left: 885px; height: 18px; width: 49px;" data-option="RelatedTags='dcs01_F_1M18ALCALM,dcs01_F_1M18ALCRN,dcs01_F_1M18ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M21ALCALM>BoolSigna" style="position: absolute; top:621px; left: 885px; height: 18px; width: 49px;" data-option="RelatedTags='dcs01_F_1M21ALCALM,dcs01_F_1M21ALCRN,dcs01_F_1M21ALCRD',Display='000:grayS,001:yellowS,010:greenS,011:greenS,100:redS,101:redS,110:redS,111:grayS'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M19ALC_RN1>BoolSigna" style="position: absolute; top:586px; left: 748px; height: 18px; width: 18px;"data-option="RelatedTags='dcs01_F_1M19ALC_RN1',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M19ALC_RN2>BoolSigna" style="position: absolute; top:586px; left: 771px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M19ALC_RN2',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M19ALC_RN3>BoolSigna" style="position: absolute; top:586px; left: 794px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M19ALC_RN3',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M19ALC_RN4>BoolSigna" style="position: absolute; top:586px; left: 817px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M19ALC_RN4',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M18ALC_RN1>BoolSigna" style="position: absolute; top:586px; left: 887px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M18ALC_RN1',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M18ALC_RN2>BoolSigna" style="position: absolute; top:586px; left: 909px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M18ALC_RN2',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M20ALC_RN1>BoolSigna" style="position: absolute; top:620px; left: 748px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M20ALC_RN1',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M20ALC_RN2>BoolSigna" style="position: absolute; top:620px; left: 771px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M20ALC_RN2',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M20ALC_RN3>BoolSigna" style="position: absolute; top:620px; left: 794px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M20ALC_RN3',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M20ALC_RN4>BoolSigna" style="position: absolute; top:620px; left: 817px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M20ALC_RN4',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M21ALC_RN1>BoolSigna" style="position: absolute; top:620px; left: 887px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M21ALC_RN1',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M21ALC_RN2>BoolSigna" style="position: absolute; top:620px; left: 909px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_F_1M21ALC_RN2',Display='0:whiteC,1:greenC'"></div>
            <div class="BoolSignal mchart" id="zc_nxjc_byc_byf>dcs01_MHSB_RN>BoolSigna" style="position: absolute; top:7px; left: 1348px; height: 29px; width: 29px;" data-option="RelatedTags='dcs01_MHSB_RN,dcs01_MHSB_RD',Display='00:grayS,01:yellowS,10:redS,11:greenS'"></div>
        
         <%--箭头--%>
            <div class="BoolSignal mchart"id="zc_nxjc_byc_byf>dcs01_L13M_SEL>BoolSigna" style="position: absolute; top:251px; left: 44px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_L13M_SEL',Display='0:NULL,1:arrowYellowRightS'"></div>
            <div class="BoolSignal mchart"id="zc_nxjc_byc_byf>dcs01_L13M_SEL1>BoolSigna" style="position: absolute; top:251px; left: 99px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_L13M_SEL',Display='0:arrowYellowLeftS,1:NULL'"></div>
        
          <%--模拟量--%>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M33Ma_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 22px; left: 293px; position:absolute;color:#4cff00;text-align:right;font-size:12px;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M33Mb_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 38px; left: 293px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L5LLT_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 191px; left: 83px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MPT06_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 211px; left: 360px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M35AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 311px; left: 127px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M35AC_SDF_M>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 328px; left: 127px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_H10AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:30px; display:block; top: 374px; left: 5px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_H10AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:30px; display:block; top: 390px; left: 5px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_H11AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:30px; display:block; top: 406px; left: 5px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_H11AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:30px; display:block; top: 421px; left: 5px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_H12AC_SDF_M>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:30px; display:block; top: 436px; left: 5px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_H12AC_CUN_M>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:30px; display:block; top: 452px; left: 5px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L23M_CUN_M>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 516px; left: 14px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MWT01_W_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 261px; left: 432px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_GYJDDZB>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 342px; left: 306px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M17M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 358px; left: 306px; position:absolute;color:#4cff00;text-align:right;font-size:12px; height: 15px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_P1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 343px; left: 362px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_JX1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 359px; left: 362px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_P2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 349px; left: 528px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_JX2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 364px; left: 528px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MPT05_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 349px; left: 609px; position:absolute;color:#4cff00;text-align:right;font-size:12px; height: 12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M16M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 364px; left: 609px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_JX_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 378px; left: 437px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MZZ03_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 26px; left: 614px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M25AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 45px; left: 756px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M25AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 61px; left: 756px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M25AC_SDF_M1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 78px; left: 756px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE41_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 136px; left: 732px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE42_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 136px; left: 786px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE43_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 136px; left: 838px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
        
        
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTT03_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 76px; left: 864px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MPT03_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 93px; left: 864px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MPTC_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 60px; left: 965px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTT04_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 46px; left: 1066px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MPT04_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 62px; left: 1066px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MZZ02_ZF_M>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 104px; left: 1066px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M8M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 128px; left: 1123px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MVT01_MM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 145px; left: 1123px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MVT01_V_M1>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 164px; left: 1123px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M10M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 207px; left: 1137px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M1M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 212px; left: 1308px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M24ALC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 422px; left: 763px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTT01_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 432px; left: 900px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MPT01_P_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 449px; left: 900px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTT02_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 417px; left: 1218px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MPT02_P_M>DCS"data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 435px; left: 1218px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MZZ01_ZF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 430px; left: 1283px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M23AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 439px; left: 1395px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_SNMN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 458px; left: 1283px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE15_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 490px; left: 773px; position:absolute;color:blue;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE17_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 490px; left: 883px; position:absolute;color:blue;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M13M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 508px; left: 829px; position:absolute;color:blue;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE16_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 530px; left: 772px; position:absolute;color:blue;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE18_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 530px; left: 882px; position:absolute;color:blue;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTT05_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 550px; left: 1010px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M42M_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 440px; left: 503px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M26AC_CUN_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 469px; left: 307px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M26AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 486px; left: 307px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_MLT09_L_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 521px; left: 429px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M44AC_SDF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 531px; left: 472px; position:absolute;color:#4cff00;text-align:right;font-size:12px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L5AFC_SF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:54px; display:block; top: 660px; left: 78px; position:absolute;color:#4cff00;text-align:right;font-size:12px; height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L5AFC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:54px; display:block; top: 678px; left: 78px; position:absolute;color:#4cff00;text-align:right;font-size:12px; height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L5AFC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:54px; display:block; top: 696px; left: 78px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L5AFC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:54px; display:block; top: 715px; left: 78px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L7AFC_SF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 660px; left: 135px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L7AFC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 678px; left: 135px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L7AFC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 696px; left: 135px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L7AFC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 715px; left: 135px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L9AFC_SF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 660px; left: 220px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L9AFC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 678px; left: 220px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L9AFC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 696px; left: 220px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L9AFC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:84px; display:block; top: 715px; left: 220px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L11AFC_SF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:48px; display:block; top: 660px; left: 308px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L11AFC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:48px; display:block; top: 678px; left: 308px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L11AFC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:48px; display:block; top: 698px; left: 308px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L11AFC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:48px; display:block; top: 715px; left: 308px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="Conflict"  data-option="id='zc_nxjc_byc_byf>dcs01_F_1M44AC_SDF_M>DCS'"style="width:46px; display:block; top: 660px; left: 360px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M44AC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 678px; left: 360px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M44AC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 698px; left: 360px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M44AC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 715px; left: 360px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X1AFC_SF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 660px; left: 410px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X1AFC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 678px; left: 410px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X1AFC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 698px; left: 410px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X1AFC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 715px; left: 410px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X2AFC_SF_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 660px; left: 464px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X2AFC_RAT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 678px; left: 464px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X2FC_SET>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 698px; left: 464px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_X2AFC_TOL_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:59px; display:block; top: 715px; left: 464px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L_FF1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 660px; left: 525px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L_RAT1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 678px; left: 525px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L_FEED_TOL1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 698px; left: 525px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_L_FEED_LJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:65px; display:block; top: 715px; left: 525px; position:absolute;color:#4cff00;text-align:right;font-size:11px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE09_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 690px; left: 599px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE10_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 690px; left: 651px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE07_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 738px; left: 597px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE08_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 738px; left: 649px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 681px; left: 710px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 698px; left: 710px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T3_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 715px; left: 710px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T4_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 734px; left: 710px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T5_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 681px; left: 764px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T6_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 698px; left: 764px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T7_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 715px; left: 764px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T8_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 734px; left: 764px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T10_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 698px; left: 824px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M29AC_T11_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 714px; left: 824px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M16M_TA_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 679px; left: 876px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M16M_TB_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 680px; left: 928px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M16M_T1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 734px; left: 873px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M16M_T2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 734px; left: 928px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M17M_TA_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 679px; left: 988px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M17M_TB_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 680px; left: 1046px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M17M_T1_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 735px; left: 991px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M16M_TC_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 699px; left: 904px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M17M_T2_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 735px; left: 1047px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1M17M_TC_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 700px; left: 1016px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE19_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 680px; left: 1109px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE22_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 698px; left: 1109px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE25_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 717px; left: 1109px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE28_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 737px; left: 1109px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE20_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 681px; left: 1162px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE23_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 700px; left: 1162px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE26_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 719px; left: 1162px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE29_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 735px; left: 1162px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE21_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 680px; left: 1215px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE24_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 697px; left: 1215px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE27_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 716px; left: 1215px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE30_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 734px; left: 1215px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE33_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 679px; left: 1276px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE34_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 679px; left: 1327px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE35_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 679px; left: 1377px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE31_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 709px; left: 1294px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE32_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 709px; left: 1365px; position:absolute;color:#4cff00;text-align:right;font-size:12px; height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE36_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 738px; left: 1294px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE37_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 738px; left: 1365px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
            <div class="AnlogSignal mchart" id="zc_nxjc_byc_byf>dcs01_F_1MTE11_T_M>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 707px; left: 629px; position:absolute;color:#4cff00;text-align:right;font-size:12px;height: 16px;"></div>
<%--            <div class="Conflict"  data-option="id='zc_nxjc_byc_byf>dcs01_T43112_SM3>DCS'" style="width:40px;display:block; top: 70px; left: 56px; position:absolute;"></div>--%>
        <%--汉字隐藏--%>
            <div id="zc_nxjc_byc_byf>dcs01_SNMKYJGZ1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 142px; left: 12px; color:red;font-size:17px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_SNMKYJGZ2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 142px; left: 62px; color:red;font-size:17px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_SNMKYJGZ3>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 142px; left: 125px; color:red;font-size:17px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_SNMKYJGZ4>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 142px; left: 191px; color:red;font-size:17px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M31M_GG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 74px; left: 333px; color:red;font-size:12px;"> 发现金属</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L5Mb_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 229px; left: 5px; color:red;font-size:12px;"> 低速报警</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L5Mb_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 229px; left: 60px; color:yellow;font-size:12px;"> I度跑偏</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L5Mb_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 229px; left: 108px; color:red;font-size:12px;"> II度跑偏</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L13M_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 269px; left: 3px; color:red;font-size:12px;"> 低速报警</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L13M_SE1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 269px; left: 58px; color:yellow;font-size:12px; width: 44px; height: 12px;"> I度跑偏</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L13M_SE2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 268px; left: 109px; color:red;font-size:12px; width: 56px;"> II度跑偏</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M17ALP_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 269px; left: 370px; color:yellow;font-size:12px;"> 备妥</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M17ALP_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 286px; left: 361px; color:#4cff00;font-size:12px;"> 启动完毕</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M17ALP_FT>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 304px; left: 371px; color:red;font-size:12px; right: 1085px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M29AC_LMF>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 318px; left: 448px; color:#4cff00;font-size:12px;"> 开</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M29AC_LMR>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 318px; left: 498px; color:#4cff00;font-size:12px;"> 关</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M16ALP_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 269px; left: 541px; color:yellow;font-size:12px;"> 备妥</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M16ALP_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 286px; left: 530px; color:#4cff00;font-size:12px;"> 启动完毕</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M16ALP_FT>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 304px; left: 540px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M35AC_GG>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 370px; left: 170px; color:red;font-size:12px;"> 发现金属</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L3MA_SL>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 457px; left: 195px; color:red;font-size:12px;"> 料位开关</div> 
            <div id="zc_nxjc_byc_byf>dcs01_L24M_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 501px; left: 91px; color:red;font-size:12px;"> 低速报警</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M33_SL>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 516px; left: 223px; color:red;font-size:12px;"> 料位开关</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M33_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 535px; left: 224px; color:#4cff00;font-size:12px;"> 速度正常</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M44AC_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 495px; left: 576px; color:red;font-size:12px;"> 1号计量装置故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M44AC_RN3>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 512px; left: 576px; color:red;font-size:12px;"> 1号给料装置故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M44AC_FT2>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 527px; left: 576px; color:red;font-size:12px;"> 2号计量装置故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M44AC_RN4>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 545px; left: 576px; color:red;font-size:12px;"> 2号给料装置故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M42_SL>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 569px; left: 595px; color:red;font-size:12px;"> 料位开关</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M42_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 586px; left: 594px; color:#4cff00;font-size:12px;"> 速度正常</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M42_SE>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 602px; left: 597px; color:red;font-size:12px;"> 跑偏</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M45ALC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 566px; left: 310px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M19ALC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 575px; left: 845px; color:#4cff00;font-size:12px;"> 允许</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M18ALC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 574px; left: 939px; color:#4cff00;font-size:12px;"> 允许</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M20ALC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 613px; left: 845px; color:#4cff00;font-size:12px;"> 允许</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M21ALC_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 612px; left: 939px; color:#4cff00;font-size:12px;"> 允许</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M19ALC_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 590px; left: 845px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M18ALC_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 590px; left: 939px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M20ALC_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 626px; left: 845px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M21ALC_FT1>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 626px; left: 939px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M13ACP_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 450px; left: 802px; color:yellow;font-size:10px;"> 备妥</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M13ACP_STA>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 463px; left: 794px; color:#4cff00;font-size:10px;"> 进相状态</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M13ACP_RN>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 475px; left: 794px; color:#4cff00;font-size:10px;"> 允许进相</div> 

            <div id="zc_nxjc_byc_byf>dcs01_F_1M10_SL>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 595px; left: 1105px; color:red;font-size:12px;"> 料位开关</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M10_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 611px; left: 1105px; color:#4cff00;font-size:12px;"> 速度正常</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M13ALP_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 482px; left: 1093px; color:yellow;font-size:12px;"> 备妥</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M13ALP_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 498px; left: 1093px; color:#4cff00;font-size:12px;"> 启动完毕</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M13ALP_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 516px; left: 1093px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M23AC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 485px; left: 1368px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M1_SP>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 329px; left: 1332px; color:#4cff00;font-size:12px;"> 速度正常</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M1_SL>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 311px; left: 1331px; color:red;font-size:12px;"> 料位开关</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 342px; left: 843px; color:#4cff00;font-size:12px;"> 1#库下料</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_2HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 362px; left: 844px; color:#4cff00;font-size:12px;"> 2#库下料</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_3HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 386px; left: 843px; color:#4cff00;font-size:12px;"> 3#库下料</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_4HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 407px; left: 843px; color:#4cff00;font-size:12px;"> 4#库下料</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_5HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 342px; left: 904px; color:#4cff00;font-size:12px;"> 5#库下料</div>
            <div id="zc_nxjc_byc_byf>dcs01_F_6HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 362px; left: 904px; color:#4cff00;font-size:12px;"> 6#库下料</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_7HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 386px; left: 906px; color:#4cff00;font-size:12px;"> 7#库下料</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_8HK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 407px; left: 906px; color:#4cff00;font-size:12px;"> 8#库下料</div>
            <div id="zc_nxjc_byc_byf>dcs01_F_1M25AC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 102px; left: 711px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M7ALC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 105px; left: 1002px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M3ALC_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 127px; left: 1241px; color:red;font-size:12px;"> 故障</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M8ALP_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 30px; left: 1168px; color:yellow;font-size:12px;"> 备妥</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M8ALP_OK>DCS" class="TextDisplay" data-option="Display='1'" style="position:absolute; top: 48px; left: 1162px; color:#4cff00;font-size:12px;"> 启动完毕</div> 
            <div id="zc_nxjc_byc_byf>dcs01_F_1M8ALP_FT>DCS" class="TextDisplay" data-option="Display='0'" style="position:absolute; top: 65px; left: 1168px; color:red;font-size:12px;"> 故障</div> 


         <%--棒图--%>
            <div class="BarGraph mchart" id="zc_nxjc_byc_byf>dcs01_MLT09_L_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:13px; height:47px; position:absolute; top: 476px; left: 505px;"></div>
            <div class="BarGraph mchart" id="zc_nxjc_byc_byf>dcs01_F_1MWT01_W_M>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:11px; height:43px; position:absolute; top: 282px; left: 471px;"></div>
          
    </div>
</body>
</html>
